# Generated by Django 5.2.15 on 2026-07-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('app_version', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_utc', models.DateTimeField()),
                ('received_utc', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('cpu_name', models.CharField(blank=True, default='', max_length=128)),
                ('cpu_physical_cores', models.IntegerField(default=0)),
                ('ram_total_mb', models.BigIntegerField(default=0)),
                ('os_name', models.CharField(blank=True, default='', max_length=128)),
                ('os_build', models.BigIntegerField(default=0)),
                ('gpu_name', models.CharField(blank=True, default='', max_length=128)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_reports', to='api.installation')),
            ],
            options={
                'indexes': [models.Index(fields=['installation', '-received_utc'], name='api_hardwar_install_f80a3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_row_id', models.BigIntegerField()),
                ('interval_start_utc', models.DateTimeField()),
                ('interval_seconds', models.IntegerField(default=0)),
                ('open_seconds', models.IntegerField(default=0)),
                ('focus_seconds', models.IntegerField(default=0)),
                ('left_clicks', models.BigIntegerField(default=0)),
                ('middle_clicks', models.BigIntegerField(default=0)),
                ('right_clicks', models.BigIntegerField(default=0)),
                ('key_presses', models.BigIntegerField(default=0)),
                ('ribbon_actions', models.JSONField(default=dict)),
                ('received_utc', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='api.installation')),
            ],
            options={
                'indexes': [models.Index(fields=['interval_start_utc'], name='api_usagere_interva_11864f_idx')],
                'constraints': [models.UniqueConstraint(fields=('installation', 'client_row_id'), name='unique_installation_client_row')],
            },
        ),
    ]
