// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
/* Verifies the 2D snap geometry of RenderPage2D.cpp against hand-computed reference cases
   (snapping.md section 15, stage 11). The code under test is #included VERBATIM from the source
   file, so this cannot drift from what the application compiles. */
#include "Snap.h"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdint>

static int failures = 0;
#define CHECK(cond) do { if (!(cond)) { std::printf("FAIL:%d  %s\n", __LINE__, #cond); ++failures; } } while (0)
#define NEAR(a, b) (std::abs((a) - (b)) < 1e-7)

namespace {
#include "snap2d_extracted.inc"   // Generated by extract_2d_geometry.py.
}

static bool HasPoint(const double xs[8], const double ys[8], size_t n, double x, double y) {
    for (size_t i = 0; i < n; ++i) if (NEAR(xs[i], x) && NEAR(ys[i], y)) return true;
    return false;
}

int main() {
    // ---- segment x segment ---------------------------------------------------------------
    {
        Cad2DSnapSegment a{ -10.0, 0.0, 10.0, 0.0, 1 };
        Cad2DSnapSegment b{ 3.0, -5.0, 3.0, 5.0, 2 };
        double x = 0.0, y = 0.0;
        CHECK(SnapSegmentIntersection(a, b, x, y));
        CHECK(NEAR(x, 3.0) && NEAR(y, 0.0));
        // Parallel: no single crossing.
        Cad2DSnapSegment c{ -10.0, 4.0, 10.0, 4.0, 3 };
        CHECK(!SnapSegmentIntersection(a, c, x, y));
        // Crossing only beyond the end of one segment is an APPARENT intersection: phase 2, so it
        // must not be offered here.
        Cad2DSnapSegment d{ 30.0, -5.0, 30.0, 5.0, 4 };
        CHECK(!SnapSegmentIntersection(a, d, x, y));
    }

    // ---- segment x circle, and segment x ellipse ------------------------------------------
    {
        Cad2DSnapConic circle{}; circle.cx = 0.0; circle.cy = 0.0; circle.rx = 5.0; circle.ry = 5.0;
        Cad2DSnapSegment through{ -10.0, 0.0, 10.0, 0.0, 1 };
        double xs[2], ys[2];
        size_t n = SnapSegmentConicIntersections(through, circle, xs, ys);
        CHECK(n == 2);
        CHECK(HasPoint(xs, ys, n, -5.0, 0.0) && HasPoint(xs, ys, n, 5.0, 0.0));
        // A chord that stops inside the circle yields only the one crossing it actually reaches.
        Cad2DSnapSegment half{ 0.0, 0.0, 10.0, 0.0, 1 };
        n = SnapSegmentConicIntersections(half, circle, xs, ys);
        CHECK(n == 1 && NEAR(xs[0], 5.0));
        // A tangent line touches once (a double root); a miss returns nothing.
        Cad2DSnapSegment tangent{ -10.0, 5.0, 10.0, 5.0, 1 };
        n = SnapSegmentConicIntersections(tangent, circle, xs, ys);
        CHECK(n == 2 && NEAR(xs[0], 0.0) && NEAR(ys[0], 5.0));   // Same point twice.
        Cad2DSnapSegment miss{ -10.0, 9.0, 10.0, 9.0, 1 };
        CHECK(SnapSegmentConicIntersections(miss, circle, xs, ys) == 0);
        // Ellipse: rx 8, ry 3. The x axis must cut it at +/-8, the y axis at +/-3.
        Cad2DSnapConic ellipse{}; ellipse.rx = 8.0; ellipse.ry = 3.0;
        n = SnapSegmentConicIntersections(Cad2DSnapSegment{ -20.0, 0.0, 20.0, 0.0, 1 }, ellipse, xs, ys);
        CHECK(n == 2 && HasPoint(xs, ys, n, -8.0, 0.0) && HasPoint(xs, ys, n, 8.0, 0.0));
        n = SnapSegmentConicIntersections(Cad2DSnapSegment{ 0.0, -20.0, 0.0, 20.0, 1 }, ellipse, xs, ys);
        CHECK(n == 2 && HasPoint(xs, ys, n, 0.0, -3.0) && HasPoint(xs, ys, n, 0.0, 3.0));
        // A rotated ellipse: 90 degrees swaps the radii, so the x axis now cuts at +/-3.
        Cad2DSnapConic rotated = ellipse; rotated.rotation = kSnapPi * 0.5;
        n = SnapSegmentConicIntersections(Cad2DSnapSegment{ -20.0, 0.0, 20.0, 0.0, 1 }, rotated, xs, ys);
        CHECK(n == 2 && HasPoint(xs, ys, n, -3.0, 0.0) && HasPoint(xs, ys, n, 3.0, 0.0));
    }

    // ---- perpendicular feet ---------------------------------------------------------------
    {
        // Circle: the feet are where the line through the centre meets it - both sides.
        Cad2DSnapConic circle{}; circle.rx = 5.0; circle.ry = 5.0;
        double xs[8], ys[8];
        size_t n = SnapConicPerpendicularFeet(circle, 20.0, 0.0, xs, ys);
        CHECK(n == 2 && HasPoint(xs, ys, n, 5.0, 0.0) && HasPoint(xs, ys, n, -5.0, 0.0));
        // At the centre every direction is normal, so there is no answer to give.
        CHECK(SnapConicPerpendicularFeet(circle, 0.0, 0.0, xs, ys) == 0);

        // Ellipse, numeric path. From a point on the major axis well outside, the near foot is the
        // vertex (8, 0): hand-computable, and the case a closed form would also have to get right.
        Cad2DSnapConic ellipse{}; ellipse.rx = 8.0; ellipse.ry = 3.0;
        n = SnapConicPerpendicularFeet(ellipse, 40.0, 0.0, xs, ys);
        CHECK(n >= 2);
        CHECK(HasPoint(xs, ys, n, 8.0, 0.0) && HasPoint(xs, ys, n, -8.0, 0.0));
        // Every root must genuinely satisfy dot(P - E(t), E'(t)) == 0.
        for (size_t i = 0; i < n; ++i) {
            const double t = ellipse.ParameterOf(xs[i], ys[i]);
            double px = 0.0, py = 0.0, dx = 0.0, dy = 0.0;
            ellipse.PointAt(t, px, py);
            ellipse.TangentAt(t, dx, dy);
            CHECK(std::abs((40.0 - px) * dx + (0.0 - py) * dy) < 1e-6);
        }
        // From a general off-axis point the foot must still be ON the ellipse.
        n = SnapConicPerpendicularFeet(ellipse, 11.0, 7.0, xs, ys);
        CHECK(n >= 2);
        for (size_t i = 0; i < n; ++i) {
            CHECK(std::abs((xs[i] * xs[i]) / 64.0 + (ys[i] * ys[i]) / 9.0 - 1.0) < 1e-9);
        }
    }

    // ---- tangent points --------------------------------------------------------------------
    {
        Cad2DSnapConic circle{}; circle.rx = 3.0; circle.ry = 3.0;
        double xs[8], ys[8];
        // From (5, 0) to a radius-3 circle: tangent length 4, touch points (9/5, +/-12/5).
        size_t n = SnapConicTangentPoints(circle, 5.0, 0.0, xs, ys);
        CHECK(n == 2);
        CHECK(HasPoint(xs, ys, n, 1.8, 2.4) && HasPoint(xs, ys, n, 1.8, -2.4));
        // Inside the circle, and exactly on it, there is no tangent from the point.
        CHECK(SnapConicTangentPoints(circle, 1.0, 0.0, xs, ys) == 0);
        CHECK(SnapConicTangentPoints(circle, 3.0, 0.0, xs, ys) == 0);

        // Ellipse, numeric path: every touch point must be on the curve and its chord parallel to
        // the tangent there.
        Cad2DSnapConic ellipse{}; ellipse.rx = 8.0; ellipse.ry = 3.0;
        n = SnapConicTangentPoints(ellipse, 30.0, 12.0, xs, ys);
        CHECK(n == 2);
        for (size_t i = 0; i < n; ++i) {
            CHECK(std::abs((xs[i] * xs[i]) / 64.0 + (ys[i] * ys[i]) / 9.0 - 1.0) < 1e-9);
            const double t = ellipse.ParameterOf(xs[i], ys[i]);
            double dx = 0.0, dy = 0.0;
            ellipse.TangentAt(t, dx, dy);
            CHECK(std::abs((30.0 - xs[i]) * dy - (12.0 - ys[i]) * dx) < 1e-6);
        }
    }

    // ---- arc sweep, matching Shader2D_CurvePixel.hlsl's AngleInCCWSweep --------------------
    {
        Cad2DSnapConic arc{}; arc.rx = 5.0; arc.ry = 5.0; arc.isArc = true;
        arc.startAngle = 0.0;                 // Quarter arc, CCW from +x to +y.
        arc.endAngle = kSnapPi * 0.5;
        CHECK(SnapAngleInSweep(arc, 0.0));
        CHECK(SnapAngleInSweep(arc, kSnapPi * 0.25));
        CHECK(SnapAngleInSweep(arc, kSnapPi * 0.5));
        CHECK(!SnapAngleInSweep(arc, kSnapPi));
        CHECK(!SnapAngleInSweep(arc, -kSnapPi * 0.25));
        // A sweep that wraps through zero is the case a naive start<=a<=end test gets wrong.
        Cad2DSnapConic wrap = arc;
        wrap.startAngle = kSnapPi * 1.5;
        wrap.endAngle = kSnapPi * 0.5;
        CHECK(SnapAngleInSweep(wrap, 0.0));
        CHECK(SnapAngleInSweep(wrap, kSnapPi * 1.75));
        CHECK(!SnapAngleInSweep(wrap, kSnapPi));
        // A full circle is not an arc and takes every parameter.
        Cad2DSnapConic full{}; full.rx = 5.0; full.ry = 5.0;
        CHECK(SnapAngleInSweep(full, 1.234) && SnapAngleInSweep(full, -2.0));
    }

    // ---- the conic parameterisation must be the shader's ----------------------------------
    {
        // PointAt and ParameterOf must invert each other, including under rotation - a snap point
        // the renderer does not draw on the curve is a defect the user sees.
        Cad2DSnapConic conic{}; conic.cx = 3.0; conic.cy = -2.0; conic.rx = 7.0; conic.ry = 2.5;
        conic.rotation = 0.7;
        for (int i = 0; i < 32; ++i) {
            const double t = -kSnapPi + kSnapTwoPi * i / 32.0;
            double x = 0.0, y = 0.0;
            conic.PointAt(t, x, y);
            double back = conic.ParameterOf(x, y);
            CHECK(std::abs(std::remainder(back - t, kSnapTwoPi)) < 1e-9);
        }
        // The four quadrants are the curve's OWN frame, so a 90-degree rotation moves them.
        Cad2DSnapConic axis{}; axis.rx = 4.0; axis.ry = 4.0;
        double x = 0.0, y = 0.0;
        axis.PointAt(0.0, x, y); CHECK(NEAR(x, 4.0) && NEAR(y, 0.0));
        axis.rotation = kSnapPi * 0.5;
        axis.PointAt(0.0, x, y); CHECK(NEAR(x, 0.0) && NEAR(y, 4.0));
    }

    // ---- nearest point on a SEGMENT is clamped to the drawn stroke -------------------------
    {
        Cad2DSnapSegment s{ 0.0, 0.0, 10.0, 0.0, 1 };
        double x = 0.0, y = 0.0;
        ClosestPointOnSegment(4.0, 3.0, s, x, y);
        CHECK(NEAR(x, 4.0) && NEAR(y, 0.0));
        ClosestPointOnSegment(-8.0, 1.0, s, x, y);   // Past the start: clamps to the endpoint.
        CHECK(NEAR(x, 0.0) && NEAR(y, 0.0));
        ClosestPointOnSegment(99.0, 1.0, s, x, y);
        CHECK(NEAR(x, 10.0) && NEAR(y, 0.0));
    }

    // ---- the gatherer's ortho filter -------------------------------------------------------
    {
        // With the direction locked to +x from (0,0), a candidate off that ray is not reachable
        // and must not be offered, however close to the cursor it is (section 11).
        SnapCandidateSet set(kDefaultSnapMask2D, 1.0);
        Cad2DSnapGatherer g{};
        g.set = &set;
        g.cursorXCU = 10.0; g.cursorYCU = 0.0;
        g.zoom = 1.0; g.reachCU = 24.0;
        g.orthoActive = true;
        g.anchorXCU = 0.0; g.anchorYCU = 0.0;
        g.orthoDirX = 1.0; g.orthoDirY = 0.0;
        g.Offer(11.0, 5.0, SnapKind::End, 14, 1);   // 5 CU off the ray: rejected.
        SnapResult r{};
        CHECK(!set.Resolve(r));
        g.Offer(11.0, 0.0, SnapKind::End, 14, 2);   // On the ray: accepted.
        CHECK(set.Resolve(r) && r.objectId == 2);
    }
    // The broad-phase box reject must not drop a record the cursor can still reach.
    {
        Cad2DSnapGatherer g{};
        g.cursorXCU = 0.0; g.cursorYCU = 0.0; g.zoom = 1.0; g.reachCU = 24.0;
        CHECK(g.NearBox(20.0, -1.0, 22.0, 1.0));    // 20 CU away, inside the 24 CU reach.
        CHECK(!g.NearBox(30.0, -1.0, 32.0, 1.0));   // 30 CU away: nothing on it can win.
        CHECK(g.NearBox(-100.0, -100.0, 100.0, 100.0));   // Cursor inside the box.
    }

    std::printf(failures == 0 ? "snap 2D geometry: ALL PASS\n" : "snap 2D geometry: %d FAILURES\n", failures);
    return failures == 0 ? 0 : 1;
}
