// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
#pragma once
#include <string>

// Local cryptographic identity of one installation. Design intent:
// 1. Installation key pair (Ed25519): generated by the installer (or by the application on
//    first launch when missing) and stored at
//    %LOCALAPPDATA%\Mission Vishwakarma\Credentials\InstallationKey.pem
//    The PUBLIC key uniquely identifies this installation towards our servers. It carries
//    no personally identifiable information.
// 2. Session key pair (Ed25519): created fresh in memory on every application launch for
//    ephemeral communications / forward secrecy with peers and server. The session public
//    key is signed by the installation key so peers can verify the chain.
// All primitives are OpenSSL (libcrypto), statically linked. This file is compiled into
// both Vishwakarma.exe and VishwakarmaSetup.exe (installer only uses EnsureInstallationKey).
namespace AccountManager {

// Creates the installation key pair if InstallationKey.pem does not exist yet.
// Safe to call repeatedly; returns true when a valid key exists on return.
bool EnsureInstallationKey();

// Called once at application launch: ensures the installation key exists, then creates the
// per-launch session key pair and signs its public key with the installation key.
bool InitializeOnLaunch();

// Raw 32-byte Ed25519 public keys, base64 encoded. Empty string when unavailable.
std::string InstallationPublicKeyBase64();
std::string SessionPublicKeyBase64();

// Base64 Ed25519 signature (by the installation key) over the raw 32-byte session public key.
std::string SessionKeySignatureBase64();

// Signs an arbitrary message with the per-launch session key. Returns base64 signature,
// empty string on failure. Used to authenticate telemetry uploads.
std::string SignWithSessionKey(const std::string& message);

} // namespace AccountManager
