// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.

// 1st version of this file was complete autogenerated by Codex by specifying the MPV part of our storage specification.

#pragma once

#include <string>

struct DATASETTAB;

class DataStorage {
public:
    static DataStorage& Instance();

    bool SaveTabToYyy(DATASETTAB& tab, const std::wstring& filePath, std::string* errorMessage = nullptr);
    bool LoadYyyIntoTab(DATASETTAB& tab, const std::wstring& filePath, std::string* errorMessage = nullptr);

private:
    DataStorage() = default;
};

