// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.

// 1st version of this file was complete autogenerated by Codex by specifying the MPV part of our storage specification.

#include "DataStorage.h"

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <limits>
#include <random>
#include <string>
#include <vector>

#include "CommonNamedNumbers.h"
#include "DataStorage_CONE.pb.h"
#include "DataStorage_CUBOID.pb.h"
#include "DataStorage_CYLINDER.pb.h"
#include "DataStorage_FRUSTUM_OF_CONE.pb.h"
#include "DataStorage_FRUSTUM_OF_PYRAMID.pb.h"
#include "DataStorage_PARALLELEPIPED.pb.h"
#include "DataStorage_PIPE.pb.h"
#include "DataStorage_PYRAMID.pb.h"
#include "DataStorage_SPHERE.pb.h"
#include "MemoryManagerGPU-DirectX12.h"
#include "sqlite3.h"
#include "विश्वकर्मा.h"
#include "डेटा-सामान्य-3D.h"

namespace {

namespace pb = vishwakarma::storage;

using VishwakarmaStorage::LifecycleState;
using VishwakarmaStorage::ObjectType;

void SetError(std::string* errorMessage, const std::string& value) {
    if (errorMessage) *errorMessage = value;
}

std::string SqliteError(sqlite3* db, const char* prefix) {
    std::string result = prefix ? prefix : "SQLite error";
    if (db) {
        result += ": ";
        result += sqlite3_errmsg(db);
    }
    return result;
}

struct SQLiteDatabase {
    sqlite3* db = nullptr;
    ~SQLiteDatabase() {
        if (db) sqlite3_close(db);
    }
};

struct SQLiteStatement {
    sqlite3_stmt* stmt = nullptr;
    ~SQLiteStatement() {
        if (stmt) sqlite3_finalize(stmt);
    }
};

bool ExecSql(sqlite3* db, const char* sql, std::string* errorMessage) {
    char* error = nullptr;
    int rc = sqlite3_exec(db, sql, nullptr, nullptr, &error);
    if (rc != SQLITE_OK) {
        std::string message = error ? error : sqlite3_errmsg(db);
        sqlite3_free(error);
        SetError(errorMessage, message);
        return false;
    }
    return true;
}

bool Prepare(sqlite3* db, const char* sql, SQLiteStatement& statement, std::string* errorMessage) {
    int rc = sqlite3_prepare_v2(db, sql, -1, &statement.stmt, nullptr);
    if (rc != SQLITE_OK) {
        SetError(errorMessage, SqliteError(db, "Failed to prepare statement"));
        return false;
    }
    return true;
}

std::vector<uint8_t> GenerateUuidBytes() {
    std::vector<uint8_t> uuid(16);
    std::random_device randomDevice;
    for (uint8_t& byte : uuid) {
        byte = static_cast<uint8_t>(randomDevice() & 0xFF);
    }
    return uuid;
}

int64_t CurrentUnixTimeSeconds() {
    using namespace std::chrono;
    return duration_cast<seconds>(system_clock::now().time_since_epoch()).count();
}

bool EnsureSchema(sqlite3* db, std::string* errorMessage) {
    const char* schemaSql =
        "PRAGMA foreign_keys = ON;"
        "PRAGMA journal_mode = WAL;"
        "PRAGMA synchronous = NORMAL;"
        "PRAGMA temp_store = MEMORY;"
        "CREATE TABLE IF NOT EXISTS file_info ("
        "  key TEXT PRIMARY KEY,"
        "  value BLOB NOT NULL"
        ");"
        "CREATE TABLE IF NOT EXISTS object_store ("
        "  object_id INTEGER PRIMARY KEY CHECK (object_id > 0 AND object_id < 1099511627776),"
        "  parent_id INTEGER,"
        "  object_type INTEGER NOT NULL,"
        "  schema_version INTEGER NOT NULL DEFAULT 1,"
        "  lifecycle_state INTEGER NOT NULL DEFAULT 0 CHECK (lifecycle_state BETWEEN 0 AND 3),"
        "  data BLOB NOT NULL,"
        "  FOREIGN KEY(parent_id) REFERENCES object_store(object_id)"
        ");"
        "CREATE INDEX IF NOT EXISTS idx_object_parent_live "
        "ON object_store(parent_id, object_id) WHERE lifecycle_state = 0;"
        "CREATE INDEX IF NOT EXISTS idx_object_type_live "
        "ON object_store(object_type, object_id) WHERE lifecycle_state = 0;";

    return ExecSql(db, schemaSql, errorMessage);
}

bool UpsertFileInfoBlob(sqlite3* db, const char* key, const void* value, int valueSize,
    std::string* errorMessage) {
    SQLiteStatement statement;
    if (!Prepare(db, "INSERT OR REPLACE INTO file_info(key, value) VALUES(?, ?);",
        statement, errorMessage)) {
        return false;
    }

    sqlite3_bind_text(statement.stmt, 1, key, -1, SQLITE_TRANSIENT);
    sqlite3_bind_blob(statement.stmt, 2, value, valueSize, SQLITE_TRANSIENT);

    int rc = sqlite3_step(statement.stmt);
    if (rc != SQLITE_DONE) {
        SetError(errorMessage, SqliteError(db, "Failed to write file_info"));
        return false;
    }
    return true;
}

bool UpsertFileInfoText(sqlite3* db, const char* key, const std::string& value,
    std::string* errorMessage) {
    return UpsertFileInfoBlob(db, key, value.data(), static_cast<int>(value.size()), errorMessage);
}

bool FileInfoKeyExists(sqlite3* db, const char* key) {
    SQLiteStatement statement;
    if (sqlite3_prepare_v2(db, "SELECT 1 FROM file_info WHERE key = ? LIMIT 1;",
        -1, &statement.stmt, nullptr) != SQLITE_OK) {
        return false;
    }

    sqlite3_bind_text(statement.stmt, 1, key, -1, SQLITE_TRANSIENT);
    return sqlite3_step(statement.stmt) == SQLITE_ROW;
}

bool EnsureFileInfo(sqlite3* db, uint64_t objectCounterNext, std::string* errorMessage) {
    if (!FileInfoKeyExists(db, "file_uuid")) {
        std::vector<uint8_t> uuid = GenerateUuidBytes();
        if (!UpsertFileInfoBlob(db, "file_uuid", uuid.data(), static_cast<int>(uuid.size()), errorMessage)) {
            return false;
        }
    }

    const std::string now = std::to_string(CurrentUnixTimeSeconds());
    return UpsertFileInfoText(db, "file_format_version", "yyy-mvp-1", errorMessage) &&
        UpsertFileInfoText(db, "file_kind", "yyy", errorMessage) &&
        UpsertFileInfoText(db, "last_saved_by_application", "Vishwakarma", errorMessage) &&
        UpsertFileInfoText(db, "last_saved_time_utc", now, errorMessage) &&
        UpsertFileInfoText(db, "schema_catalog_hash", "geometry3d-mvp-schema-v1", errorMessage) &&
        UpsertFileInfoText(db, "schema_catalog_version", "1", errorMessage) &&
        UpsertFileInfoText(db, "object_counter_next", std::to_string(objectCounterNext), errorMessage);
}

void WritePoint3(pb::Point3F* message, const XMFLOAT3& point) {
    message->set_x(point.x);
    message->set_y(point.y);
    message->set_z(point.z);
}

XMFLOAT3 ReadPoint3(const pb::Point3F& message) {
    return XMFLOAT3(message.x(), message.y(), message.z());
}

void WriteColor4(pb::Color4F* message, const XMHALF4& color) {
    message->set_r(DirectX::PackedVector::XMConvertHalfToFloat(color.x));
    message->set_g(DirectX::PackedVector::XMConvertHalfToFloat(color.y));
    message->set_b(DirectX::PackedVector::XMConvertHalfToFloat(color.z));
    message->set_a(DirectX::PackedVector::XMConvertHalfToFloat(color.w));
}

XMHALF4 ReadColor4(const pb::Color4F& message) {
    return XMHALF4(message.r(), message.g(), message.b(), message.a());
}

XMHALF4 DefaultColor4() {
    return XMHALF4(0.8f, 0.8f, 0.8f, 1.0f);
}

template <typename Message>
bool SerializeMessage(const Message& message, std::vector<uint8_t>& payload, std::string* errorMessage) {
    std::string bytes;
    if (!message.SerializeToString(&bytes)) {
        SetError(errorMessage, "Could not serialize protobuf payload.");
        return false;
    }

    payload.assign(bytes.begin(), bytes.end());
    return true;
}

template <typename Message>
bool ParseMessage(const std::vector<uint8_t>& payload, Message& message) {
    if (payload.size() > static_cast<size_t>((std::numeric_limits<int>::max)())) {
        return false;
    }

    const void* data = payload.empty()
        ? static_cast<const void*>("")
        : static_cast<const void*>(payload.data());
    return message.ParseFromArray(data, static_cast<int>(payload.size()));
}

bool EncodePyramid(const PYRAMID& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Pyramid message;
    for (const XMFLOAT3& vertex : object.vertices) {
        WritePoint3(message.add_vertices(), vertex);
    }
    for (const XMHALF4& color : object.colors) {
        WriteColor4(message.add_colors(), color);
    }
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeCuboid(const CUBOID& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Cuboid message;
    for (const XMFLOAT3& vertex : object.vertices) {
        WritePoint3(message.add_vertices(), vertex);
    }
    WriteColor4(message.mutable_color(), object.colors);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeCone(const CONE& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Cone message;
    WritePoint3(message.mutable_apex(), object.apex);
    WritePoint3(message.mutable_base_center(), object.baseCenter);
    message.set_radius(object.radius);
    WriteColor4(message.mutable_color_base(), object.colorBase);
    WriteColor4(message.mutable_color_incline(), object.colorIncline);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeCylinder(const CYLINDER& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Cylinder message;
    WritePoint3(message.mutable_p1(), object.p1);
    WritePoint3(message.mutable_p2(), object.p2);
    message.set_radius(object.radius);
    WriteColor4(message.mutable_color_base(), object.colorBase);
    WriteColor4(message.mutable_color_top(), object.colorTop);
    WriteColor4(message.mutable_color_incline(), object.colorIncline);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeParallelepiped(const PARALLELEPIPED& object, std::vector<uint8_t>& payload,
    std::string* errorMessage) {
    pb::Parallelepiped message;
    for (const XMFLOAT3& vertex : object.vertices) {
        WritePoint3(message.add_vertices(), vertex);
    }
    WriteColor4(message.mutable_color(), object.colors);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeSphere(const SPHERE& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Sphere message;
    WritePoint3(message.mutable_center(), object.center);
    message.set_radius(object.radius);
    WriteColor4(message.mutable_color(), object.color);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeFrustumOfPyramid(const FRUSTUM_OF_PYRAMID& object, std::vector<uint8_t>& payload,
    std::string* errorMessage) {
    pb::FrustumOfPyramid message;
    for (const XMFLOAT3& vertex : object.vertices) {
        WritePoint3(message.add_vertices(), vertex);
    }
    WriteColor4(message.mutable_color_base(), object.colorBase);
    WriteColor4(message.mutable_color_top(), object.colorTop);
    WriteColor4(message.mutable_color_incline(), object.colorIncline);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeFrustumOfCone(const FRUSTUM_OF_CONE& object, std::vector<uint8_t>& payload,
    std::string* errorMessage) {
    pb::FrustumOfCone message;
    WritePoint3(message.mutable_bottom_center(), object.bottomCenter);
    WritePoint3(message.mutable_top_center(), object.topCenter);
    message.set_bottom_radius(object.bottomRadius);
    message.set_top_radius(object.topRadius);
    WriteColor4(message.mutable_color_base(), object.colorBase);
    WriteColor4(message.mutable_color_top(), object.colorTop);
    WriteColor4(message.mutable_color_incline(), object.colorIncline);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodePipe(const PIPE& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Pipe message;
    WritePoint3(message.mutable_center1(), object.center1);
    WritePoint3(message.mutable_center2(), object.center2);
    message.set_outside_diameter(object.outsideDiameter);
    message.set_inside_diameter(object.insideDiameter);
    WriteColor4(message.mutable_color_outer(), object.colorOuter);
    WriteColor4(message.mutable_color_inner(), object.colorInner);
    WriteColor4(message.mutable_color_cap(), object.colorCap);
    return SerializeMessage(message, payload, errorMessage);
}

bool DecodePyramid(const std::vector<uint8_t>& payload, PYRAMID& object) {
    pb::Pyramid message;
    if (!ParseMessage(payload, message)) return false;

    object.vertices.clear();
    object.vertices.reserve(message.vertices_size());
    for (int i = 0; i < message.vertices_size(); ++i) {
        object.vertices.push_back(ReadPoint3(message.vertices(i)));
    }

    object.colors.clear();
    object.colors.reserve(message.colors_size());
    for (int i = 0; i < message.colors_size(); ++i) {
        object.colors.push_back(ReadColor4(message.colors(i)));
    }
    if (object.colors.empty()) object.colors.push_back(DefaultColor4());

    return object.vertices.size() >= 4;
}

bool DecodeCuboid(const std::vector<uint8_t>& payload, CUBOID& object) {
    pb::Cuboid message;
    if (!ParseMessage(payload, message)) return false;

    object.vertices.clear();
    object.vertices.reserve(message.vertices_size());
    for (int i = 0; i < message.vertices_size(); ++i) {
        object.vertices.push_back(ReadPoint3(message.vertices(i)));
    }
    object.colors = message.has_color() ? ReadColor4(message.color()) : DefaultColor4();
    return object.vertices.size() >= 8;
}

bool DecodeCone(const std::vector<uint8_t>& payload, CONE& object) {
    pb::Cone message;
    if (!ParseMessage(payload, message)) return false;

    object.apex = message.has_apex() ? ReadPoint3(message.apex()) : XMFLOAT3{};
    object.baseCenter = message.has_base_center() ? ReadPoint3(message.base_center()) : XMFLOAT3{};
    object.radius = message.radius();
    object.colorBase = message.has_color_base() ? ReadColor4(message.color_base()) : DefaultColor4();
    object.colorIncline = message.has_color_incline() ? ReadColor4(message.color_incline()) : DefaultColor4();
    return true;
}

bool DecodeCylinder(const std::vector<uint8_t>& payload, CYLINDER& object) {
    pb::Cylinder message;
    if (!ParseMessage(payload, message)) return false;

    object.p1 = message.has_p1() ? ReadPoint3(message.p1()) : XMFLOAT3{};
    object.p2 = message.has_p2() ? ReadPoint3(message.p2()) : XMFLOAT3{};
    object.radius = message.radius();
    object.colorBase = message.has_color_base() ? ReadColor4(message.color_base()) : DefaultColor4();
    object.colorTop = message.has_color_top() ? ReadColor4(message.color_top()) : DefaultColor4();
    object.colorIncline = message.has_color_incline() ? ReadColor4(message.color_incline()) : DefaultColor4();
    return true;
}

bool DecodeParallelepiped(const std::vector<uint8_t>& payload, PARALLELEPIPED& object) {
    pb::Parallelepiped message;
    if (!ParseMessage(payload, message)) return false;

    object.vertices.clear();
    object.vertices.reserve(message.vertices_size());
    for (int i = 0; i < message.vertices_size(); ++i) {
        object.vertices.push_back(ReadPoint3(message.vertices(i)));
    }
    object.colors = message.has_color() ? ReadColor4(message.color()) : DefaultColor4();
    return object.vertices.size() >= 8;
}

bool DecodeSphere(const std::vector<uint8_t>& payload, SPHERE& object) {
    pb::Sphere message;
    if (!ParseMessage(payload, message)) return false;

    object.center = message.has_center() ? ReadPoint3(message.center()) : XMFLOAT3{};
    object.radius = message.radius();
    object.color = message.has_color() ? ReadColor4(message.color()) : DefaultColor4();
    return true;
}

bool DecodeFrustumOfPyramid(const std::vector<uint8_t>& payload, FRUSTUM_OF_PYRAMID& object) {
    pb::FrustumOfPyramid message;
    if (!ParseMessage(payload, message)) return false;

    object.vertices.clear();
    object.vertices.reserve(message.vertices_size());
    for (int i = 0; i < message.vertices_size(); ++i) {
        object.vertices.push_back(ReadPoint3(message.vertices(i)));
    }
    object.colorBase = message.has_color_base() ? ReadColor4(message.color_base()) : DefaultColor4();
    object.colorTop = message.has_color_top() ? ReadColor4(message.color_top()) : DefaultColor4();
    object.colorIncline = message.has_color_incline() ? ReadColor4(message.color_incline()) : DefaultColor4();
    return object.vertices.size() >= 8;
}

bool DecodeFrustumOfCone(const std::vector<uint8_t>& payload, FRUSTUM_OF_CONE& object) {
    pb::FrustumOfCone message;
    if (!ParseMessage(payload, message)) return false;

    object.bottomCenter = message.has_bottom_center() ? ReadPoint3(message.bottom_center()) : XMFLOAT3{};
    object.topCenter = message.has_top_center() ? ReadPoint3(message.top_center()) : XMFLOAT3{};
    object.bottomRadius = message.bottom_radius();
    object.topRadius = message.top_radius();
    object.colorBase = message.has_color_base() ? ReadColor4(message.color_base()) : DefaultColor4();
    object.colorTop = message.has_color_top() ? ReadColor4(message.color_top()) : DefaultColor4();
    object.colorIncline = message.has_color_incline() ? ReadColor4(message.color_incline()) : DefaultColor4();
    return true;
}

bool DecodePipe(const std::vector<uint8_t>& payload, PIPE& object) {
    pb::Pipe message;
    if (!ParseMessage(payload, message)) return false;

    object.center1 = message.has_center1() ? ReadPoint3(message.center1()) : XMFLOAT3{};
    object.center2 = message.has_center2() ? ReadPoint3(message.center2()) : XMFLOAT3{};
    object.outsideDiameter = message.outside_diameter();
    object.insideDiameter = message.inside_diameter();
    object.colorOuter = message.has_color_outer() ? ReadColor4(message.color_outer()) : DefaultColor4();
    object.colorInner = message.has_color_inner() ? ReadColor4(message.color_inner()) : DefaultColor4();
    object.colorCap = message.has_color_cap() ? ReadColor4(message.color_cap()) : DefaultColor4();
    return true;
}

std::string ObjectTypeName(ObjectType objectType) {
    switch (objectType) {
    case ObjectType::Pyramid: return "Pyramid";
    case ObjectType::Cuboid: return "Cuboid";
    case ObjectType::Cone: return "Cone";
    case ObjectType::Cylinder: return "Cylinder";
    case ObjectType::Parallelepiped: return "Parallelepiped";
    case ObjectType::Sphere: return "Sphere";
    case ObjectType::FrustumOfPyramid: return "FrustumOfPyramid";
    case ObjectType::FrustumOfCone: return "FrustumOfCone";
    case ObjectType::Pipe: return "Pipe";
    default: return "Unknown";
    }
}

bool ObjectTypeFromNumber(uint32_t value, ObjectType& objectType) {
    switch (value) {
    case 1: objectType = ObjectType::Pyramid; return true;
    case 2: objectType = ObjectType::Cuboid; return true;
    case 3: objectType = ObjectType::Cone; return true;
    case 4: objectType = ObjectType::Cylinder; return true;
    case 5: objectType = ObjectType::Parallelepiped; return true;
    case 6: objectType = ObjectType::Sphere; return true;
    case 7: objectType = ObjectType::FrustumOfPyramid; return true;
    case 8: objectType = ObjectType::FrustumOfCone; return true;
    case 9: objectType = ObjectType::Pipe; return true;
    default: objectType = ObjectType::Unknown; return false;
    }
}

bool SerializeGeometryObject(const StoredGeometryObject3D& entry, std::vector<uint8_t>& payload,
    std::string* errorMessage) {
    if (!entry.object) {
        SetError(errorMessage, "Storage object has a null runtime pointer.");
        return false;
    }

    switch (entry.objectType) {
    case ObjectType::Pyramid:
        return EncodePyramid(*static_cast<const PYRAMID*>(entry.object), payload, errorMessage);
    case ObjectType::Cuboid:
        return EncodeCuboid(*static_cast<const CUBOID*>(entry.object), payload, errorMessage);
    case ObjectType::Cone:
        return EncodeCone(*static_cast<const CONE*>(entry.object), payload, errorMessage);
    case ObjectType::Cylinder:
        return EncodeCylinder(*static_cast<const CYLINDER*>(entry.object), payload, errorMessage);
    case ObjectType::Parallelepiped:
        return EncodeParallelepiped(*static_cast<const PARALLELEPIPED*>(entry.object), payload, errorMessage);
    case ObjectType::Sphere:
        return EncodeSphere(*static_cast<const SPHERE*>(entry.object), payload, errorMessage);
    case ObjectType::FrustumOfPyramid:
        return EncodeFrustumOfPyramid(*static_cast<const FRUSTUM_OF_PYRAMID*>(entry.object), payload, errorMessage);
    case ObjectType::FrustumOfCone:
        return EncodeFrustumOfCone(*static_cast<const FRUSTUM_OF_CONE*>(entry.object), payload, errorMessage);
    case ObjectType::Pipe:
        return EncodePipe(*static_cast<const PIPE*>(entry.object), payload, errorMessage);
    default:
        SetError(errorMessage, "Unsupported object type during save.");
        return false;
    }
}

bool DeserializeGeometryObject(ObjectType objectType, const std::vector<uint8_t>& payload,
    uint32_t memoryGroupNo, META_DATA*& object, std::string* errorMessage) {
    object = nullptr;
    bool ok = false;

    switch (objectType) {
    case ObjectType::Pyramid: {
        PYRAMID* shape = new (memoryGroupNo) PYRAMID();
        ok = DecodePyramid(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Cuboid: {
        CUBOID* shape = new (memoryGroupNo) CUBOID();
        ok = DecodeCuboid(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Cone: {
        CONE* shape = new (memoryGroupNo) CONE();
        ok = DecodeCone(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Cylinder: {
        CYLINDER* shape = new (memoryGroupNo) CYLINDER();
        ok = DecodeCylinder(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Parallelepiped: {
        PARALLELEPIPED* shape = new (memoryGroupNo) PARALLELEPIPED();
        ok = DecodeParallelepiped(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Sphere: {
        SPHERE* shape = new (memoryGroupNo) SPHERE();
        ok = DecodeSphere(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::FrustumOfPyramid: {
        FRUSTUM_OF_PYRAMID* shape = new (memoryGroupNo) FRUSTUM_OF_PYRAMID();
        ok = DecodeFrustumOfPyramid(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::FrustumOfCone: {
        FRUSTUM_OF_CONE* shape = new (memoryGroupNo) FRUSTUM_OF_CONE();
        ok = DecodeFrustumOfCone(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Pipe: {
        PIPE* shape = new (memoryGroupNo) PIPE();
        ok = DecodePipe(payload, *shape);
        object = shape;
        break;
    }
    default:
        SetError(errorMessage, "Unsupported object type during load.");
        return false;
    }

    if (!ok) {
        SetError(errorMessage, "Could not decode " + ObjectTypeName(objectType) + " protobuf payload.");
        return false;
    }
    return true;
}

bool GeometryForObject(ObjectType objectType, META_DATA* object, GeometryData& geometry) {
    if (!object) return false;

    switch (objectType) {
    case ObjectType::Pyramid:
        geometry = static_cast<PYRAMID*>(object)->GetGeometry();
        return true;
    case ObjectType::Cuboid:
        geometry = static_cast<CUBOID*>(object)->GetGeometry();
        return true;
    case ObjectType::Cone:
        geometry = static_cast<CONE*>(object)->GetGeometry();
        return true;
    case ObjectType::Cylinder:
        geometry = static_cast<CYLINDER*>(object)->GetGeometry();
        return true;
    case ObjectType::Parallelepiped:
        geometry = static_cast<PARALLELEPIPED*>(object)->GetGeometry();
        return true;
    case ObjectType::Sphere:
        geometry = static_cast<SPHERE*>(object)->GetGeometry();
        return true;
    case ObjectType::FrustumOfPyramid:
        geometry = static_cast<FRUSTUM_OF_PYRAMID*>(object)->GetGeometry();
        return true;
    case ObjectType::FrustumOfCone:
        geometry = static_cast<FRUSTUM_OF_CONE*>(object)->GetGeometry();
        return true;
    case ObjectType::Pipe:
        geometry = static_cast<PIPE*>(object)->GetGeometry();
        return true;
    default:
        return false;
    }
}

void AppendObjectToTab(DATASETTAB& tab, ObjectType objectType, META_DATA* object) {
    if (!tab.storageObjectsMutex) tab.storageObjectsMutex = std::make_unique<std::mutex>();

    object->dataType = static_cast<uint16_t>(VishwakarmaStorage::ToNumber(objectType));
    object->schemaVersion = VishwakarmaStorage::kGeometry3DMvpSchemaVersion;

    GeometryData geometry;
    if (GeometryForObject(objectType, object, geometry)) {
        std::lock_guard<std::mutex> lock(toCopyThreadMutex);
        commandToCopyThreadQueue.push({ CommandToCopyThreadType::ADD, geometry, object->memoryID, tab.tabID });
    }

    {
        std::lock_guard<std::mutex> lock(*tab.storageObjectsMutex);
        tab.storageObjects3D.push_back({ objectType, object->memoryID, object });
    }

    tab.allIDsInThisTab.push_back(object->memoryID);
    toCopyThreadCV.notify_one();
}

struct ObjectStoreRow {
    uint64_t objectId = 0;
    uint64_t parentId = 0;
    ObjectType objectType = ObjectType::Unknown;
    uint16_t schemaVersion = VishwakarmaStorage::kGeometry3DMvpSchemaVersion;
    LifecycleState lifecycleState = LifecycleState::Live;
    std::vector<uint8_t> payload;
};

LifecycleState LifecycleForObject(const META_DATA& object) {
    return object.isDeleted ? LifecycleState::SoftDeleted : LifecycleState::Live;
}

bool BuildRowsFromTab(DATASETTAB& tab, std::vector<ObjectStoreRow>& rows, uint64_t& nextObjectId,
    std::string* errorMessage) {
    if (!tab.storageObjectsMutex) tab.storageObjectsMutex = std::make_unique<std::mutex>();

    std::lock_guard<std::mutex> lock(*tab.storageObjectsMutex);

    uint64_t maxExistingId = 0;
    for (const StoredGeometryObject3D& entry : tab.storageObjects3D) {
        if (entry.object && entry.object->persistedId > maxExistingId) {
            maxExistingId = entry.object->persistedId;
        }
    }

    uint64_t assignNextId = maxExistingId + 1;
    if (assignNextId == 0) assignNextId = 1;

    for (StoredGeometryObject3D& entry : tab.storageObjects3D) {
        if (!entry.object) continue;

        if (entry.object->persistedId == 0) {
            if (assignNextId > VishwakarmaStorage::kMaxLocalObjectId) {
                SetError(errorMessage, "MVP object_id counter exceeded the 40-bit local object ID range.");
                return false;
            }
            entry.object->persistedId = assignNextId++;
        }

        std::vector<uint8_t> payload;
        if (!SerializeGeometryObject(entry, payload, errorMessage)) return false;

        ObjectStoreRow row;
        row.objectId = entry.object->persistedId;
        row.parentId = entry.object->persistedParentId;
        row.objectType = entry.objectType;
        row.schemaVersion = entry.object->schemaVersion != 0
            ? entry.object->schemaVersion
            : VishwakarmaStorage::kGeometry3DMvpSchemaVersion;
        row.lifecycleState = LifecycleForObject(*entry.object);
        row.payload = std::move(payload);
        rows.push_back(std::move(row));
    }

    nextObjectId = (std::max)(assignNextId, maxExistingId + 1);
    if (nextObjectId == 0) nextObjectId = 1;
    return true;
}

bool InsertObjectRows(sqlite3* db, const std::vector<ObjectStoreRow>& rows, std::string* errorMessage) {
    SQLiteStatement statement;
    if (!Prepare(db,
        "INSERT INTO object_store(object_id, parent_id, object_type, schema_version, lifecycle_state, data) "
        "VALUES(?, ?, ?, ?, ?, ?);",
        statement, errorMessage)) {
        return false;
    }

    for (const ObjectStoreRow& row : rows) {
        sqlite3_reset(statement.stmt);
        sqlite3_clear_bindings(statement.stmt);

        sqlite3_bind_int64(statement.stmt, 1, static_cast<sqlite3_int64>(row.objectId));
        if (row.parentId == 0) {
            sqlite3_bind_null(statement.stmt, 2);
        } else {
            sqlite3_bind_int64(statement.stmt, 2, static_cast<sqlite3_int64>(row.parentId));
        }
        sqlite3_bind_int(statement.stmt, 3, static_cast<int>(VishwakarmaStorage::ToNumber(row.objectType)));
        sqlite3_bind_int(statement.stmt, 4, row.schemaVersion);
        sqlite3_bind_int(statement.stmt, 5, static_cast<int>(VishwakarmaStorage::ToNumber(row.lifecycleState)));
        sqlite3_bind_blob(statement.stmt, 6, row.payload.data(),
            static_cast<int>(row.payload.size()), SQLITE_TRANSIENT);

        int rc = sqlite3_step(statement.stmt);
        if (rc != SQLITE_DONE) {
            SetError(errorMessage, SqliteError(db, "Failed to insert object_store row"));
            return false;
        }
    }

    return true;
}

bool ReadObjectPayload(sqlite3_stmt* statement, int columnIndex, std::vector<uint8_t>& payload) {
    const void* blob = sqlite3_column_blob(statement, columnIndex);
    int blobSize = sqlite3_column_bytes(statement, columnIndex);
    if (blobSize < 0 || (blobSize > 0 && !blob)) return false;
    if (blobSize == 0) {
        payload.clear();
        return true;
    }
    const uint8_t* begin = static_cast<const uint8_t*>(blob);
    payload.assign(begin, begin + blobSize);
    return true;
}

} // namespace

DataStorage& DataStorage::Instance() {
    static DataStorage instance;
    return instance;
}

bool DataStorage::SaveTabToYyy(DATASETTAB& tab, const std::wstring& filePath,
    std::string* errorMessage) {
    SQLiteDatabase database;
    int rc = sqlite3_open16(filePath.c_str(), &database.db);
    if (rc != SQLITE_OK || !database.db) {
        SetError(errorMessage, SqliteError(database.db, "Could not open .yyy file for saving"));
        return false;
    }

    if (!EnsureSchema(database.db, errorMessage)) return false;

    std::vector<ObjectStoreRow> rows;
    uint64_t nextObjectId = 1;
    if (!BuildRowsFromTab(tab, rows, nextObjectId, errorMessage)) return false;

    if (!ExecSql(database.db, "BEGIN IMMEDIATE TRANSACTION;", errorMessage)) return false;
    if (!ExecSql(database.db, "DELETE FROM object_store;", errorMessage)) {
        ExecSql(database.db, "ROLLBACK;", nullptr);
        return false;
    }
    if (!InsertObjectRows(database.db, rows, errorMessage)) {
        ExecSql(database.db, "ROLLBACK;", nullptr);
        return false;
    }
    if (!EnsureFileInfo(database.db, nextObjectId, errorMessage)) {
        ExecSql(database.db, "ROLLBACK;", nullptr);
        return false;
    }
    if (!ExecSql(database.db, "COMMIT;", errorMessage)) {
        ExecSql(database.db, "ROLLBACK;", nullptr);
        return false;
    }

    return true;
}

bool DataStorage::LoadYyyIntoTab(DATASETTAB& tab, const std::wstring& filePath,
    std::string* errorMessage) {
    SQLiteDatabase database;
    int rc = sqlite3_open16(filePath.c_str(), &database.db);
    if (rc != SQLITE_OK || !database.db) {
        SetError(errorMessage, SqliteError(database.db, "Could not open .yyy file for loading"));
        return false;
    }

    SQLiteStatement statement;
    if (!Prepare(database.db,
        "SELECT object_id, parent_id, object_type, schema_version, lifecycle_state, data "
        "FROM object_store WHERE lifecycle_state = 0 ORDER BY object_id;",
        statement, errorMessage)) {
        return false;
    }

    if (!tab.storageObjectsMutex) tab.storageObjectsMutex = std::make_unique<std::mutex>();
    {
        std::lock_guard<std::mutex> lock(*tab.storageObjectsMutex);
        tab.storageObjects3D.clear();
    }
    tab.allIDsInThisTab.clear();

    while ((rc = sqlite3_step(statement.stmt)) == SQLITE_ROW) {
        uint64_t objectId = static_cast<uint64_t>(sqlite3_column_int64(statement.stmt, 0));
        uint64_t parentId = sqlite3_column_type(statement.stmt, 1) == SQLITE_NULL
            ? 0
            : static_cast<uint64_t>(sqlite3_column_int64(statement.stmt, 1));
        uint32_t objectTypeNumber = static_cast<uint32_t>(sqlite3_column_int(statement.stmt, 2));
        uint16_t schemaVersion = static_cast<uint16_t>(sqlite3_column_int(statement.stmt, 3));

        ObjectType objectType = ObjectType::Unknown;
        if (!ObjectTypeFromNumber(objectTypeNumber, objectType)) {
            SetError(errorMessage, "Unsupported object_type in .yyy file: " + std::to_string(objectTypeNumber));
            return false;
        }

        std::vector<uint8_t> payload;
        if (!ReadObjectPayload(statement.stmt, 5, payload)) {
            SetError(errorMessage, "Could not read object payload from SQLite.");
            return false;
        }

        META_DATA* object = nullptr;
        if (!DeserializeGeometryObject(objectType, payload, tab.tabNo, object, errorMessage)) {
            return false;
        }

        object->persistedId = objectId;
        object->persistedParentId = parentId;
        object->schemaVersion = schemaVersion != 0
            ? schemaVersion
            : VishwakarmaStorage::kGeometry3DMvpSchemaVersion;
        object->isDeleted = false;
        AppendObjectToTab(tab, objectType, object);
    }

    if (rc != SQLITE_DONE) {
        SetError(errorMessage, SqliteError(database.db, "Failed while reading object_store"));
        return false;
    }

    return true;
}
