// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.

// 1st version of this file was complete autogenerated by Codex by specifying the MPV part of our storage specification.

#include "DataStorage.h"

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstring>
#include <limits>
#include <mutex>
#include <random>
#include <string>
#include <unordered_map>
#include <vector>

#include "CommonNamedNumbers.h"
#include "DataStorage_ARC2D.pb.h"
#include "DataStorage_CIRCLE2D.pb.h"
#include "DataStorage_CONE.pb.h"
#include "DataStorage_CUBOID.pb.h"
#include "DataStorage_CYLINDER.pb.h"
#include "DataStorage_ELLIPSOID.pb.h"
#include "DataStorage_ELLIPSE2D.pb.h"
#include "DataStorage_FOLDER.pb.h"
#include "DataStorage_FRUSTUM_OF_CONE.pb.h"
#include "DataStorage_FRUSTUM_OF_PYRAMID.pb.h"
#include "DataStorage_LINE2D.pb.h"
#include "DataStorage_PAGE2D.pb.h"
#include "DataStorage_PARALLELEPIPED.pb.h"
#include "DataStorage_PIPE.pb.h"
#include "DataStorage_POLYLINE2D.pb.h"
#include "DataStorage_POLYGON2D.pb.h"
#include "DataStorage_PYRAMID.pb.h"
#include "DataStorage_SCENE3D.pb.h"
#include "DataStorage_SPHERE.pb.h"
#include "DataStorage_TEXT2D.pb.h"
#include "DataStorage_TORUS.pb.h"
#include "ID.h"
#include "MemoryManagerGPU-DirectX12.h"
#include "sqlite3.h"
#include "विश्वकर्मा.h"
#include "डेटा-सामान्य-3D.h"

namespace {

namespace pb = vishwakarma::storage;

using VishwakarmaStorage::LifecycleState;
using VishwakarmaStorage::ObjectType;

constexpr uint32_t kMinPolygonLineSegmentCount = 3;
constexpr uint32_t kMaxPolygonLineSegmentCount = 16;

void SetError(std::string* errorMessage, const std::string& value) {
    if (errorMessage) *errorMessage = value;
}

uint32_t ClampedPolygonLineSegmentCount(uint32_t lineSegmentCount) {
    return std::clamp(lineSegmentCount, kMinPolygonLineSegmentCount, kMaxPolygonLineSegmentCount);
}

std::string SqliteError(sqlite3* db, const char* prefix) {
    std::string result = prefix ? prefix : "SQLite error";
    if (db) {
        result += ": ";
        result += sqlite3_errmsg(db);
    }
    return result;
}

struct SQLiteDatabase {
    sqlite3* db = nullptr;
    ~SQLiteDatabase() {
        if (db) sqlite3_close(db);
    }
};

struct SQLiteStatement {
    sqlite3_stmt* stmt = nullptr;
    ~SQLiteStatement() {
        if (stmt) sqlite3_finalize(stmt);
    }
};

bool ExecSql(sqlite3* db, const char* sql, std::string* errorMessage) {
    char* error = nullptr;
    int rc = sqlite3_exec(db, sql, nullptr, nullptr, &error);
    if (rc != SQLITE_OK) {
        std::string message = error ? error : sqlite3_errmsg(db);
        sqlite3_free(error);
        SetError(errorMessage, message);
        return false;
    }
    return true;
}

bool Prepare(sqlite3* db, const char* sql, SQLiteStatement& statement, std::string* errorMessage) {
    int rc = sqlite3_prepare_v2(db, sql, -1, &statement.stmt, nullptr);
    if (rc != SQLITE_OK) {
        SetError(errorMessage, SqliteError(db, "Failed to prepare statement"));
        return false;
    }
    return true;
}

std::vector<uint8_t> GenerateUuidBytes() {
    std::vector<uint8_t> uuid(16);
    std::random_device randomDevice;
    for (uint8_t& byte : uuid) {
        byte = static_cast<uint8_t>(randomDevice() & 0xFF);
    }
    return uuid;
}

int64_t CurrentUnixTimeSeconds() {
    using namespace std::chrono;
    return duration_cast<seconds>(system_clock::now().time_since_epoch()).count();
}

bool EnsureSchema(sqlite3* db, std::string* errorMessage) {
    const char* schemaSql =
        "PRAGMA foreign_keys = ON;"
        "PRAGMA journal_mode = WAL;"
        "PRAGMA synchronous = NORMAL;"
        "PRAGMA temp_store = MEMORY;"
        "CREATE TABLE IF NOT EXISTS file_info ("
        "  key TEXT PRIMARY KEY,"
        "  value BLOB NOT NULL"
        ");"
        "CREATE TABLE IF NOT EXISTS object_store ("
        "  object_id INTEGER PRIMARY KEY CHECK (object_id > 0 AND object_id < 1099511627776),"
        "  parent_id INTEGER,"
        "  object_type INTEGER NOT NULL,"
        "  schema_version INTEGER NOT NULL DEFAULT 1,"
        "  lifecycle_state INTEGER NOT NULL DEFAULT 0 CHECK (lifecycle_state BETWEEN 0 AND 3),"
        "  data BLOB NOT NULL,"
        "  FOREIGN KEY(parent_id) REFERENCES object_store(object_id)"
        ");"
        "CREATE INDEX IF NOT EXISTS idx_object_parent_live "
        "ON object_store(parent_id, object_id) WHERE lifecycle_state = 0;"
        "CREATE INDEX IF NOT EXISTS idx_object_type_live "
        "ON object_store(object_type, object_id) WHERE lifecycle_state = 0;";

    return ExecSql(db, schemaSql, errorMessage);
}

bool UpsertFileInfoBlob(sqlite3* db, const char* key, const void* value, int valueSize,
    std::string* errorMessage) {
    SQLiteStatement statement;
    if (!Prepare(db, "INSERT OR REPLACE INTO file_info(key, value) VALUES(?, ?);",
        statement, errorMessage)) {
        return false;
    }

    sqlite3_bind_text(statement.stmt, 1, key, -1, SQLITE_TRANSIENT);
    sqlite3_bind_blob(statement.stmt, 2, value, valueSize, SQLITE_TRANSIENT);

    int rc = sqlite3_step(statement.stmt);
    if (rc != SQLITE_DONE) {
        SetError(errorMessage, SqliteError(db, "Failed to write file_info"));
        return false;
    }
    return true;
}

bool UpsertFileInfoText(sqlite3* db, const char* key, const std::string& value,
    std::string* errorMessage) {
    return UpsertFileInfoBlob(db, key, value.data(), static_cast<int>(value.size()), errorMessage);
}

bool FileInfoKeyExists(sqlite3* db, const char* key) {
    SQLiteStatement statement;
    if (sqlite3_prepare_v2(db, "SELECT 1 FROM file_info WHERE key = ? LIMIT 1;",
        -1, &statement.stmt, nullptr) != SQLITE_OK) {
        return false;
    }

    sqlite3_bind_text(statement.stmt, 1, key, -1, SQLITE_TRANSIENT);
    return sqlite3_step(statement.stmt) == SQLITE_ROW;
}

bool EnsureFileInfo(sqlite3* db, uint64_t objectCounterNext, std::string* errorMessage) {
    if (!FileInfoKeyExists(db, "file_uuid")) {
        std::vector<uint8_t> uuid = GenerateUuidBytes();
        if (!UpsertFileInfoBlob(db, "file_uuid", uuid.data(), static_cast<int>(uuid.size()), errorMessage)) {
            return false;
        }
    }

    const std::string now = std::to_string(CurrentUnixTimeSeconds());
    return UpsertFileInfoText(db, "file_format_version", "yyy-mvp-3", errorMessage) &&
        UpsertFileInfoText(db, "file_kind", "yyy", errorMessage) &&
        UpsertFileInfoText(db, "last_saved_by_application", "Vishwakarma", errorMessage) &&
        UpsertFileInfoText(db, "last_saved_time_utc", now, errorMessage) &&
        UpsertFileInfoText(db, "schema_catalog_hash",
            "logical-hierarchy-geometry3d-page2d-line2d-polyline2d-polygon2d-circle2d-ellipse2d-arc2d-text2d-mvp-schema-v1",
            errorMessage) &&
        UpsertFileInfoText(db, "schema_catalog_version", "7", errorMessage) &&
        UpsertFileInfoText(db, "object_counter_next", std::to_string(objectCounterNext), errorMessage);
}

void WritePoint3(pb::Point3F* message, const XMFLOAT3& point) {
    message->set_x(point.x);
    message->set_y(point.y);
    message->set_z(point.z);
}

XMFLOAT3 ReadPoint3(const pb::Point3F& message) {
    return XMFLOAT3(message.x(), message.y(), message.z());
}

void WriteColor4(pb::Color4F* message, const XMHALF4& color) {
    message->set_r(DirectX::PackedVector::XMConvertHalfToFloat(color.x));
    message->set_g(DirectX::PackedVector::XMConvertHalfToFloat(color.y));
    message->set_b(DirectX::PackedVector::XMConvertHalfToFloat(color.z));
    message->set_a(DirectX::PackedVector::XMConvertHalfToFloat(color.w));
}

XMHALF4 ReadColor4(const pb::Color4F& message) {
    return XMHALF4(message.r(), message.g(), message.b(), message.a());
}

XMHALF4 DefaultColor4() {
    return XMHALF4(0.8f, 0.8f, 0.8f, 1.0f);
}

std::string FixedCStringToString(const char* value, size_t capacity) {
    if (!value || capacity == 0) return {};
    const void* terminator = std::memchr(value, '\0', capacity);
    const size_t length = terminator
        ? static_cast<const char*>(terminator) - value
        : capacity;
    return std::string(value, value + length);
}

void CopyStringToFixedCString(const std::string& value, char* target, size_t capacity) {
    if (!target || capacity == 0) return;
    std::memset(target, 0, capacity);
    const size_t copyLength = (std::min)(value.size(), capacity - 1);
    if (copyLength > 0) {
        std::memcpy(target, value.data(), copyLength);
    }
}

template <typename Message>
bool SerializeMessage(const Message& message, std::vector<uint8_t>& payload, std::string* errorMessage) {
    std::string bytes;
    if (!message.SerializeToString(&bytes)) {
        SetError(errorMessage, "Could not serialize protobuf payload.");
        return false;
    }

    payload.assign(bytes.begin(), bytes.end());
    return true;
}

template <typename Message>
bool ParseMessage(const std::vector<uint8_t>& payload, Message& message) {
    if (payload.size() > static_cast<size_t>((std::numeric_limits<int>::max)())) {
        return false;
    }

    const void* data = payload.empty()
        ? static_cast<const void*>("")
        : static_cast<const void*>(payload.data());
    return message.ParseFromArray(data, static_cast<int>(payload.size()));
}

bool EncodePyramid(const PYRAMID& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Pyramid message;
    for (const XMFLOAT3& vertex : object.vertices) {
        WritePoint3(message.add_vertices(), vertex);
    }
    for (const XMHALF4& color : object.colors) {
        WriteColor4(message.add_colors(), color);
    }
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeCuboid(const CUBOID& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Cuboid message;
    for (const XMFLOAT3& vertex : object.vertices) {
        WritePoint3(message.add_vertices(), vertex);
    }
    WriteColor4(message.mutable_color(), object.colors);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeCone(const CONE& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Cone message;
    WritePoint3(message.mutable_apex(), object.apex);
    WritePoint3(message.mutable_base_center(), object.baseCenter);
    message.set_radius(object.radius);
    WriteColor4(message.mutable_color_base(), object.colorBase);
    WriteColor4(message.mutable_color_incline(), object.colorIncline);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeCylinder(const CYLINDER& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Cylinder message;
    WritePoint3(message.mutable_p1(), object.p1);
    WritePoint3(message.mutable_p2(), object.p2);
    message.set_radius(object.radius);
    WriteColor4(message.mutable_color_base(), object.colorBase);
    WriteColor4(message.mutable_color_top(), object.colorTop);
    WriteColor4(message.mutable_color_incline(), object.colorIncline);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeParallelepiped(const PARALLELEPIPED& object, std::vector<uint8_t>& payload,
    std::string* errorMessage) {
    pb::Parallelepiped message;
    for (const XMFLOAT3& vertex : object.vertices) {
        WritePoint3(message.add_vertices(), vertex);
    }
    WriteColor4(message.mutable_color(), object.colors);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeSphere(const SPHERE& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Sphere message;
    WritePoint3(message.mutable_center(), object.center);
    message.set_radius(object.radius);
    WriteColor4(message.mutable_color(), object.color);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeTorus(const TORUS& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Torus message;
    WritePoint3(message.mutable_center(), object.center);
    message.set_major_radius(object.majorRadius);
    message.set_minor_radius(object.minorRadius);
    WriteColor4(message.mutable_color(), object.color);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeEllipsoid(const ELLIPSOID& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Ellipsoid message;
    WritePoint3(message.mutable_center(), object.center);
    message.set_radius_x(object.radiusX);
    message.set_radius_y(object.radiusY);
    message.set_radius_z(object.radiusZ);
    WriteColor4(message.mutable_color(), object.color);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeFrustumOfPyramid(const FRUSTUM_OF_PYRAMID& object, std::vector<uint8_t>& payload,
    std::string* errorMessage) {
    pb::FrustumOfPyramid message;
    for (const XMFLOAT3& vertex : object.vertices) {
        WritePoint3(message.add_vertices(), vertex);
    }
    WriteColor4(message.mutable_color_base(), object.colorBase);
    WriteColor4(message.mutable_color_top(), object.colorTop);
    WriteColor4(message.mutable_color_incline(), object.colorIncline);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeFrustumOfCone(const FRUSTUM_OF_CONE& object, std::vector<uint8_t>& payload,
    std::string* errorMessage) {
    pb::FrustumOfCone message;
    WritePoint3(message.mutable_bottom_center(), object.bottomCenter);
    WritePoint3(message.mutable_top_center(), object.topCenter);
    message.set_bottom_radius(object.bottomRadius);
    message.set_top_radius(object.topRadius);
    WriteColor4(message.mutable_color_base(), object.colorBase);
    WriteColor4(message.mutable_color_top(), object.colorTop);
    WriteColor4(message.mutable_color_incline(), object.colorIncline);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodePipe(const PIPE& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Pipe message;
    WritePoint3(message.mutable_center1(), object.center1);
    WritePoint3(message.mutable_center2(), object.center2);
    message.set_outside_diameter(object.outsideDiameter);
    message.set_inside_diameter(object.insideDiameter);
    WriteColor4(message.mutable_color_outer(), object.colorOuter);
    WriteColor4(message.mutable_color_inner(), object.colorInner);
    WriteColor4(message.mutable_color_cap(), object.colorCap);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeFolder(const FOLDER& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Folder message;
    message.set_name(FixedCStringToString(object.name, sizeof(object.name)));
    message.set_short_code(FixedCStringToString(object.shortCode, sizeof(object.shortCode)));
    message.set_previous_sequence_no(object.previousSequenceNo);
    message.set_next_sequence_no(object.nextSequenceNo);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodePage2D(const PAGE2D& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Page2D message;
    message.set_name(FixedCStringToString(object.name, sizeof(object.name)));
    message.set_width_mm(object.widthMM);
    message.set_height_mm(object.heightMM);
    message.set_previous_sequence_no(object.previousSequenceNo);
    message.set_next_sequence_no(object.nextSequenceNo);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeScene3D(const SCENE3D& object, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Scene3D message;
    message.set_name(FixedCStringToString(object.name, sizeof(object.name)));
    message.set_previous_sequence_no(object.previousSequenceNo);
    message.set_next_sequence_no(object.nextSequenceNo);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeLine2D(const Cad2DLineRecordCPU& line, std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Line2D message;
    message.set_x1(line.x1);
    message.set_y1(line.y1);
    message.set_x2(line.x2);
    message.set_y2(line.y2);
    message.set_line_weight(line.lineWeight);
    message.set_line_weight_mode(static_cast<uint32_t>(line.lineWeightMode));
    message.set_color_abgr(line.colorABGR);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodePolyline2D(const Cad2DPolylineRecordCPU& polyline,
    std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Polyline2D message;
    for (const Cad2DPoint2D& point : polyline.points) {
        pb::Polyline2DPoint* pointMessage = message.add_points();
        pointMessage->set_x(point.x);
        pointMessage->set_y(point.y);
    }
    message.set_line_weight(polyline.lineWeight);
    message.set_line_weight_mode(static_cast<uint32_t>(polyline.lineWeightMode));
    message.set_color_abgr(polyline.colorABGR);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodePolygon2D(const Cad2DPolygonRecordCPU& polygon,
    std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Polygon2D message;
    message.set_line_segment_count(ClampedPolygonLineSegmentCount(polygon.lineSegmentCount));
    message.set_center_x(polygon.centerX);
    message.set_center_y(polygon.centerY);
    message.set_radius(polygon.radius);
    message.set_rotation_degrees(polygon.rotationDegrees);
    message.set_line_weight(polygon.lineWeight);
    message.set_line_weight_mode(static_cast<uint32_t>(polygon.lineWeightMode));
    message.set_color_abgr(polygon.colorABGR);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeCircle2D(const Cad2DCircleRecordCPU& circle,
    std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Circle2D message;
    message.set_center_x(circle.centerX);
    message.set_center_y(circle.centerY);
    message.set_radius(circle.radius);
    message.set_line_weight(circle.lineWeight);
    message.set_line_weight_mode(static_cast<uint32_t>(circle.lineWeightMode));
    message.set_color_abgr(circle.colorABGR);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeEllipse2D(const Cad2DEllipseRecordCPU& ellipse,
    std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Ellipse2D message;
    message.set_center_x(ellipse.centerX);
    message.set_center_y(ellipse.centerY);
    message.set_radius_x(ellipse.radiusX);
    message.set_radius_y(ellipse.radiusY);
    message.set_rotation_radians(ellipse.rotationRadians);
    message.set_line_weight(ellipse.lineWeight);
    message.set_line_weight_mode(static_cast<uint32_t>(ellipse.lineWeightMode));
    message.set_color_abgr(ellipse.colorABGR);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeArc2D(const Cad2DArcRecordCPU& arc,
    std::vector<uint8_t>& payload, std::string* errorMessage) {
    pb::Arc2D message;
    message.set_center_x(arc.centerX);
    message.set_center_y(arc.centerY);
    message.set_radius_x(arc.radiusX);
    message.set_radius_y(arc.radiusY);
    message.set_rotation_radians(arc.rotationRadians);
    message.set_start_x(arc.startX);
    message.set_start_y(arc.startY);
    message.set_end_x(arc.endX);
    message.set_end_y(arc.endY);
    message.set_line_weight(arc.lineWeight);
    message.set_line_weight_mode(static_cast<uint32_t>(arc.lineWeightMode));
    message.set_color_abgr(arc.colorABGR);
    return SerializeMessage(message, payload, errorMessage);
}

bool EncodeText2D(const Cad2DTextRecordCPU& text, std::vector<uint8_t>& payload,
    std::string* errorMessage) {
    pb::Text2D message;
    message.set_x(text.x);
    message.set_y(text.y);
    message.set_text_height_cu(text.textHeightCU);
    message.set_rotation_radians(text.rotationRadians);
    message.set_color_abgr(text.colorABGR);
    message.set_font(text.font);
    message.set_justification(static_cast<uint32_t>(text.justification));
    message.set_x_offset_cu(text.xOffsetCU);
    message.set_y_offset_cu(text.yOffsetCU);
    message.set_text(text.text);
    return SerializeMessage(message, payload, errorMessage);
}

bool DecodePyramid(const std::vector<uint8_t>& payload, PYRAMID& object) {
    pb::Pyramid message;
    if (!ParseMessage(payload, message)) return false;

    object.vertices.clear();
    object.vertices.reserve(message.vertices_size());
    for (int i = 0; i < message.vertices_size(); ++i) {
        object.vertices.push_back(ReadPoint3(message.vertices(i)));
    }

    object.colors.clear();
    object.colors.reserve(message.colors_size());
    for (int i = 0; i < message.colors_size(); ++i) {
        object.colors.push_back(ReadColor4(message.colors(i)));
    }
    if (object.colors.empty()) object.colors.push_back(DefaultColor4());

    return object.vertices.size() >= 4;
}

bool DecodeCuboid(const std::vector<uint8_t>& payload, CUBOID& object) {
    pb::Cuboid message;
    if (!ParseMessage(payload, message)) return false;

    object.vertices.clear();
    object.vertices.reserve(message.vertices_size());
    for (int i = 0; i < message.vertices_size(); ++i) {
        object.vertices.push_back(ReadPoint3(message.vertices(i)));
    }
    object.colors = message.has_color() ? ReadColor4(message.color()) : DefaultColor4();
    return object.vertices.size() >= 8;
}

bool DecodeCone(const std::vector<uint8_t>& payload, CONE& object) {
    pb::Cone message;
    if (!ParseMessage(payload, message)) return false;

    object.apex = message.has_apex() ? ReadPoint3(message.apex()) : XMFLOAT3{};
    object.baseCenter = message.has_base_center() ? ReadPoint3(message.base_center()) : XMFLOAT3{};
    object.radius = message.radius();
    object.colorBase = message.has_color_base() ? ReadColor4(message.color_base()) : DefaultColor4();
    object.colorIncline = message.has_color_incline() ? ReadColor4(message.color_incline()) : DefaultColor4();
    return true;
}

bool DecodeCylinder(const std::vector<uint8_t>& payload, CYLINDER& object) {
    pb::Cylinder message;
    if (!ParseMessage(payload, message)) return false;

    object.p1 = message.has_p1() ? ReadPoint3(message.p1()) : XMFLOAT3{};
    object.p2 = message.has_p2() ? ReadPoint3(message.p2()) : XMFLOAT3{};
    object.radius = message.radius();
    object.colorBase = message.has_color_base() ? ReadColor4(message.color_base()) : DefaultColor4();
    object.colorTop = message.has_color_top() ? ReadColor4(message.color_top()) : DefaultColor4();
    object.colorIncline = message.has_color_incline() ? ReadColor4(message.color_incline()) : DefaultColor4();
    return true;
}

bool DecodeParallelepiped(const std::vector<uint8_t>& payload, PARALLELEPIPED& object) {
    pb::Parallelepiped message;
    if (!ParseMessage(payload, message)) return false;

    object.vertices.clear();
    object.vertices.reserve(message.vertices_size());
    for (int i = 0; i < message.vertices_size(); ++i) {
        object.vertices.push_back(ReadPoint3(message.vertices(i)));
    }
    object.colors = message.has_color() ? ReadColor4(message.color()) : DefaultColor4();
    return object.vertices.size() >= 8;
}

bool DecodeSphere(const std::vector<uint8_t>& payload, SPHERE& object) {
    pb::Sphere message;
    if (!ParseMessage(payload, message)) return false;

    object.center = message.has_center() ? ReadPoint3(message.center()) : XMFLOAT3{};
    object.radius = message.radius();
    object.color = message.has_color() ? ReadColor4(message.color()) : DefaultColor4();
    return true;
}

bool DecodeTorus(const std::vector<uint8_t>& payload, TORUS& object) {
    pb::Torus message;
    if (!ParseMessage(payload, message)) return false;

    object.center = message.has_center() ? ReadPoint3(message.center()) : XMFLOAT3{};
    object.majorRadius = message.major_radius() > 0.0f ? message.major_radius() : 0.5f;
    object.minorRadius = message.minor_radius() > 0.0f ? message.minor_radius() : 0.125f;
    object.color = message.has_color() ? ReadColor4(message.color()) : DefaultColor4();
    return true;
}

bool DecodeEllipsoid(const std::vector<uint8_t>& payload, ELLIPSOID& object) {
    pb::Ellipsoid message;
    if (!ParseMessage(payload, message)) return false;

    object.center = message.has_center() ? ReadPoint3(message.center()) : XMFLOAT3{};
    object.radiusX = message.radius_x() > 0.0f ? message.radius_x() : 0.5f;
    object.radiusY = message.radius_y() > 0.0f ? message.radius_y() : 0.5f;
    object.radiusZ = message.radius_z() > 0.0f ? message.radius_z() : 0.5f;
    object.color = message.has_color() ? ReadColor4(message.color()) : DefaultColor4();
    return true;
}

bool DecodeFrustumOfPyramid(const std::vector<uint8_t>& payload, FRUSTUM_OF_PYRAMID& object) {
    pb::FrustumOfPyramid message;
    if (!ParseMessage(payload, message)) return false;

    object.vertices.clear();
    object.vertices.reserve(message.vertices_size());
    for (int i = 0; i < message.vertices_size(); ++i) {
        object.vertices.push_back(ReadPoint3(message.vertices(i)));
    }
    object.colorBase = message.has_color_base() ? ReadColor4(message.color_base()) : DefaultColor4();
    object.colorTop = message.has_color_top() ? ReadColor4(message.color_top()) : DefaultColor4();
    object.colorIncline = message.has_color_incline() ? ReadColor4(message.color_incline()) : DefaultColor4();
    return object.vertices.size() >= 8;
}

bool DecodeFrustumOfCone(const std::vector<uint8_t>& payload, FRUSTUM_OF_CONE& object) {
    pb::FrustumOfCone message;
    if (!ParseMessage(payload, message)) return false;

    object.bottomCenter = message.has_bottom_center() ? ReadPoint3(message.bottom_center()) : XMFLOAT3{};
    object.topCenter = message.has_top_center() ? ReadPoint3(message.top_center()) : XMFLOAT3{};
    object.bottomRadius = message.bottom_radius();
    object.topRadius = message.top_radius();
    object.colorBase = message.has_color_base() ? ReadColor4(message.color_base()) : DefaultColor4();
    object.colorTop = message.has_color_top() ? ReadColor4(message.color_top()) : DefaultColor4();
    object.colorIncline = message.has_color_incline() ? ReadColor4(message.color_incline()) : DefaultColor4();
    return true;
}

bool DecodePipe(const std::vector<uint8_t>& payload, PIPE& object) {
    pb::Pipe message;
    if (!ParseMessage(payload, message)) return false;

    object.center1 = message.has_center1() ? ReadPoint3(message.center1()) : XMFLOAT3{};
    object.center2 = message.has_center2() ? ReadPoint3(message.center2()) : XMFLOAT3{};
    object.outsideDiameter = message.outside_diameter();
    object.insideDiameter = message.inside_diameter();
    object.colorOuter = message.has_color_outer() ? ReadColor4(message.color_outer()) : DefaultColor4();
    object.colorInner = message.has_color_inner() ? ReadColor4(message.color_inner()) : DefaultColor4();
    object.colorCap = message.has_color_cap() ? ReadColor4(message.color_cap()) : DefaultColor4();
    return true;
}

bool DecodeFolder(const std::vector<uint8_t>& payload, FOLDER& object) {
    pb::Folder message;
    if (!ParseMessage(payload, message)) return false;

    CopyStringToFixedCString(message.name(), object.name, sizeof(object.name));
    CopyStringToFixedCString(message.short_code(), object.shortCode, sizeof(object.shortCode));
    object.previousSequenceNo = message.previous_sequence_no();
    object.nextSequenceNo = message.next_sequence_no();
    return true;
}

bool DecodePage2D(const std::vector<uint8_t>& payload, PAGE2D& object) {
    pb::Page2D message;
    if (!ParseMessage(payload, message)) return false;

    CopyStringToFixedCString(message.name(), object.name, sizeof(object.name));
    object.widthMM = message.width_mm() > 0.0f ? message.width_mm() : 841.0f;
    object.heightMM = message.height_mm() > 0.0f ? message.height_mm() : 594.0f;
    object.previousSequenceNo = message.previous_sequence_no();
    object.nextSequenceNo = message.next_sequence_no();
    return true;
}

bool DecodeScene3D(const std::vector<uint8_t>& payload, SCENE3D& object) {
    pb::Scene3D message;
    if (!ParseMessage(payload, message)) return false;

    CopyStringToFixedCString(message.name(), object.name, sizeof(object.name));
    object.previousSequenceNo = message.previous_sequence_no();
    object.nextSequenceNo = message.next_sequence_no();
    return true;
}

Cad2DLineWeightMode ReadLineWeightMode(uint32_t value) {
    switch (value) {
    case static_cast<uint32_t>(Cad2DLineWeightMode::ModelComputerUnit):
        return Cad2DLineWeightMode::ModelComputerUnit;
    case static_cast<uint32_t>(Cad2DLineWeightMode::ScreenPixel):
        return Cad2DLineWeightMode::ScreenPixel;
    case static_cast<uint32_t>(Cad2DLineWeightMode::PaperMM):
        return Cad2DLineWeightMode::PaperMM;
    default:
        return Cad2DLineWeightMode::PaperMM;
    }
}

Cad2DTextJustification ReadTextJustification(uint32_t value) {
    switch (value) {
    case static_cast<uint32_t>(Cad2DTextJustification::TopLeft):
        return Cad2DTextJustification::TopLeft;
    case static_cast<uint32_t>(Cad2DTextJustification::TopMiddle):
        return Cad2DTextJustification::TopMiddle;
    case static_cast<uint32_t>(Cad2DTextJustification::TopRight):
        return Cad2DTextJustification::TopRight;
    case static_cast<uint32_t>(Cad2DTextJustification::MiddleLeft):
        return Cad2DTextJustification::MiddleLeft;
    case static_cast<uint32_t>(Cad2DTextJustification::Center):
        return Cad2DTextJustification::Center;
    case static_cast<uint32_t>(Cad2DTextJustification::MiddleRight):
        return Cad2DTextJustification::MiddleRight;
    case static_cast<uint32_t>(Cad2DTextJustification::BottomLeft):
        return Cad2DTextJustification::BottomLeft;
    case static_cast<uint32_t>(Cad2DTextJustification::BottomCenter):
        return Cad2DTextJustification::BottomCenter;
    case static_cast<uint32_t>(Cad2DTextJustification::BottomRight):
        return Cad2DTextJustification::BottomRight;
    default:
        return Cad2DTextJustification::Center;
    }
}

bool DecodeLine2D(const std::vector<uint8_t>& payload, Cad2DLineRecordCPU& line) {
    pb::Line2D message;
    if (!ParseMessage(payload, message)) return false;

    line.x1 = message.x1();
    line.y1 = message.y1();
    line.x2 = message.x2();
    line.y2 = message.y2();
    line.lineWeight = message.line_weight() > 0.0f ? message.line_weight() : 0.25f;
    line.lineWeightMode = ReadLineWeightMode(message.line_weight_mode());
    line.colorABGR = message.color_abgr();
    return true;
}

bool DecodePolyline2D(const std::vector<uint8_t>& payload, Cad2DPolylineRecordCPU& polyline) {
    pb::Polyline2D message;
    if (!ParseMessage(payload, message)) return false;

    polyline.points.clear();
    polyline.points.reserve(message.points_size());
    for (int i = 0; i < message.points_size(); ++i) {
        const pb::Polyline2DPoint& pointMessage = message.points(i);
        polyline.points.push_back({ pointMessage.x(), pointMessage.y() });
    }
    polyline.lineWeight = message.line_weight() > 0.0f ? message.line_weight() : 0.25f;
    polyline.lineWeightMode = ReadLineWeightMode(message.line_weight_mode());
    polyline.colorABGR = message.color_abgr();
    return polyline.points.size() >= 2;
}

bool DecodePolygon2D(const std::vector<uint8_t>& payload, Cad2DPolygonRecordCPU& polygon) {
    pb::Polygon2D message;
    if (!ParseMessage(payload, message)) return false;

    polygon.lineSegmentCount = ClampedPolygonLineSegmentCount(message.line_segment_count());
    polygon.centerX = message.center_x();
    polygon.centerY = message.center_y();
    polygon.radius = message.radius();
    polygon.rotationDegrees = message.rotation_degrees();
    polygon.lineWeight = message.line_weight() > 0.0f ? message.line_weight() : 0.25f;
    polygon.lineWeightMode = ReadLineWeightMode(message.line_weight_mode());
    polygon.colorABGR = message.color_abgr();
    return polygon.radius > 0.0;
}

bool DecodeCircle2D(const std::vector<uint8_t>& payload, Cad2DCircleRecordCPU& circle) {
    pb::Circle2D message;
    if (!ParseMessage(payload, message)) return false;

    circle.centerX = message.center_x();
    circle.centerY = message.center_y();
    circle.radius = message.radius();
    circle.lineWeight = message.line_weight() > 0.0f ? message.line_weight() : 0.25f;
    circle.lineWeightMode = ReadLineWeightMode(message.line_weight_mode());
    circle.colorABGR = message.color_abgr();
    return circle.radius > 0.0;
}

bool DecodeEllipse2D(const std::vector<uint8_t>& payload, Cad2DEllipseRecordCPU& ellipse) {
    pb::Ellipse2D message;
    if (!ParseMessage(payload, message)) return false;

    ellipse.centerX = message.center_x();
    ellipse.centerY = message.center_y();
    ellipse.radiusX = message.radius_x();
    ellipse.radiusY = message.radius_y();
    ellipse.rotationRadians = message.rotation_radians(); // 0.0 for schema v1 files.
    ellipse.lineWeight = message.line_weight() > 0.0f ? message.line_weight() : 0.25f;
    ellipse.lineWeightMode = ReadLineWeightMode(message.line_weight_mode());
    ellipse.colorABGR = message.color_abgr();
    return ellipse.radiusX > 0.0 && ellipse.radiusY > 0.0;
}

bool DecodeArc2D(const std::vector<uint8_t>& payload, Cad2DArcRecordCPU& arc) {
    pb::Arc2D message;
    if (!ParseMessage(payload, message)) return false;

    arc.centerX = message.center_x();
    arc.centerY = message.center_y();
    arc.radiusX = message.radius_x();
    arc.radiusY = message.radius_y();
    arc.rotationRadians = message.rotation_radians(); // 0.0 for schema v1 files.
    arc.startX = message.start_x();
    arc.startY = message.start_y();
    arc.endX = message.end_x();
    arc.endY = message.end_y();
    arc.lineWeight = message.line_weight() > 0.0f ? message.line_weight() : 0.25f;
    arc.lineWeightMode = ReadLineWeightMode(message.line_weight_mode());
    arc.colorABGR = message.color_abgr();
    return arc.radiusX > 0.0 && arc.radiusY > 0.0;
}

bool DecodeText2D(const std::vector<uint8_t>& payload, Cad2DTextRecordCPU& text) {
    pb::Text2D message;
    if (!ParseMessage(payload, message)) return false;

    text.x = message.x();
    text.y = message.y();
    text.textHeightCU = message.text_height_cu() > 0.0f ? message.text_height_cu() : 3.5f;
    text.rotationRadians = message.rotation_radians();
    text.colorABGR = message.color_abgr();
    text.font = message.font();
    text.justification = ReadTextJustification(message.justification());
    text.xOffsetCU = message.x_offset_cu();
    text.yOffsetCU = message.y_offset_cu();
    text.text = message.text();
    return !text.text.empty();
}

std::string ObjectTypeName(ObjectType objectType) {
    switch (objectType) {
    case ObjectType::Pyramid: return "Pyramid";
    case ObjectType::Cuboid: return "Cuboid";
    case ObjectType::Cone: return "Cone";
    case ObjectType::Cylinder: return "Cylinder";
    case ObjectType::Parallelepiped: return "Parallelepiped";
    case ObjectType::Sphere: return "Sphere";
    case ObjectType::FrustumOfPyramid: return "FrustumOfPyramid";
    case ObjectType::FrustumOfCone: return "FrustumOfCone";
    case ObjectType::Pipe: return "Pipe";
    case ObjectType::Torus: return "Torus";
    case ObjectType::Ellipsoid: return "Ellipsoid";
    case ObjectType::Folder: return "Folder";
    case ObjectType::Page2D: return "Page2D";
    case ObjectType::Scene3D: return "Scene3D";
    case ObjectType::Line2D: return "Line2D";
    case ObjectType::Polyline2D: return "Polyline2D";
    case ObjectType::Polygon2D: return "Polygon2D";
    case ObjectType::Text2D: return "Text2D";
    case ObjectType::Circle2D: return "Circle2D";
    case ObjectType::Ellipse2D: return "Ellipse2D";
    case ObjectType::Arc2D: return "Arc2D";
    default: return "Unknown";
    }
}

bool ObjectTypeFromNumber(uint32_t value, ObjectType& objectType) {
    switch (value) {
    case 1: objectType = ObjectType::Pyramid; return true;
    case 2: objectType = ObjectType::Cuboid; return true;
    case 3: objectType = ObjectType::Cone; return true;
    case 4: objectType = ObjectType::Cylinder; return true;
    case 5: objectType = ObjectType::Parallelepiped; return true;
    case 6: objectType = ObjectType::Sphere; return true;
    case 7: objectType = ObjectType::FrustumOfPyramid; return true;
    case 8: objectType = ObjectType::FrustumOfCone; return true;
    case 9: objectType = ObjectType::Pipe; return true;
    case 10: objectType = ObjectType::Folder; return true;
    case 11: objectType = ObjectType::Page2D; return true;
    case 12: objectType = ObjectType::Scene3D; return true;
    case 13: objectType = ObjectType::Line2D; return true;
    case 14: objectType = ObjectType::Polyline2D; return true;
    case 15: objectType = ObjectType::Polygon2D; return true;
    case 16: objectType = ObjectType::Text2D; return true;
    case 17: objectType = ObjectType::Circle2D; return true;
    case 18: objectType = ObjectType::Ellipse2D; return true;
    case 19: objectType = ObjectType::Arc2D; return true;
    case 20: objectType = ObjectType::Torus; return true;
    case 21: objectType = ObjectType::Ellipsoid; return true;
    default: objectType = ObjectType::Unknown; return false;
    }
}

uint16_t DefaultSchemaVersionForObjectType(ObjectType objectType) {
    if (VishwakarmaStorage::IsLogicalObjectType(objectType)) {
        return VishwakarmaStorage::kLogicalElementSchemaVersion;
    }
    if (VishwakarmaStorage::IsGeometry2DObjectType(objectType)) {
        switch (objectType) {
        case ObjectType::Polyline2D:
            return VishwakarmaStorage::kGeometry2DPolylineSchemaVersion;
        case ObjectType::Polygon2D:
            return VishwakarmaStorage::kGeometry2DPolygonSchemaVersion;
        case ObjectType::Text2D:
            return VishwakarmaStorage::kGeometry2DTextSchemaVersion;
        case ObjectType::Circle2D:
            return VishwakarmaStorage::kGeometry2DCircleSchemaVersion;
        case ObjectType::Ellipse2D:
            return VishwakarmaStorage::kGeometry2DEllipseSchemaVersion;
        case ObjectType::Arc2D:
            return VishwakarmaStorage::kGeometry2DArcSchemaVersion;
        default:
            return VishwakarmaStorage::kGeometry2DLineSchemaVersion;
        }
    }
    return VishwakarmaStorage::kGeometry3DMvpSchemaVersion;
}

bool SerializeGeometryObject(const StoredGeometryObject3D& entry, std::vector<uint8_t>& payload,
    std::string* errorMessage) {
    if (!entry.object) {
        SetError(errorMessage, "Storage object has a null runtime pointer.");
        return false;
    }

    switch (entry.objectType) {
    case ObjectType::Pyramid:
        return EncodePyramid(*static_cast<const PYRAMID*>(entry.object), payload, errorMessage);
    case ObjectType::Cuboid:
        return EncodeCuboid(*static_cast<const CUBOID*>(entry.object), payload, errorMessage);
    case ObjectType::Cone:
        return EncodeCone(*static_cast<const CONE*>(entry.object), payload, errorMessage);
    case ObjectType::Cylinder:
        return EncodeCylinder(*static_cast<const CYLINDER*>(entry.object), payload, errorMessage);
    case ObjectType::Parallelepiped:
        return EncodeParallelepiped(*static_cast<const PARALLELEPIPED*>(entry.object), payload, errorMessage);
    case ObjectType::Sphere:
        return EncodeSphere(*static_cast<const SPHERE*>(entry.object), payload, errorMessage);
    case ObjectType::FrustumOfPyramid:
        return EncodeFrustumOfPyramid(*static_cast<const FRUSTUM_OF_PYRAMID*>(entry.object), payload, errorMessage);
    case ObjectType::FrustumOfCone:
        return EncodeFrustumOfCone(*static_cast<const FRUSTUM_OF_CONE*>(entry.object), payload, errorMessage);
    case ObjectType::Pipe:
        return EncodePipe(*static_cast<const PIPE*>(entry.object), payload, errorMessage);
    case ObjectType::Torus:
        return EncodeTorus(*static_cast<const TORUS*>(entry.object), payload, errorMessage);
    case ObjectType::Ellipsoid:
        return EncodeEllipsoid(*static_cast<const ELLIPSOID*>(entry.object), payload, errorMessage);
    default:
        SetError(errorMessage, "Unsupported object type during save.");
        return false;
    }
}

bool SerializeLogicalObject(const StoredLogicalObject& entry, std::vector<uint8_t>& payload,
    std::string* errorMessage) {
    if (!entry.object) {
        SetError(errorMessage, "Logical storage object has a null runtime pointer.");
        return false;
    }

    switch (entry.objectType) {
    case ObjectType::Folder:
        return EncodeFolder(*static_cast<const FOLDER*>(entry.object), payload, errorMessage);
    case ObjectType::Page2D:
        return EncodePage2D(*static_cast<const PAGE2D*>(entry.object), payload, errorMessage);
    case ObjectType::Scene3D:
        return EncodeScene3D(*static_cast<const SCENE3D*>(entry.object), payload, errorMessage);
    default:
        SetError(errorMessage, "Unsupported logical object type during save.");
        return false;
    }
}

bool DeserializeLogicalObject(ObjectType objectType, const std::vector<uint8_t>& payload,
    uint32_t memoryGroupNo, META_DATA*& object, std::string* errorMessage) {
    object = nullptr;
    bool ok = false;

    switch (objectType) {
    case ObjectType::Folder: {
        FOLDER* folder = new (memoryGroupNo) FOLDER();
        ok = DecodeFolder(payload, *folder);
        object = folder;
        break;
    }
    case ObjectType::Page2D: {
        PAGE2D* page = new (memoryGroupNo) PAGE2D();
        ok = DecodePage2D(payload, *page);
        object = page;
        break;
    }
    case ObjectType::Scene3D: {
        SCENE3D* scene = new (memoryGroupNo) SCENE3D();
        ok = DecodeScene3D(payload, *scene);
        object = scene;
        break;
    }
    default:
        SetError(errorMessage, "Unsupported logical object type during load.");
        return false;
    }

    if (!ok) {
        SetError(errorMessage, "Could not decode " + ObjectTypeName(objectType) + " protobuf payload.");
        return false;
    }
    return true;
}

bool DeserializeGeometryObject(ObjectType objectType, const std::vector<uint8_t>& payload,
    uint32_t memoryGroupNo, META_DATA*& object, std::string* errorMessage) {
    object = nullptr;
    bool ok = false;

    switch (objectType) {
    case ObjectType::Pyramid: {
        PYRAMID* shape = new (memoryGroupNo) PYRAMID();
        ok = DecodePyramid(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Cuboid: {
        CUBOID* shape = new (memoryGroupNo) CUBOID();
        ok = DecodeCuboid(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Cone: {
        CONE* shape = new (memoryGroupNo) CONE();
        ok = DecodeCone(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Cylinder: {
        CYLINDER* shape = new (memoryGroupNo) CYLINDER();
        ok = DecodeCylinder(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Parallelepiped: {
        PARALLELEPIPED* shape = new (memoryGroupNo) PARALLELEPIPED();
        ok = DecodeParallelepiped(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Sphere: {
        SPHERE* shape = new (memoryGroupNo) SPHERE();
        ok = DecodeSphere(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::FrustumOfPyramid: {
        FRUSTUM_OF_PYRAMID* shape = new (memoryGroupNo) FRUSTUM_OF_PYRAMID();
        ok = DecodeFrustumOfPyramid(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::FrustumOfCone: {
        FRUSTUM_OF_CONE* shape = new (memoryGroupNo) FRUSTUM_OF_CONE();
        ok = DecodeFrustumOfCone(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Pipe: {
        PIPE* shape = new (memoryGroupNo) PIPE();
        ok = DecodePipe(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Torus: {
        TORUS* shape = new (memoryGroupNo) TORUS();
        ok = DecodeTorus(payload, *shape);
        object = shape;
        break;
    }
    case ObjectType::Ellipsoid: {
        ELLIPSOID* shape = new (memoryGroupNo) ELLIPSOID();
        ok = DecodeEllipsoid(payload, *shape);
        object = shape;
        break;
    }
    default:
        SetError(errorMessage, "Unsupported object type during load.");
        return false;
    }

    if (!ok) {
        SetError(errorMessage, "Could not decode " + ObjectTypeName(objectType) + " protobuf payload.");
        return false;
    }
    return true;
}

} // anonymous namespace — GeometryForObject is lifted to external linkage so the engineering thread
  // can reuse it for property-edit MODIFY (propertiesPane.md §5); declared in डेटा-सामान्य-3D.h.

bool GeometryForObject(VishwakarmaStorage::ObjectType objectType, META_DATA* object, GeometryData& geometry) {
    using VishwakarmaStorage::ObjectType;
    if (!object) return false;

    switch (objectType) {
    case ObjectType::Pyramid:
        geometry = static_cast<PYRAMID*>(object)->GetGeometry();
        return true;
    case ObjectType::Cuboid:
        geometry = static_cast<CUBOID*>(object)->GetGeometry();
        return true;
    case ObjectType::Cone:
        geometry = static_cast<CONE*>(object)->GetGeometry();
        return true;
    case ObjectType::Cylinder:
        geometry = static_cast<CYLINDER*>(object)->GetGeometry();
        return true;
    case ObjectType::Parallelepiped:
        geometry = static_cast<PARALLELEPIPED*>(object)->GetGeometry();
        return true;
    case ObjectType::Sphere:
        geometry = static_cast<SPHERE*>(object)->GetGeometry();
        return true;
    case ObjectType::FrustumOfPyramid:
        geometry = static_cast<FRUSTUM_OF_PYRAMID*>(object)->GetGeometry();
        return true;
    case ObjectType::FrustumOfCone:
        geometry = static_cast<FRUSTUM_OF_CONE*>(object)->GetGeometry();
        return true;
    case ObjectType::Pipe:
        geometry = static_cast<PIPE*>(object)->GetGeometry();
        return true;
    case ObjectType::Torus:
        geometry = static_cast<TORUS*>(object)->GetGeometry();
        return true;
    case ObjectType::Ellipsoid:
        geometry = static_cast<ELLIPSOID*>(object)->GetGeometry();
        return true;
    default:
        return false;
    }
}

namespace { // Reopen the anonymous namespace for the remaining internal helpers.

void AppendObjectToTab(DATASETTAB& tab, ObjectType objectType, META_DATA* object) {
    if (!tab.storageObjectsMutex) tab.storageObjectsMutex = std::make_unique<std::mutex>();

    object->dataType = static_cast<uint16_t>(VishwakarmaStorage::ToNumber(objectType));
    object->schemaVersion = VishwakarmaStorage::kGeometry3DMvpSchemaVersion;

    GeometryData geometry;
    if (GeometryForObject(objectType, object, geometry)) {
        std::lock_guard<std::mutex> lock(toCopyThreadMutex);
        commandToCopyThreadQueue.push({ CommandToCopyThreadType::ADD, geometry, object->memoryID,
            tab.tabID, object->memoryIDParent });
    }

    {
        std::lock_guard<std::mutex> lock(*tab.storageObjectsMutex);
        tab.storageObjects3D.push_back({ objectType, object->memoryID, object });
    }

    tab.allIDsInThisTab.push_back(object->memoryID);
    toCopyThreadCV.notify_one();
}

void AppendLogicalObjectToTab(DATASETTAB& tab, ObjectType objectType, META_DATA* object) {
    if (!tab.storageObjectsMutex) tab.storageObjectsMutex = std::make_unique<std::mutex>();

    object->dataType = static_cast<uint16_t>(VishwakarmaStorage::ToNumber(objectType));
    object->schemaVersion = VishwakarmaStorage::kLogicalElementSchemaVersion;

    {
        std::lock_guard<std::mutex> lock(*tab.storageObjectsMutex);
        tab.storageLogicalObjects.push_back({ objectType, object->memoryID, object });
        if (objectType == ObjectType::Scene3D) {
            if (tab.defaultScene3DMemoryId == 0) {
                tab.defaultScene3DMemoryId = object->memoryID;
                tab.expandedDataTreeNodeIds.push_back(object->memoryID);
            }
            if (tab.activeScene3DMemoryId == 0) {
                tab.activeScene3DMemoryId = object->memoryID;
            }
        }
    }

    tab.allIDsInThisTab.push_back(object->memoryID);
}

void AppendLine2DToTab(DATASETTAB& tab, Cad2DLineRecordCPU line) {
    if (!tab.cad2d) tab.cad2d = std::make_unique<TabCad2DStorage>();
    if (line.objectId == 0) line.objectId = MemoryID::next();
    if (line.schemaVersion == 0) {
        line.schemaVersion = VishwakarmaStorage::kGeometry2DLineSchemaVersion;
    }

    {
        std::lock_guard<std::mutex> lock(tab.cad2d->cpuRecordsMutex);
        auto existing = std::find_if(tab.cad2d->lineRecords.begin(), tab.cad2d->lineRecords.end(),
            [&](const Cad2DLineRecordCPU& existingLine) {
                return existingLine.objectId == line.objectId;
            });
        if (existing == tab.cad2d->lineRecords.end()) {
            tab.cad2d->lineRecords.push_back(line);
        }
        else {
            *existing = line;
        }
    }

    if (std::find(tab.allIDsInThisTab.begin(), tab.allIDsInThisTab.end(), line.objectId) ==
        tab.allIDsInThisTab.end()) {
        tab.allIDsInThisTab.push_back(line.objectId);
    }

    EnqueueCad2DLine(tab.tabID, line.containerMemoryId, line);
}

void AppendPolyline2DToTab(DATASETTAB& tab, Cad2DPolylineRecordCPU polyline) {
    if (!tab.cad2d) tab.cad2d = std::make_unique<TabCad2DStorage>();
    if (polyline.objectId == 0) polyline.objectId = MemoryID::next();
    if (polyline.schemaVersion == 0) {
        polyline.schemaVersion = VishwakarmaStorage::kGeometry2DPolylineSchemaVersion;
    }

    {
        std::lock_guard<std::mutex> lock(tab.cad2d->cpuRecordsMutex);
        auto existing = std::find_if(tab.cad2d->polylineRecords.begin(), tab.cad2d->polylineRecords.end(),
            [&](const Cad2DPolylineRecordCPU& existingPolyline) {
                return existingPolyline.objectId == polyline.objectId;
            });
        if (existing == tab.cad2d->polylineRecords.end()) {
            tab.cad2d->polylineRecords.push_back(polyline);
        }
        else {
            *existing = polyline;
        }
    }

    if (std::find(tab.allIDsInThisTab.begin(), tab.allIDsInThisTab.end(), polyline.objectId) ==
        tab.allIDsInThisTab.end()) {
        tab.allIDsInThisTab.push_back(polyline.objectId);
    }

    EnqueueCad2DPolyline(tab.tabID, polyline.containerMemoryId, polyline);
}

void AppendPolygon2DToTab(DATASETTAB& tab, Cad2DPolygonRecordCPU polygon) {
    if (!tab.cad2d) tab.cad2d = std::make_unique<TabCad2DStorage>();
    if (polygon.objectId == 0) polygon.objectId = MemoryID::next();
    polygon.lineSegmentCount = ClampedPolygonLineSegmentCount(polygon.lineSegmentCount);
    if (polygon.schemaVersion == 0) {
        polygon.schemaVersion = VishwakarmaStorage::kGeometry2DPolygonSchemaVersion;
    }

    {
        std::lock_guard<std::mutex> lock(tab.cad2d->cpuRecordsMutex);
        auto existing = std::find_if(tab.cad2d->polygonRecords.begin(), tab.cad2d->polygonRecords.end(),
            [&](const Cad2DPolygonRecordCPU& existingPolygon) {
                return existingPolygon.objectId == polygon.objectId;
            });
        if (existing == tab.cad2d->polygonRecords.end()) {
            tab.cad2d->polygonRecords.push_back(polygon);
        }
        else {
            *existing = polygon;
        }
    }

    if (std::find(tab.allIDsInThisTab.begin(), tab.allIDsInThisTab.end(), polygon.objectId) ==
        tab.allIDsInThisTab.end()) {
        tab.allIDsInThisTab.push_back(polygon.objectId);
    }

    EnqueueCad2DPolygon(tab.tabID, polygon.containerMemoryId, polygon);
}

void AppendCircle2DToTab(DATASETTAB& tab, Cad2DCircleRecordCPU circle) {
    if (!tab.cad2d) tab.cad2d = std::make_unique<TabCad2DStorage>();
    if (circle.objectId == 0) circle.objectId = MemoryID::next();
    if (circle.schemaVersion == 0) {
        circle.schemaVersion = VishwakarmaStorage::kGeometry2DCircleSchemaVersion;
    }

    {
        std::lock_guard<std::mutex> lock(tab.cad2d->cpuRecordsMutex);
        auto existing = std::find_if(tab.cad2d->circleRecords.begin(), tab.cad2d->circleRecords.end(),
            [&](const Cad2DCircleRecordCPU& existingCircle) {
                return existingCircle.objectId == circle.objectId;
            });
        if (existing == tab.cad2d->circleRecords.end()) {
            tab.cad2d->circleRecords.push_back(circle);
        }
        else {
            *existing = circle;
        }
    }

    if (std::find(tab.allIDsInThisTab.begin(), tab.allIDsInThisTab.end(), circle.objectId) ==
        tab.allIDsInThisTab.end()) {
        tab.allIDsInThisTab.push_back(circle.objectId);
    }

    EnqueueCad2DCircle(tab.tabID, circle.containerMemoryId, circle);
}

void AppendEllipse2DToTab(DATASETTAB& tab, Cad2DEllipseRecordCPU ellipse) {
    if (!tab.cad2d) tab.cad2d = std::make_unique<TabCad2DStorage>();
    if (ellipse.objectId == 0) ellipse.objectId = MemoryID::next();
    if (ellipse.schemaVersion == 0) {
        ellipse.schemaVersion = VishwakarmaStorage::kGeometry2DEllipseSchemaVersion;
    }

    {
        std::lock_guard<std::mutex> lock(tab.cad2d->cpuRecordsMutex);
        auto existing = std::find_if(tab.cad2d->ellipseRecords.begin(), tab.cad2d->ellipseRecords.end(),
            [&](const Cad2DEllipseRecordCPU& existingEllipse) {
                return existingEllipse.objectId == ellipse.objectId;
            });
        if (existing == tab.cad2d->ellipseRecords.end()) {
            tab.cad2d->ellipseRecords.push_back(ellipse);
        }
        else {
            *existing = ellipse;
        }
    }

    if (std::find(tab.allIDsInThisTab.begin(), tab.allIDsInThisTab.end(), ellipse.objectId) ==
        tab.allIDsInThisTab.end()) {
        tab.allIDsInThisTab.push_back(ellipse.objectId);
    }

    EnqueueCad2DEllipse(tab.tabID, ellipse.containerMemoryId, ellipse);
}

void AppendArc2DToTab(DATASETTAB& tab, Cad2DArcRecordCPU arc) {
    if (!tab.cad2d) tab.cad2d = std::make_unique<TabCad2DStorage>();
    if (arc.objectId == 0) arc.objectId = MemoryID::next();
    if (arc.schemaVersion == 0) {
        arc.schemaVersion = VishwakarmaStorage::kGeometry2DArcSchemaVersion;
    }

    {
        std::lock_guard<std::mutex> lock(tab.cad2d->cpuRecordsMutex);
        auto existing = std::find_if(tab.cad2d->arcRecords.begin(), tab.cad2d->arcRecords.end(),
            [&](const Cad2DArcRecordCPU& existingArc) {
                return existingArc.objectId == arc.objectId;
            });
        if (existing == tab.cad2d->arcRecords.end()) {
            tab.cad2d->arcRecords.push_back(arc);
        }
        else {
            *existing = arc;
        }
    }

    if (std::find(tab.allIDsInThisTab.begin(), tab.allIDsInThisTab.end(), arc.objectId) ==
        tab.allIDsInThisTab.end()) {
        tab.allIDsInThisTab.push_back(arc.objectId);
    }

    EnqueueCad2DArc(tab.tabID, arc.containerMemoryId, arc);
}

void AppendText2DToTab(DATASETTAB& tab, Cad2DTextRecordCPU text) {
    if (!tab.cad2d) tab.cad2d = std::make_unique<TabCad2DStorage>();
    if (text.objectId == 0) text.objectId = MemoryID::next();
    if (text.schemaVersion == 0) {
        text.schemaVersion = VishwakarmaStorage::kGeometry2DTextSchemaVersion;
    }

    {
        std::lock_guard<std::mutex> lock(tab.cad2d->cpuRecordsMutex);
        auto existing = std::find_if(tab.cad2d->textRecords.begin(), tab.cad2d->textRecords.end(),
            [&](const Cad2DTextRecordCPU& existingText) {
                return existingText.objectId == text.objectId;
            });
        if (existing == tab.cad2d->textRecords.end()) {
            tab.cad2d->textRecords.push_back(text);
        }
        else {
            *existing = text;
        }
    }

    if (std::find(tab.allIDsInThisTab.begin(), tab.allIDsInThisTab.end(), text.objectId) ==
        tab.allIDsInThisTab.end()) {
        tab.allIDsInThisTab.push_back(text.objectId);
    }

    EnqueueCad2DText(tab.tabID, text.containerMemoryId, std::move(text));
}

struct ObjectStoreRow {
    uint64_t objectId = 0;
    uint64_t parentId = 0;
    ObjectType objectType = ObjectType::Unknown;
    uint16_t schemaVersion = VishwakarmaStorage::kGeometry3DMvpSchemaVersion;
    LifecycleState lifecycleState = LifecycleState::Live;
    std::vector<uint8_t> payload;
};

LifecycleState LifecycleForObject(const META_DATA& object) {
    return object.isDeleted ? LifecycleState::SoftDeleted : LifecycleState::Live;
}

bool BuildRowsFromTab(DATASETTAB& tab, std::vector<ObjectStoreRow>& rows, uint64_t& nextObjectId,
    std::string* errorMessage) {
    if (!tab.storageObjectsMutex) tab.storageObjectsMutex = std::make_unique<std::mutex>();

    std::lock_guard<std::mutex> lock(*tab.storageObjectsMutex);
    TabCad2DStorage* cad2d = tab.cad2d.get();
    std::unique_lock<std::mutex> cad2DLock;
    if (cad2d) {
        cad2DLock = std::unique_lock<std::mutex>(cad2d->cpuRecordsMutex);
    }

    uint64_t maxExistingId = 0;
    for (const StoredLogicalObject& entry : tab.storageLogicalObjects) {
        if (entry.object && entry.object->persistedId > maxExistingId) {
            maxExistingId = entry.object->persistedId;
        }
    }
    for (const StoredGeometryObject3D& entry : tab.storageObjects3D) {
        if (entry.object && entry.object->persistedId > maxExistingId) {
            maxExistingId = entry.object->persistedId;
        }
    }
    if (cad2d) {
        for (const Cad2DLineRecordCPU& line : cad2d->lineRecords) {
            if (line.persistedId > maxExistingId) {
                maxExistingId = line.persistedId;
            }
        }
        for (const Cad2DPolylineRecordCPU& polyline : cad2d->polylineRecords) {
            if (polyline.persistedId > maxExistingId) {
                maxExistingId = polyline.persistedId;
            }
        }
        for (const Cad2DPolygonRecordCPU& polygon : cad2d->polygonRecords) {
            if (polygon.persistedId > maxExistingId) {
                maxExistingId = polygon.persistedId;
            }
        }
        for (const Cad2DCircleRecordCPU& circle : cad2d->circleRecords) {
            if (circle.persistedId > maxExistingId) {
                maxExistingId = circle.persistedId;
            }
        }
        for (const Cad2DEllipseRecordCPU& ellipse : cad2d->ellipseRecords) {
            if (ellipse.persistedId > maxExistingId) {
                maxExistingId = ellipse.persistedId;
            }
        }
        for (const Cad2DArcRecordCPU& arc : cad2d->arcRecords) {
            if (arc.persistedId > maxExistingId) {
                maxExistingId = arc.persistedId;
            }
        }
        for (const Cad2DTextRecordCPU& text : cad2d->textRecords) {
            if (text.persistedId > maxExistingId) {
                maxExistingId = text.persistedId;
            }
        }
    }

    uint64_t assignNextId = maxExistingId + 1;
    if (assignNextId == 0) assignNextId = 1;

    for (StoredLogicalObject& entry : tab.storageLogicalObjects) {
        if (!entry.object) continue;

        if (entry.object->persistedId == 0) {
            if (assignNextId > VishwakarmaStorage::kMaxLocalObjectId) {
                SetError(errorMessage, "MVP object_id counter exceeded the 40-bit local object ID range.");
                return false;
            }
            entry.object->persistedId = assignNextId++;
        }
    }

    for (StoredGeometryObject3D& entry : tab.storageObjects3D) {
        if (!entry.object) continue;

        if (entry.object->persistedId == 0) {
            if (assignNextId > VishwakarmaStorage::kMaxLocalObjectId) {
                SetError(errorMessage, "MVP object_id counter exceeded the 40-bit local object ID range.");
                return false;
            }
            entry.object->persistedId = assignNextId++;
        }
    }

    if (cad2d) {
        for (Cad2DLineRecordCPU& line : cad2d->lineRecords) {
            if (line.objectId == 0) {
                line.objectId = MemoryID::next();
            }
            if (line.persistedId == 0) {
                if (assignNextId > VishwakarmaStorage::kMaxLocalObjectId) {
                    SetError(errorMessage, "MVP object_id counter exceeded the 40-bit local object ID range.");
                    return false;
                }
                line.persistedId = assignNextId++;
            }
            if (line.schemaVersion == 0) {
                line.schemaVersion = VishwakarmaStorage::kGeometry2DLineSchemaVersion;
            }
        }
        for (Cad2DPolylineRecordCPU& polyline : cad2d->polylineRecords) {
            if (polyline.objectId == 0) {
                polyline.objectId = MemoryID::next();
            }
            if (polyline.persistedId == 0) {
                if (assignNextId > VishwakarmaStorage::kMaxLocalObjectId) {
                    SetError(errorMessage, "MVP object_id counter exceeded the 40-bit local object ID range.");
                    return false;
                }
                polyline.persistedId = assignNextId++;
            }
            if (polyline.schemaVersion == 0) {
                polyline.schemaVersion = VishwakarmaStorage::kGeometry2DPolylineSchemaVersion;
            }
        }
        for (Cad2DPolygonRecordCPU& polygon : cad2d->polygonRecords) {
            if (polygon.objectId == 0) {
                polygon.objectId = MemoryID::next();
            }
            polygon.lineSegmentCount = ClampedPolygonLineSegmentCount(polygon.lineSegmentCount);
            if (polygon.persistedId == 0) {
                if (assignNextId > VishwakarmaStorage::kMaxLocalObjectId) {
                    SetError(errorMessage, "MVP object_id counter exceeded the 40-bit local object ID range.");
                    return false;
                }
                polygon.persistedId = assignNextId++;
            }
            if (polygon.schemaVersion == 0) {
                polygon.schemaVersion = VishwakarmaStorage::kGeometry2DPolygonSchemaVersion;
            }
        }
        for (Cad2DCircleRecordCPU& circle : cad2d->circleRecords) {
            if (circle.objectId == 0) {
                circle.objectId = MemoryID::next();
            }
            if (circle.persistedId == 0) {
                if (assignNextId > VishwakarmaStorage::kMaxLocalObjectId) {
                    SetError(errorMessage, "MVP object_id counter exceeded the 40-bit local object ID range.");
                    return false;
                }
                circle.persistedId = assignNextId++;
            }
            if (circle.schemaVersion == 0) {
                circle.schemaVersion = VishwakarmaStorage::kGeometry2DCircleSchemaVersion;
            }
        }
        for (Cad2DEllipseRecordCPU& ellipse : cad2d->ellipseRecords) {
            if (ellipse.objectId == 0) {
                ellipse.objectId = MemoryID::next();
            }
            if (ellipse.persistedId == 0) {
                if (assignNextId > VishwakarmaStorage::kMaxLocalObjectId) {
                    SetError(errorMessage, "MVP object_id counter exceeded the 40-bit local object ID range.");
                    return false;
                }
                ellipse.persistedId = assignNextId++;
            }
            if (ellipse.schemaVersion == 0) {
                ellipse.schemaVersion = VishwakarmaStorage::kGeometry2DEllipseSchemaVersion;
            }
        }
        for (Cad2DArcRecordCPU& arc : cad2d->arcRecords) {
            if (arc.objectId == 0) {
                arc.objectId = MemoryID::next();
            }
            if (arc.persistedId == 0) {
                if (assignNextId > VishwakarmaStorage::kMaxLocalObjectId) {
                    SetError(errorMessage, "MVP object_id counter exceeded the 40-bit local object ID range.");
                    return false;
                }
                arc.persistedId = assignNextId++;
            }
            if (arc.schemaVersion == 0) {
                arc.schemaVersion = VishwakarmaStorage::kGeometry2DArcSchemaVersion;
            }
        }
        for (Cad2DTextRecordCPU& text : cad2d->textRecords) {
            if (text.objectId == 0) {
                text.objectId = MemoryID::next();
            }
            if (text.persistedId == 0) {
                if (assignNextId > VishwakarmaStorage::kMaxLocalObjectId) {
                    SetError(errorMessage, "MVP object_id counter exceeded the 40-bit local object ID range.");
                    return false;
                }
                text.persistedId = assignNextId++;
            }
            if (text.schemaVersion == 0) {
                text.schemaVersion = VishwakarmaStorage::kGeometry2DTextSchemaVersion;
            }
        }
    }

    std::unordered_map<uint64_t, uint64_t> memoryIdToPersistedId;
    memoryIdToPersistedId.reserve(tab.storageLogicalObjects.size() + tab.storageObjects3D.size() +
        (cad2d ? cad2d->lineRecords.size() + cad2d->polylineRecords.size() +
            cad2d->polygonRecords.size() + cad2d->circleRecords.size() +
            cad2d->ellipseRecords.size() + cad2d->arcRecords.size() +
            cad2d->textRecords.size() : 0));

    for (const StoredLogicalObject& entry : tab.storageLogicalObjects) {
        if (entry.object && entry.object->persistedId != 0) {
            memoryIdToPersistedId[entry.object->memoryID] = entry.object->persistedId;
        }
    }
    for (const StoredGeometryObject3D& entry : tab.storageObjects3D) {
        if (entry.object && entry.object->persistedId != 0) {
            memoryIdToPersistedId[entry.object->memoryID] = entry.object->persistedId;
        }
    }
    if (cad2d) {
        for (const Cad2DLineRecordCPU& line : cad2d->lineRecords) {
            if (line.objectId != 0 && line.persistedId != 0) {
                memoryIdToPersistedId[line.objectId] = line.persistedId;
            }
        }
        for (const Cad2DPolylineRecordCPU& polyline : cad2d->polylineRecords) {
            if (polyline.objectId != 0 && polyline.persistedId != 0) {
                memoryIdToPersistedId[polyline.objectId] = polyline.persistedId;
            }
        }
        for (const Cad2DPolygonRecordCPU& polygon : cad2d->polygonRecords) {
            if (polygon.objectId != 0 && polygon.persistedId != 0) {
                memoryIdToPersistedId[polygon.objectId] = polygon.persistedId;
            }
        }
        for (const Cad2DCircleRecordCPU& circle : cad2d->circleRecords) {
            if (circle.objectId != 0 && circle.persistedId != 0) {
                memoryIdToPersistedId[circle.objectId] = circle.persistedId;
            }
        }
        for (const Cad2DEllipseRecordCPU& ellipse : cad2d->ellipseRecords) {
            if (ellipse.objectId != 0 && ellipse.persistedId != 0) {
                memoryIdToPersistedId[ellipse.objectId] = ellipse.persistedId;
            }
        }
        for (const Cad2DArcRecordCPU& arc : cad2d->arcRecords) {
            if (arc.objectId != 0 && arc.persistedId != 0) {
                memoryIdToPersistedId[arc.objectId] = arc.persistedId;
            }
        }
        for (const Cad2DTextRecordCPU& text : cad2d->textRecords) {
            if (text.objectId != 0 && text.persistedId != 0) {
                memoryIdToPersistedId[text.objectId] = text.persistedId;
            }
        }
    }

    auto resolveParentId = [&](META_DATA* object) {
        if (!object) return uint64_t{ 0 };
        if (object->memoryIDParent != 0) {
            auto parentIt = memoryIdToPersistedId.find(object->memoryIDParent);
            if (parentIt != memoryIdToPersistedId.end()) {
                object->persistedParentId = parentIt->second;
                return parentIt->second;
            }
        }
        return object->persistedParentId;
    };

    auto resolveLineParentId = [&](Cad2DLineRecordCPU& line) {
        if (line.containerMemoryId != 0) {
            auto parentIt = memoryIdToPersistedId.find(line.containerMemoryId);
            if (parentIt != memoryIdToPersistedId.end()) {
                line.persistedParentId = parentIt->second;
                return parentIt->second;
            }
        }
        return line.persistedParentId;
    };

    auto resolvePolylineParentId = [&](Cad2DPolylineRecordCPU& polyline) {
        if (polyline.containerMemoryId != 0) {
            auto parentIt = memoryIdToPersistedId.find(polyline.containerMemoryId);
            if (parentIt != memoryIdToPersistedId.end()) {
                polyline.persistedParentId = parentIt->second;
                return parentIt->second;
            }
        }
        return polyline.persistedParentId;
    };

    auto resolvePolygonParentId = [&](Cad2DPolygonRecordCPU& polygon) {
        if (polygon.containerMemoryId != 0) {
            auto parentIt = memoryIdToPersistedId.find(polygon.containerMemoryId);
            if (parentIt != memoryIdToPersistedId.end()) {
                polygon.persistedParentId = parentIt->second;
                return parentIt->second;
            }
        }
        return polygon.persistedParentId;
    };

    auto resolveCircleParentId = [&](Cad2DCircleRecordCPU& circle) {
        if (circle.containerMemoryId != 0) {
            auto parentIt = memoryIdToPersistedId.find(circle.containerMemoryId);
            if (parentIt != memoryIdToPersistedId.end()) {
                circle.persistedParentId = parentIt->second;
                return parentIt->second;
            }
        }
        return circle.persistedParentId;
    };

    auto resolveEllipseParentId = [&](Cad2DEllipseRecordCPU& ellipse) {
        if (ellipse.containerMemoryId != 0) {
            auto parentIt = memoryIdToPersistedId.find(ellipse.containerMemoryId);
            if (parentIt != memoryIdToPersistedId.end()) {
                ellipse.persistedParentId = parentIt->second;
                return parentIt->second;
            }
        }
        return ellipse.persistedParentId;
    };

    auto resolveArcParentId = [&](Cad2DArcRecordCPU& arc) {
        if (arc.containerMemoryId != 0) {
            auto parentIt = memoryIdToPersistedId.find(arc.containerMemoryId);
            if (parentIt != memoryIdToPersistedId.end()) {
                arc.persistedParentId = parentIt->second;
                return parentIt->second;
            }
        }
        return arc.persistedParentId;
    };

    auto resolveTextParentId = [&](Cad2DTextRecordCPU& text) {
        if (text.containerMemoryId != 0) {
            auto parentIt = memoryIdToPersistedId.find(text.containerMemoryId);
            if (parentIt != memoryIdToPersistedId.end()) {
                text.persistedParentId = parentIt->second;
                return parentIt->second;
            }
        }
        return text.persistedParentId;
    };

    for (StoredLogicalObject& entry : tab.storageLogicalObjects) {
        if (!entry.object) continue;

        std::vector<uint8_t> payload;
        if (!SerializeLogicalObject(entry, payload, errorMessage)) return false;

        ObjectStoreRow row;
        row.objectId = entry.object->persistedId;
        row.parentId = resolveParentId(entry.object);
        row.objectType = entry.objectType;
        row.schemaVersion = entry.object->schemaVersion != 0
            ? entry.object->schemaVersion
            : VishwakarmaStorage::kLogicalElementSchemaVersion;
        row.lifecycleState = LifecycleForObject(*entry.object);
        row.payload = std::move(payload);
        rows.push_back(std::move(row));
    }

    if (cad2d) {
        for (Cad2DLineRecordCPU& line : cad2d->lineRecords) {
            if (line.objectId == 0) continue;

            std::vector<uint8_t> payload;
            if (!EncodeLine2D(line, payload, errorMessage)) return false;

            ObjectStoreRow row;
            row.objectId = line.persistedId;
            row.parentId = resolveLineParentId(line);
            row.objectType = ObjectType::Line2D;
            row.schemaVersion = line.schemaVersion != 0
                ? line.schemaVersion
                : VishwakarmaStorage::kGeometry2DLineSchemaVersion;
            row.lifecycleState = line.isDeleted ? LifecycleState::SoftDeleted : LifecycleState::Live;
            row.payload = std::move(payload);
            rows.push_back(std::move(row));
        }

        for (Cad2DPolylineRecordCPU& polyline : cad2d->polylineRecords) {
            if (polyline.objectId == 0 || polyline.points.size() < 2) continue;

            std::vector<uint8_t> payload;
            if (!EncodePolyline2D(polyline, payload, errorMessage)) return false;

            ObjectStoreRow row;
            row.objectId = polyline.persistedId;
            row.parentId = resolvePolylineParentId(polyline);
            row.objectType = ObjectType::Polyline2D;
            row.schemaVersion = polyline.schemaVersion != 0
                ? polyline.schemaVersion
                : VishwakarmaStorage::kGeometry2DPolylineSchemaVersion;
            row.lifecycleState = polyline.isDeleted ? LifecycleState::SoftDeleted : LifecycleState::Live;
            row.payload = std::move(payload);
            rows.push_back(std::move(row));
        }

        for (Cad2DPolygonRecordCPU& polygon : cad2d->polygonRecords) {
            if (polygon.objectId == 0 || polygon.radius <= 0.0) continue;
            polygon.lineSegmentCount = ClampedPolygonLineSegmentCount(polygon.lineSegmentCount);

            std::vector<uint8_t> payload;
            if (!EncodePolygon2D(polygon, payload, errorMessage)) return false;

            ObjectStoreRow row;
            row.objectId = polygon.persistedId;
            row.parentId = resolvePolygonParentId(polygon);
            row.objectType = ObjectType::Polygon2D;
            row.schemaVersion = polygon.schemaVersion != 0
                ? polygon.schemaVersion
                : VishwakarmaStorage::kGeometry2DPolygonSchemaVersion;
            row.lifecycleState = polygon.isDeleted ? LifecycleState::SoftDeleted : LifecycleState::Live;
            row.payload = std::move(payload);
            rows.push_back(std::move(row));
        }

        for (Cad2DCircleRecordCPU& circle : cad2d->circleRecords) {
            if (circle.objectId == 0 || circle.radius <= 0.0) continue;

            std::vector<uint8_t> payload;
            if (!EncodeCircle2D(circle, payload, errorMessage)) return false;

            ObjectStoreRow row;
            row.objectId = circle.persistedId;
            row.parentId = resolveCircleParentId(circle);
            row.objectType = ObjectType::Circle2D;
            row.schemaVersion = circle.schemaVersion != 0
                ? circle.schemaVersion
                : VishwakarmaStorage::kGeometry2DCircleSchemaVersion;
            row.lifecycleState = circle.isDeleted ? LifecycleState::SoftDeleted : LifecycleState::Live;
            row.payload = std::move(payload);
            rows.push_back(std::move(row));
        }

        for (Cad2DEllipseRecordCPU& ellipse : cad2d->ellipseRecords) {
            if (ellipse.objectId == 0 || ellipse.radiusX <= 0.0 || ellipse.radiusY <= 0.0) continue;

            std::vector<uint8_t> payload;
            if (!EncodeEllipse2D(ellipse, payload, errorMessage)) return false;

            ObjectStoreRow row;
            row.objectId = ellipse.persistedId;
            row.parentId = resolveEllipseParentId(ellipse);
            row.objectType = ObjectType::Ellipse2D;
            row.schemaVersion = ellipse.schemaVersion != 0
                ? ellipse.schemaVersion
                : VishwakarmaStorage::kGeometry2DEllipseSchemaVersion;
            row.lifecycleState = ellipse.isDeleted ? LifecycleState::SoftDeleted : LifecycleState::Live;
            row.payload = std::move(payload);
            rows.push_back(std::move(row));
        }

        for (Cad2DArcRecordCPU& arc : cad2d->arcRecords) {
            if (arc.objectId == 0 || arc.radiusX <= 0.0 || arc.radiusY <= 0.0) continue;

            std::vector<uint8_t> payload;
            if (!EncodeArc2D(arc, payload, errorMessage)) return false;

            ObjectStoreRow row;
            row.objectId = arc.persistedId;
            row.parentId = resolveArcParentId(arc);
            row.objectType = ObjectType::Arc2D;
            row.schemaVersion = arc.schemaVersion != 0
                ? arc.schemaVersion
                : VishwakarmaStorage::kGeometry2DArcSchemaVersion;
            row.lifecycleState = arc.isDeleted ? LifecycleState::SoftDeleted : LifecycleState::Live;
            row.payload = std::move(payload);
            rows.push_back(std::move(row));
        }

        for (Cad2DTextRecordCPU& text : cad2d->textRecords) {
            if (text.objectId == 0 || text.text.empty()) continue;

            std::vector<uint8_t> payload;
            if (!EncodeText2D(text, payload, errorMessage)) return false;

            ObjectStoreRow row;
            row.objectId = text.persistedId;
            row.parentId = resolveTextParentId(text);
            row.objectType = ObjectType::Text2D;
            row.schemaVersion = text.schemaVersion != 0
                ? text.schemaVersion
                : VishwakarmaStorage::kGeometry2DTextSchemaVersion;
            row.lifecycleState = text.isDeleted ? LifecycleState::SoftDeleted : LifecycleState::Live;
            row.payload = std::move(payload);
            rows.push_back(std::move(row));
        }
    }

    for (StoredGeometryObject3D& entry : tab.storageObjects3D) {
        if (!entry.object) continue;

        std::vector<uint8_t> payload;
        if (!SerializeGeometryObject(entry, payload, errorMessage)) return false;

        ObjectStoreRow row;
        row.objectId = entry.object->persistedId;
        row.parentId = resolveParentId(entry.object);
        row.objectType = entry.objectType;
        row.schemaVersion = entry.object->schemaVersion != 0
            ? entry.object->schemaVersion
            : VishwakarmaStorage::kGeometry3DMvpSchemaVersion;
        row.lifecycleState = LifecycleForObject(*entry.object);
        row.payload = std::move(payload);
        rows.push_back(std::move(row));
    }

    nextObjectId = (std::max)(assignNextId, maxExistingId + 1);
    if (nextObjectId == 0) nextObjectId = 1;
    return true;
}

bool InsertObjectRows(sqlite3* db, const std::vector<ObjectStoreRow>& rows, std::string* errorMessage) {
    SQLiteStatement statement;
    if (!Prepare(db,
        "INSERT INTO object_store(object_id, parent_id, object_type, schema_version, lifecycle_state, data) "
        "VALUES(?, ?, ?, ?, ?, ?);",
        statement, errorMessage)) {
        return false;
    }

    for (const ObjectStoreRow& row : rows) {
        sqlite3_reset(statement.stmt);
        sqlite3_clear_bindings(statement.stmt);

        sqlite3_bind_int64(statement.stmt, 1, static_cast<sqlite3_int64>(row.objectId));
        if (row.parentId == 0) {
            sqlite3_bind_null(statement.stmt, 2);
        } else {
            sqlite3_bind_int64(statement.stmt, 2, static_cast<sqlite3_int64>(row.parentId));
        }
        sqlite3_bind_int(statement.stmt, 3, static_cast<int>(VishwakarmaStorage::ToNumber(row.objectType)));
        sqlite3_bind_int(statement.stmt, 4, row.schemaVersion);
        sqlite3_bind_int(statement.stmt, 5, static_cast<int>(VishwakarmaStorage::ToNumber(row.lifecycleState)));
        sqlite3_bind_blob(statement.stmt, 6, row.payload.data(),
            static_cast<int>(row.payload.size()), SQLITE_TRANSIENT);

        int rc = sqlite3_step(statement.stmt);
        if (rc != SQLITE_DONE) {
            SetError(errorMessage, SqliteError(db, "Failed to insert object_store row"));
            return false;
        }
    }

    return true;
}

bool ReadObjectPayload(sqlite3_stmt* statement, int columnIndex, std::vector<uint8_t>& payload) {
    const void* blob = sqlite3_column_blob(statement, columnIndex);
    int blobSize = sqlite3_column_bytes(statement, columnIndex);
    if (blobSize < 0 || (blobSize > 0 && !blob)) return false;
    if (blobSize == 0) {
        payload.clear();
        return true;
    }
    const uint8_t* begin = static_cast<const uint8_t*>(blob);
    payload.assign(begin, begin + blobSize);
    return true;
}

} // namespace

DataStorage& DataStorage::Instance() {
    static DataStorage instance;
    return instance;
}

bool DataStorage::SaveTabToYyy(DATASETTAB& tab, const std::wstring& filePath,
    std::string* errorMessage) {
    SQLiteDatabase database;
    int rc = sqlite3_open16(filePath.c_str(), &database.db);
    if (rc != SQLITE_OK || !database.db) {
        SetError(errorMessage, SqliteError(database.db, "Could not open .yyy file for saving"));
        return false;
    }

    if (!EnsureSchema(database.db, errorMessage)) return false;

    std::vector<ObjectStoreRow> rows;
    uint64_t nextObjectId = 1;
    if (!BuildRowsFromTab(tab, rows, nextObjectId, errorMessage)) return false;

    if (!ExecSql(database.db, "BEGIN IMMEDIATE TRANSACTION;", errorMessage)) return false;
    if (!ExecSql(database.db, "DELETE FROM object_store;", errorMessage)) {
        ExecSql(database.db, "ROLLBACK;", nullptr);
        return false;
    }
    if (!InsertObjectRows(database.db, rows, errorMessage)) {
        ExecSql(database.db, "ROLLBACK;", nullptr);
        return false;
    }
    if (!EnsureFileInfo(database.db, nextObjectId, errorMessage)) {
        ExecSql(database.db, "ROLLBACK;", nullptr);
        return false;
    }
    if (!ExecSql(database.db, "COMMIT;", errorMessage)) {
        ExecSql(database.db, "ROLLBACK;", nullptr);
        return false;
    }

    return true;
}

bool DataStorage::LoadYyyIntoTab(DATASETTAB& tab, const std::wstring& filePath,
    std::string* errorMessage) {
    SQLiteDatabase database;
    int rc = sqlite3_open16(filePath.c_str(), &database.db);
    if (rc != SQLITE_OK || !database.db) {
        SetError(errorMessage, SqliteError(database.db, "Could not open .yyy file for loading"));
        return false;
    }

    SQLiteStatement statement;
    if (!Prepare(database.db,
        "SELECT object_id, parent_id, object_type, schema_version, lifecycle_state, data "
        "FROM object_store WHERE lifecycle_state = 0 ORDER BY object_id;",
        statement, errorMessage)) {
        return false;
    }

    if (!tab.storageObjectsMutex) tab.storageObjectsMutex = std::make_unique<std::mutex>();
    {
        std::lock_guard<std::mutex> lock(*tab.storageObjectsMutex);
        tab.storageLogicalObjects.clear();
        tab.storageObjects3D.clear();
        tab.expandedDataTreeNodeIds.clear();
        CloseAllInternalSubTabsLocked(tab);
        tab.defaultScene3DMemoryId = 0;
        tab.activeScene3DMemoryId = 0;
    }
    if (tab.cad2d) {
        std::lock_guard<std::mutex> lock(tab.cad2d->cpuRecordsMutex);
        tab.cad2d->lineRecords.clear();
        tab.cad2d->polylineRecords.clear();
        tab.cad2d->polygonRecords.clear();
        tab.cad2d->circleRecords.clear();
        tab.cad2d->ellipseRecords.clear();
        tab.cad2d->arcRecords.clear();
        tab.cad2d->textRecords.clear();
        tab.cad2d->demoLineCounter.store(0, std::memory_order_release);
        tab.cad2d->demoTextQueued.store(false, std::memory_order_release);
        tab.cad2d->lineCreationMode.store(false, std::memory_order_release);
        tab.cad2d->lineCreationHasPreviousPoint.store(false, std::memory_order_release);
        tab.cad2d->polylineCreationMode.store(false, std::memory_order_release);
        tab.cad2d->polylineCreationObjectId = 0;
        tab.cad2d->polylineCreationPoints.clear();
        tab.cad2d->polygonCreationMode.store(false, std::memory_order_release);
        tab.cad2d->polygonCreationHasCenter.store(false, std::memory_order_release);
        tab.cad2d->polygonCreationCenterXCU.store(0.0, std::memory_order_release);
        tab.cad2d->polygonCreationCenterYCU.store(0.0, std::memory_order_release);
        tab.cad2d->circleCreationMode.store(false, std::memory_order_release);
        tab.cad2d->circleCreationHasCenter.store(false, std::memory_order_release);
        tab.cad2d->circleCreationCenterXCU.store(0.0, std::memory_order_release);
        tab.cad2d->circleCreationCenterYCU.store(0.0, std::memory_order_release);
        tab.cad2d->ellipseCreationMode.store(false, std::memory_order_release);
        tab.cad2d->ellipseCreationStep.store(0, std::memory_order_release);
        tab.cad2d->ellipseCreationCenterXCU.store(0.0, std::memory_order_release);
        tab.cad2d->ellipseCreationCenterYCU.store(0.0, std::memory_order_release);
        tab.cad2d->ellipseCreationRadiusXCU.store(0.0, std::memory_order_release);
        tab.cad2d->arcCreationMode.store(false, std::memory_order_release);
        tab.cad2d->arcCreationStep.store(0, std::memory_order_release);
        tab.cad2d->arcCreationCenterXCU.store(0.0, std::memory_order_release);
        tab.cad2d->arcCreationCenterYCU.store(0.0, std::memory_order_release);
        tab.cad2d->arcCreationStartXCU.store(0.0, std::memory_order_release);
        tab.cad2d->arcCreationStartYCU.store(0.0, std::memory_order_release);
        tab.cad2d->textCreationMode.store(false, std::memory_order_release);
        tab.cad2d->textCreationHasAnchor.store(false, std::memory_order_release);
        tab.cad2d->textCreationXCU.store(0.0, std::memory_order_release);
        tab.cad2d->textCreationYCU.store(0.0, std::memory_order_release);
        tab.cad2d->textCreationObjectId = 0;
        tab.cad2d->textCreationDraft.clear();
    }
    DataTreeView::ResetScroll(tab.dataTreeView);
    tab.allIDsInThisTab.clear();

    std::unordered_map<uint64_t, uint64_t> persistedIdToMemoryId;

    while ((rc = sqlite3_step(statement.stmt)) == SQLITE_ROW) {
        uint64_t objectId = static_cast<uint64_t>(sqlite3_column_int64(statement.stmt, 0));
        uint64_t parentId = sqlite3_column_type(statement.stmt, 1) == SQLITE_NULL
            ? 0
            : static_cast<uint64_t>(sqlite3_column_int64(statement.stmt, 1));
        uint32_t objectTypeNumber = static_cast<uint32_t>(sqlite3_column_int(statement.stmt, 2));
        uint16_t schemaVersion = static_cast<uint16_t>(sqlite3_column_int(statement.stmt, 3));

        ObjectType objectType = ObjectType::Unknown;
        if (!ObjectTypeFromNumber(objectTypeNumber, objectType)) {
            SetError(errorMessage, "Unsupported object_type in .yyy file: " + std::to_string(objectTypeNumber));
            return false;
        }

        std::vector<uint8_t> payload;
        if (!ReadObjectPayload(statement.stmt, 5, payload)) {
            SetError(errorMessage, "Could not read object payload from SQLite.");
            return false;
        }

        if (VishwakarmaStorage::IsGeometry2DObjectType(objectType)) {
            if (objectType == ObjectType::Line2D) {
                Cad2DLineRecordCPU line;
                if (!DecodeLine2D(payload, line)) {
                    SetError(errorMessage, "Could not decode " + ObjectTypeName(objectType) + " protobuf payload.");
                    return false;
                }

                line.objectId = MemoryID::next();
                line.persistedId = objectId;
                line.persistedParentId = parentId;
                line.schemaVersion = schemaVersion != 0
                    ? schemaVersion
                    : DefaultSchemaVersionForObjectType(objectType);
                line.isDeleted = false;
                if (parentId != 0) {
                    auto parentIt = persistedIdToMemoryId.find(parentId);
                    if (parentIt != persistedIdToMemoryId.end()) {
                        line.containerMemoryId = parentIt->second;
                    }
                }

                AppendLine2DToTab(tab, line);
                persistedIdToMemoryId[objectId] = line.objectId;
            }
            else if (objectType == ObjectType::Polyline2D) {
                Cad2DPolylineRecordCPU polyline;
                if (!DecodePolyline2D(payload, polyline)) {
                    SetError(errorMessage, "Could not decode " + ObjectTypeName(objectType) + " protobuf payload.");
                    return false;
                }

                polyline.objectId = MemoryID::next();
                polyline.persistedId = objectId;
                polyline.persistedParentId = parentId;
                polyline.schemaVersion = schemaVersion != 0
                    ? schemaVersion
                    : DefaultSchemaVersionForObjectType(objectType);
                polyline.isDeleted = false;
                if (parentId != 0) {
                    auto parentIt = persistedIdToMemoryId.find(parentId);
                    if (parentIt != persistedIdToMemoryId.end()) {
                        polyline.containerMemoryId = parentIt->second;
                    }
                }

                const uint64_t runtimeObjectId = polyline.objectId;
                AppendPolyline2DToTab(tab, std::move(polyline));
                persistedIdToMemoryId[objectId] = runtimeObjectId;
            }
            else if (objectType == ObjectType::Polygon2D) {
                Cad2DPolygonRecordCPU polygon;
                if (!DecodePolygon2D(payload, polygon)) {
                    SetError(errorMessage, "Could not decode " + ObjectTypeName(objectType) + " protobuf payload.");
                    return false;
                }

                polygon.objectId = MemoryID::next();
                polygon.persistedId = objectId;
                polygon.persistedParentId = parentId;
                polygon.schemaVersion = schemaVersion != 0
                    ? schemaVersion
                    : DefaultSchemaVersionForObjectType(objectType);
                polygon.isDeleted = false;
                if (parentId != 0) {
                    auto parentIt = persistedIdToMemoryId.find(parentId);
                    if (parentIt != persistedIdToMemoryId.end()) {
                        polygon.containerMemoryId = parentIt->second;
                    }
                }

                const uint64_t runtimeObjectId = polygon.objectId;
                AppendPolygon2DToTab(tab, polygon);
                persistedIdToMemoryId[objectId] = runtimeObjectId;
            }
            else if (objectType == ObjectType::Circle2D) {
                Cad2DCircleRecordCPU circle;
                if (!DecodeCircle2D(payload, circle)) {
                    SetError(errorMessage, "Could not decode " + ObjectTypeName(objectType) + " protobuf payload.");
                    return false;
                }

                circle.objectId = MemoryID::next();
                circle.persistedId = objectId;
                circle.persistedParentId = parentId;
                circle.schemaVersion = schemaVersion != 0
                    ? schemaVersion
                    : DefaultSchemaVersionForObjectType(objectType);
                circle.isDeleted = false;
                if (parentId != 0) {
                    auto parentIt = persistedIdToMemoryId.find(parentId);
                    if (parentIt != persistedIdToMemoryId.end()) {
                        circle.containerMemoryId = parentIt->second;
                    }
                }

                const uint64_t runtimeObjectId = circle.objectId;
                AppendCircle2DToTab(tab, circle);
                persistedIdToMemoryId[objectId] = runtimeObjectId;
            }
            else if (objectType == ObjectType::Ellipse2D) {
                Cad2DEllipseRecordCPU ellipse;
                if (!DecodeEllipse2D(payload, ellipse)) {
                    SetError(errorMessage, "Could not decode " + ObjectTypeName(objectType) + " protobuf payload.");
                    return false;
                }

                ellipse.objectId = MemoryID::next();
                ellipse.persistedId = objectId;
                ellipse.persistedParentId = parentId;
                ellipse.schemaVersion = schemaVersion != 0
                    ? schemaVersion
                    : DefaultSchemaVersionForObjectType(objectType);
                ellipse.isDeleted = false;
                if (parentId != 0) {
                    auto parentIt = persistedIdToMemoryId.find(parentId);
                    if (parentIt != persistedIdToMemoryId.end()) {
                        ellipse.containerMemoryId = parentIt->second;
                    }
                }

                const uint64_t runtimeObjectId = ellipse.objectId;
                AppendEllipse2DToTab(tab, ellipse);
                persistedIdToMemoryId[objectId] = runtimeObjectId;
            }
            else if (objectType == ObjectType::Arc2D) {
                Cad2DArcRecordCPU arc;
                if (!DecodeArc2D(payload, arc)) {
                    SetError(errorMessage, "Could not decode " + ObjectTypeName(objectType) + " protobuf payload.");
                    return false;
                }

                arc.objectId = MemoryID::next();
                arc.persistedId = objectId;
                arc.persistedParentId = parentId;
                arc.schemaVersion = schemaVersion != 0
                    ? schemaVersion
                    : DefaultSchemaVersionForObjectType(objectType);
                arc.isDeleted = false;
                if (parentId != 0) {
                    auto parentIt = persistedIdToMemoryId.find(parentId);
                    if (parentIt != persistedIdToMemoryId.end()) {
                        arc.containerMemoryId = parentIt->second;
                    }
                }

                const uint64_t runtimeObjectId = arc.objectId;
                AppendArc2DToTab(tab, arc);
                persistedIdToMemoryId[objectId] = runtimeObjectId;
            }
            else if (objectType == ObjectType::Text2D) {
                Cad2DTextRecordCPU text;
                if (!DecodeText2D(payload, text)) {
                    SetError(errorMessage, "Could not decode " + ObjectTypeName(objectType) + " protobuf payload.");
                    return false;
                }

                text.objectId = MemoryID::next();
                text.persistedId = objectId;
                text.persistedParentId = parentId;
                text.schemaVersion = schemaVersion != 0
                    ? schemaVersion
                    : DefaultSchemaVersionForObjectType(objectType);
                text.isDeleted = false;
                if (parentId != 0) {
                    auto parentIt = persistedIdToMemoryId.find(parentId);
                    if (parentIt != persistedIdToMemoryId.end()) {
                        text.containerMemoryId = parentIt->second;
                    }
                }

                const uint64_t runtimeObjectId = text.objectId;
                AppendText2DToTab(tab, std::move(text));
                persistedIdToMemoryId[objectId] = runtimeObjectId;
            }
            else {
                SetError(errorMessage, "Unsupported 2D object_type in .yyy file: " + std::to_string(objectTypeNumber));
                return false;
            }
            continue;
        }

        META_DATA* object = nullptr;
        if (VishwakarmaStorage::IsLogicalObjectType(objectType)) {
            if (!DeserializeLogicalObject(objectType, payload, tab.tabNo, object, errorMessage)) {
                return false;
            }
        } else if (VishwakarmaStorage::IsGeometry3DObjectType(objectType)) {
            if (!DeserializeGeometryObject(objectType, payload, tab.tabNo, object, errorMessage)) {
                return false;
            }
        } else {
            SetError(errorMessage, "Unsupported object_type in .yyy file: " + std::to_string(objectTypeNumber));
            return false;
        }

        object->persistedId = objectId;
        object->persistedParentId = parentId;
        if (parentId != 0) {
            auto parentIt = persistedIdToMemoryId.find(parentId);
            if (parentIt != persistedIdToMemoryId.end()) {
                object->memoryIDParent = parentIt->second;
            }
        }
        object->schemaVersion = schemaVersion != 0
            ? schemaVersion
            : DefaultSchemaVersionForObjectType(objectType);
        object->isDeleted = false;
        if (VishwakarmaStorage::IsLogicalObjectType(objectType)) {
            AppendLogicalObjectToTab(tab, objectType, object);
        } else {
            AppendObjectToTab(tab, objectType, object);
        }
        persistedIdToMemoryId[objectId] = object->memoryID;
    }

    if (rc != SQLITE_DONE) {
        SetError(errorMessage, SqliteError(database.db, "Failed while reading object_store"));
        return false;
    }

    return true;
}
