// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
#pragma once

#include <cstdint>
#include <mutex>
#include <queue>
#include <string>
#include <vector>

#include "UserInputProcessing.h"

struct DATASETTAB;

enum class Cad2DLineWeightMode : uint32_t {
    ModelComputerUnit = 0, // thickness is in Page2D ComputerUnits and zooms with the drawing
    ScreenPixel = 1,       // thickness is fixed in screen pixels
    PaperMM = 2            // thickness is millimeters converted through monitor DPI
};

enum class Cad2DTextJustification : uint32_t {
    TopLeft = 0,
    TopMiddle = 1,
    TopRight = 2,
    MiddleLeft = 3,
    Center = 4,
    MiddleRight = 5,
    BottomLeft = 6,
    BottomCenter = 7,
    BottomRight = 8
};

struct Cad2DLineRecordCPU {
    uint64_t objectId = 0;
    uint64_t containerMemoryId = 0;
    double x1 = 0.0;
    double y1 = 0.0;
    double x2 = 0.0;
    double y2 = 0.0;
    float lineWeight = 0.25f;
    Cad2DLineWeightMode lineWeightMode = Cad2DLineWeightMode::PaperMM;
    uint32_t colorABGR = 0xFF000000u;
};

struct Cad2DTextRecordCPU {
    uint64_t objectId = 0;
    uint64_t containerMemoryId = 0;
    double x = 0.0;
    double y = 0.0;
    float textHeightCU = 3.5f;
    float rotationRadians = 0.0f;
    uint32_t colorABGR = 0xFF000000u;
    uint64_t font = 0; // 0 = Noto Sans MVP font
    Cad2DTextJustification justification = Cad2DTextJustification::BottomLeft;
    float xOffsetCU = 0.0f;
    float yOffsetCU = 0.0f;
    std::string text;
};

enum class CommandToCopyThread2DType : uint8_t {
    AddLine = 0,
    AddText = 1
};

struct CommandToCopyThread2D {
    CommandToCopyThread2DType type = CommandToCopyThread2DType::AddLine;
    uint64_t id = 0;
    uint64_t tabID = 0;
    uint64_t containerMemoryId = 0;
    Cad2DLineRecordCPU line;
    Cad2DTextRecordCPU text;
};

void EnqueueCad2DLine(uint64_t tabID, uint64_t containerMemoryId, Cad2DLineRecordCPU line);
void EnqueueCad2DText(uint64_t tabID, uint64_t containerMemoryId, Cad2DTextRecordCPU text);
bool HasPendingCad2DCopyCommands();
void PopAllCad2DCopyCommands(std::vector<CommandToCopyThread2D>& outCommands);

uint64_t Cad2DFindTargetPage2DMemoryId(DATASETTAB& tab);
bool Cad2DIsActivePage2D(DATASETTAB& tab);
bool Cad2DHandleInput(DATASETTAB& tab, const ACTION_DETAILS& input);
void Cad2DAutoGenerateDemoContent(DATASETTAB& tab);
