// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
#pragma once
#include <iostream>
#include <cstdint>
#include <unordered_map>
#include <array>

#include <ft2build.h>
#include FT_FREETYPE_H

#include "FontManager.h" // FreeType font atlas generation
#include "UserInterface-TextTranslations.h" // localization
#include <deque>
#include <mutex>

/*
This file is our User Inteface Design document.
Further, codes common to DirectX12 / Vulkan / Metal engines are defined in this file itself.

User Interface Design: Render the entire UI in DirectX12 itself. UI is a post-geometry overlay.
Fundamental UI Philosophy: Immediate Mode UI (initially). Late stage, Retained mode for Top Ribbons/Active forms.
Pipeline: RenderFrame(){ Render3DScene() RenderUIOverlay() Present() } This file represents UI part.
Rendering Order: Clear > Render3D > DisableDepth > EnableBlend > RenderUI > Present
UI Coordinate System : Use pixel space. Origin: (0,0) = top-left. Screen: X → right, Y → down
Orthographic matrix: float4x4 Ortho = { 2/W, 0, 0, -1, 0, -2/H, 0, 1,  0, 0, 1, 0, 0, 0, 0, 1 }
This allows vertices to be placed directly in pixels.
UI Vertex is different from 3D scene vertex because it mandatorily refers to a texture needing u/v coordinates.
Tab 0 stores common textures and UI elements.
3 primitives:
1st: Rectangles Used for buttons / backgrounds / panels / tab bar, Rendered as: 2 triangles
2nd: Text Rendered via: glyph atlas texture, 3rd: Icons, Also from texture atlas.

We will use FreeType to keep maximum cross platform code base between Windows / Linux / Mac / Android / iOS.
HarfBuzz for Unicode shaping. Initial implementation will skip this and have ASCII characters only.

At startup:
Load font file (TTF) or desired Language / Script. ( All 18 indian scheduled languages covered. )
Generate glyph bitmaps. Pack into texture atlas. Upload to GPU
Glyph packing algorithm: Skyline bin packer

Dedicated Root signature (uiRootSignature), Pipeline State Object (uiPipelineState)
Vertex shader: position → clip space, uv → pass through, color → pass through
Pixel shader: sample atlas, multiply color,
Enable: alpha blending, Blend: SrcAlpha, InvSrcAlpha

Use: DrawIndexedInstanced, No ExecuteIndirect needed. Batch everything.
When drawing text: for each character, lookup glyph, append quad

There are only 2 themes. Light and Dark. No colorful themes. System Light / Dark theme to be followed by default.
This is to facilitate color as discipline code or visually distinguishing different UI elements.
Our initial implementation will not have any Icons !
During advanced stage of development, dedicated fonts depicting the icon will be constructed.
So that same font rendering codes also generates the Icons ! No PNG embedded icon resource at all.
Initial Memory Budget: Font atlas ~4MB, Icon atlas ~2MB, Vertex buffer ~1MB, Index buffer ~256KB

UI Layout:
----------------------------------------------
| TAB BAR    4mm High           MIN-MAX-CLOSE|
--------------------1px-----------------------
| ACTION GROUP    24mm High                  |
--------------------1px-----------------------
| VIEW LIST ( Currently only 1)   4mm High   |
--------------------1px-----------------------
| I |                           |Action  | I |
| C |                           |Pane    | C |
| O |       3D VIEWPORT         |As per  | O |
| N |                           |Right   | N |
| S |                           |Buttons | S |
----------------------------------------------
| What next action user needs to take text   |
----------------------------------------------

Pixels = Millimeters * (Monitor_DPI / 25.4f)

In शंकर::InitD3DPerTab add if (tab.tabID == 0) InitUIResources(tab);
Create the atlas texture once (committed resource, DEFAULT heap).
Upload via Copy Queue exactly like geometry pages (reuse your upload ring buffer you are about to add).
Mark it published immediately and never touch again.
All text in UI shall be mandatorily any of the size : 1.5mm, 2.5mm(default), 4mm. No customizable size.

Ribbon groups will be static compile time. Left and Right side buttons will be partially static and
partially dynamical generated by engineering threads. 

Each button will have  following:
1. An integer number action ID, to signal to engineering thread what to do. 
    Action integer IDs can have gaps for future buttons.
2. 1 special "Icon" alphabet , along with a Icon size.
3. An integer string id. This string id will be localized to ~45 languages also at compile time in separate 
    localization.h file ).
4. Width & Height of Icon in pixels. This will start with default value at compile time, 
    but will be multiplied by a specific factor based on screen DPI at runtime of owning monitor.
5. 1 uint8 ZIndex to handle small drop down menu buttons. To facilitate 1 active dropdown at a time.

Definitions of ribbon tab groups shall be different from basic button list. 
Such that user could add the same buttons at different locations. Example apart from main location in ribbon, 
a button could also be added to Quick Favorite bar / button list in the right side of screen pane.

All UI strings are compile time assigned an immutable uint32 ID to translation vsv file.
Each language get's its own translation csv file. Ex:
UserInterfaceTranslation_<2 digit language code>_languageName.csv

WorldID, ShortWordName, English, Human, Comments, ChatGPT, Gemini, Grok, Claude  
1, Home, Home, Home Button, Home Button, Home Button, Home Button, Home Button, Home Button
2, Copy, Copy, Copy Button, Copy Button, Copy Button, Copy Button, Copy Button, Copy Button
3, Edit, Edit, Edit Button, Edit Button, Edit Button, Edit Button, Edit Button, Edit Button
4, Draw, Draw, Draw Button, Draw Button, Draw Button, Draw Button, Draw Button, Draw Button
5, Erase, Erase, Erase Button, Erase Button, Erase Button, Erase Button, Erase Button, Erase Button
6, Close, Close, Close Button, Close Button, Close Button, Close Button, Close(Button), Close(Button)
 
Corresponding statically compiled translated header need to be generated as part of build process.
This CSV to .h translation will happen using a python script named UserInterfaceTranslationCompiler.py file. 
All of the csv, .py and .h/.cpp shall be checked into git. Compiled code will produce following 2 files only.
They will represent all languages.
 
UserInterfaceTranslationCompiled.h
UserInterfaceTranslationCompiled.cpp
 
C++ code will provide a simple function to return string for corresponding integer string ID.
All unique alphabet combination shall be rendered in a single texture atlas and handed over 2D buffer
    for uploading to GPU by UI handling code.
This texture preparation shall happen at the beginning of application launch in an async thread.
Till the time this thread completes its texture atlas preparation, UI handler code will keep displaying a blank space.
For string which have a missing translation corresponding English word shall be displayed. At a time,
texture atlas of only 1 language shall be active.
The font files will come from byte steam already loaded by other part of code from embedded Resource.
 
Initial translation shall be performed by AI translator file named UserInterfaceTranslationByAI.py

-- Phased Rollout ( Phase 4 checklist) --

Phase 4A – Tab Bar only (1–2 days)
Hard-coded tab names from publishedTabIndexes.
Colored rects + simple text (even without atlas yet — use dummy color quads).
Clicking changes activeTabIndex and triggers re-render.

Phase 4B – Font Atlas + Text (next)
Add stb_truetype or FreeType atlas.
Render real tab labels + button text.

Phase 4C – Ribbon Bar
8–10 buttons with rect + text (icons later).
Click handlers queue actions to the active tab’s engineering thread.

Phase 4D – Icons & Polish
Custom Font for Icons.
Hover glow, pressed state, tooltips (delayed text draw).

Future: regenerate atlas on WM_DPICHANGED
Far Future:
Translator / AI edits: Hindi.csv, German.csv, Tamil.csv
Build step runs: generate_ui_text_table.py
Script generates: UserInterface-Text.generated.h
Compiler builds: static constexpr translation tables
Runtime: no file loading, no parsing, pure compile-time arrays
*/

// UI Layout Constants (millimeters)
constexpr float UI_TEXT_HEIGHT_MM = 2.5f; // EIL's recommended text hight for printed drawing is 2.5mm.
// Perhaps this is also good for UI text to maintain consistency between printed and on-screen drawings.
// TODO: Latter, we will allow user to customize text height from settings.
constexpr float UI_TAB_BAR_HEIGHT_MM = 4.0f;
constexpr float UI_ACTION_GROUP_LABEL_HEIGHT_MM = 4.0f;
constexpr float UI_ACTION_GROUP_HEIGHT_MM = 12.0f; // Divisible by 2/3/4
constexpr float UI_VIEWLIST_HEIGHT_MM = 4.0f;
constexpr float UI_DIVIDER_GAP_PX = 1.0f;
constexpr float UI_BUTTON_HEIGHT_MM = 3.0f; // Text is 2.5mm.
constexpr float UI_BUTTON_WIDTH_MM = 8.0f;
constexpr float UI_BUTTON_GAP_MM = 1.0f;
constexpr float UI_ICON_SIZE_MM = 4.0f;
constexpr float UI_GROUP_GAP_MM = 5.0f; // We would rather keep it 2 pixel fixed width.
constexpr float UI_BUTTON_CORNER_RADIUS_MM = 2.0f;

constexpr uint32_t UI_MAX_ATLAS_TEXTURES = 10;
constexpr uint32_t UI_ENGLISH_ATLAS_SLOT = 0;
constexpr uint32_t UI_ICON_ATLAS_SLOT = 1;
constexpr uint32_t UI_FIRST_DYNAMIC_SCRIPT_ATLAS_SLOT = 2;

// Colors (ABGR)
constexpr uint32_t COLOR_UI_TAB_ACTIVE = 0xFF2D2D30;
constexpr uint32_t COLOR_UI_TAB_INACTIVE = 0xFF3E3E42;

struct UIVertex {// Vertex format
    float x, y, u, v;
    uint32_t color; // ABGR format for DX12 standard
    uint32_t atlasIndex; // Index into the UI SRV atlas array. 0 = English, 1 = icons/shape coverage.
};

struct Glyph { // Store glyph info: Glyph metadata (Phase 4B)
    float uvMinX, uvMinY, uvMaxX, uvMaxY; // Normalized UV coordinates in the atlas (0.0 to 1.0)
    int width, height; // Pixel dimensions for drawing the quad
    int bearingX, bearingY; // Positional offsets (Crucial for baseline alignment)
    int advanceX;
};

// Use char32_t for full UTF-32 Unicode support (necessary for all languages)
inline std::unordered_map<char32_t, Glyph> glyphLookup; // Lookup table.
inline std::unordered_map<char32_t, Glyph> iconGlyphLookup; // Private-use codepoints for monochrome UI icons.
extern std::string charset;

struct AtlasBitmap {
    int width;
    int height;
    std::vector<uint8_t> pixels; // 1 channel (R8)
};

inline AtlasBitmap BuildFontAtlas() {
    const int atlasW = 512;
    const int atlasH = 512;

    AtlasBitmap atlas;
    atlas.width = atlasW;
    atlas.height = atlasH;
    atlas.pixels.resize(atlasW * atlasH, 0);

    int penX = 0;
    int penY = 0;
    int rowHeight = 0;

    for (char c : charset)
    {
        if (FT_Load_Char(ftFace, c, FT_LOAD_RENDER)) continue;

        FT_GlyphSlot g = ftFace->glyph;

        if (penX + g->bitmap.width >= atlasW) {
            penX = 0;
            penY += rowHeight;
            rowHeight = 0;
        }

        // Copy bitmap
        for (int y = 0; y < g->bitmap.rows; y++) {
            for (int x = 0; x < g->bitmap.width; x++) {
                int dst = (penY + y) * atlasW + (penX + x);
                atlas.pixels[dst] = g->bitmap.buffer[y * g->bitmap.pitch + x];
            }
        }

        // Store glyph metadata
        Glyph glyph{};
        glyph.uvMinX = (float)penX / atlasW;
        glyph.uvMinY = (float)penY / atlasH;
        glyph.uvMaxX = (float)(penX + g->bitmap.width) / atlasW;
        glyph.uvMaxY = (float)(penY + g->bitmap.rows) / atlasH;

        glyph.width = g->bitmap.width;
        glyph.height = g->bitmap.rows;
        glyph.bearingX = g->bitmap_left;
        glyph.bearingY = g->bitmap_top;
        glyph.advanceX = g->advance.x >> 6;

        glyphLookup[c] = glyph;

        penX += g->bitmap.width + 1;
        int glyphHeight = (int)g->bitmap.rows;
        if (glyphHeight > rowHeight) { rowHeight = glyphHeight; }
    }

    return atlas;
}

struct UIButton { // UI Button abstraction
    uint32_t id; // Unique hash for immediate mode tracking
    //RECT physicalRect; // Calculated dynamically based on DPI
    const wchar_t* label; // UTF-32 string for HarfBuzz
    int iconIndex; // -1 = no icon, else index into sprite sheet
    char32_t iconCodePoint;// The Unicode point for custom icon font
    bool enabled;
};

struct UITabBarState { // Tab bar state
    int hoveredTab = -1;
    int activeTab; // copied from window.activeTabIndex
};

struct UIInput {
    // Mouse position in client pixels (top-left origin). Float for consistent math with UI layout.
    float mouseX = 0.0f, mouseY = 0.0f;
    // Persistent button state
    bool leftButtonDown = false, rightButtonDown = false, middleButtonDown = false;
    // Rising/falling edge for this exact frame (used by immediate-mode hit-testing)
    bool leftButtonPressedThisFrame = false,  leftButtonReleasedThisFrame = false;
    bool rightButtonPressedThisFrame = false, middleButtonPressedThisFrame = false;
    int mouseWheelDelta = 0;          // WM_MOUSEWHEEL
    // Modifiers — per-window snapshot (synced with GetAsyncKeyState in WndProc)
    bool shiftDown = false, ctrlDown = false, altDown = false;

    // Text input buffer for future text fields / search boxes (WM_CHAR)
    char32_t textInputThisFrame[32] = {};
    uint8_t  textInputCount = 0; // 0–31 chars this frame. We discard key inputs if we are unable to process.

    // Optional hotkey raw keys this frame (can be added later as a small bitset)
};

struct UIColors { // Standard UI Colours (ABGR format for DX12)
    // The default values specified here are for theme "Light". 
    // These can be overridden by other themes (e.g. Dark) or by user customizations.
    uint32_t tabBackground = 0xFFD4E5DD; //rgba(221, 229, 212)
    uint32_t tabBackgroundText = 0xFF4E6254; //rgba(84, 98, 78) + Corner smoothening color?
    //tabActive is also the background color of action group surrounding.
    uint32_t tabActive = 0xFFF1FBF8; //rgba(248, 251, 241)
    uint32_t tabActiveText = 0xFF171D19; //rgba(25, 29, 23)
    uint32_t tabBackgroundHover = 0xFFC4D5CD; // 1 Shade darker than tabBackground.

    uint32_t actionGroupBackground = 0xFFFFFFFF;
    uint32_t actionGroupSeperator = 0xFFD1D1D1; //rgba(209, 209, 209)
    uint32_t actionGroupHoverBackground = 0xFFFF9933; // Orange in Indian Flag
    uint32_t actionText = 0xFF242424; //rgba(36, 36, 36) + Corner smoothening color?
    //Action icon color is stored inside the button itself. Different icons = different colors.
    uint32_t actionIconDisabled = 0xFF888888; //rgba(136, 136, 136)	
};


// Thread-safe push (lock-free ring buffer style – reuse your MemoryManagerGPU ring buffer idea)
extern std::atomic<uint32_t> actionWriteIndex;
constexpr uint32_t ACTION_RING_SIZE = 4096;
// Simpler thread-safe queue for UI -> Engine actions (protected by mutex)
struct UIActionEntry {
    uint32_t id;
    uint32_t p1;
    uint32_t p2;
};

//TODO: WARNING: Get rid of mutex and use lock-free multi producer single consumer ring buffer for this.
extern std::mutex g_actionQueueMutex;
extern std::deque<UIActionEntry> g_actionQueue;

// Call from UI thread: push an action into the global action queue
inline void PushUIAction(uint32_t id, uint32_t p1 = 0, uint32_t p2 = 0) {
    std::lock_guard<std::mutex> lk(g_actionQueueMutex);
    g_actionQueue.push_back({ id, p1, p2 });
    // actionRing[idx] = { id, p1, p2, /*timestamp*/ };
    // Engineering thread reads with its own readIndex (standard ring-buffer)
}

// These are exhausting list of identified action user can perform in our application.
// These actions can be triggered either by clicking buttons, or thorough automation scripts etc.
enum class UIAction : uint32_t {

    //Action Group 1: Common
    PROJECT_OPEN = 0x00002005,
    PROJECT_SAVE = 0x00002006,
    PROJECT_CLOSE = 0x00002007,

    VIEW_TREE = 0x00004003,
    VIEW_PERSPECTIVE_ISO_DROPDOWN = 0x00004004,   // Dropdown trigger
    VIEW_MAX_ZOOM = 0x00004005,
    VIEW_ROTATE = 0x00004006,
    VIEW_PAN = 0x00004007,

    SELECT_GENERAL = 0x00005003,
    SELECT_PIPES = 0x00005004,
    SELECT_FITTINGS = 0x00005005,
    SELECT_REINFORCEMENT = 0x00005006,
    SELECT_2D_ONLY = 0x00005007,
    SELECT_TEXT = 0x00005008,
    SELECT_LINES = 0x00005009,

    //Action Group 2: (2D) General
    CREATE_LINE = 0x00006001,
    CREATE_POLYLINE = 0x00006002,
    CREATE_CIRCLE = 0x00006003,
    CREATE_ARC = 0x00006004,
    CREATE_ELLIPSE = 0x00006005,
    CREATE_TEXT = 0x00006006,
    CREATE_MULTITEXT = 0x00006007,

    EDIT_COPY = 0x00006008,
    EDIT_OFFSET = 0x00006009,
    EDIT_MOVE = 0x00006010,

    //Action Group 3: "(2D) P&ID"
    CREATE_VVESSEL = 0x00007001,
    CREATE_HVESSEL = 0x00007002,
    CREATE_EXCHANGE = 0x00007003,
    CREATE_PIPE = 0x00007004,
    CREATE_INSTRUMENT = 0x00007005,
    EDIT_PARAMETER = 0x00007006,

    //Action Group 4: (3D) General
    CREATE_FOLDER = 0x00008001,
    CREATE_GRID = 0x00008002,
    CREATE_STRUCTURE = 0x00008003,
    CREATE_LINES_3D = 0x00008004,
    CONCRETE_COLUMN = 0x00008005,
    CONCRETE_BEAM = 0x00008006,
    CONCRETE_SLAB = 0x00008007,
    CONCRETE_CURVED_SLAB = 0x00008008,
    CONCRETE_DOME = 0x00008009,
    CONCRETE_PILE = 0x00008010,
    REINFORCEMENT_LINEAR = 0x00008011,
    REINFORCEMENT_SHAPED_DROPDOWN = 0x00008012,   // Dropdown trigger
    STEEL_COLUMN = 0x00008013,
    STEEL_BEAM = 0x00008014,
    FRP_COLUMN = 0x00008015,
    FRP_BEAM = 0x00008016,
    GLASS_PLATE = 0x00008017,

    //Action Group 5: (3D) Equipment
    EQUIPMENT_VVESSEL = 0x00009001,
    EQUIPMENT_HVESSEL = 0x00009002,
    EQUIPMENT_EXCHANGER = 0x00009003,
    EQUIPMENT_PUMP = 0x00009004,

    //Action Group 6: (3D) Piping
    CREATE_PIPING = 0x0000A001,
    CREATE_SPOOL = 0x0000A002,
    CREATE_VALVE = 0x0000A003,
    CREATE_ELBOW = 0x0000A004,
    CREATE_T = 0x0000A005,
    CREATE_Y = 0x0000A006,
    INSTRUMENT_PG = 0x0000A007,
    INSTRUMENT_TG = 0x0000A008,
    EDIT_EXTEND = 0x0000A009,
    EDIT_STRETCH = 0x0000A010,

    //Action Group 7: Analysis and Simulation
    LOAD_CASE = 0x0000B001,
    LOAD_COMBINATIONS = 0x0000B002,
    LOAD_SELF_WEIGHT = 0x0000B003,
    LOAD_UNIFORM = 0x0000B004,
    LOAD_TRAPEZOIDAL = 0x0000B005,
    LOAD_PRESSURE = 0x0000B006,
    LOAD_TEMPERATURE = 0x0000B007,

    SUPPORT_FIXED = 0x0000B008,
    SUPPORT_PINNED = 0x0000B009,
    SUPPORT_ROLLER = 0x0000B010,

    ANALYSIS_3D_FRAME = 0x0000B011,
    ANALYSIS_STATIC = 0x0000B012,
    ANALYSIS_SPECTRUM = 0x0000B013,
    ANALYSIS_TIME_HISTORY = 0x0000B014,

    //Action Group 8: Code Checking
    CODE_CIVIL_IS456 = 0x0000C001,
    CODE_CIVIL_IS13920 = 0x0000C002,
    CODE_CIVIL_IS800 = 0x0000C003,
    CODE_MECH_ASME_VIII = 0x0000C004,

    //Action Group 9: 3D to 2D
    GENERAL_DRAWING = 0x0000D001,
    GENERAL_SHEET = 0x0000D002,
    GENERAL_3D2DGA = 0x0000D003,
    GENERAL_ASSEMBLY = 0x0000D004,
    GENERAL_ISOMETRIC = 0x0000D005,
    GENERAL_TABLES = 0x0000D006,

    //Action Group 10: (4D) Time
    // 0x0000E000 series reserved for this.
    
    //Action Group 11: (5D) Cost
    // 0x0000F000 series reserved for this.
    
    //Action Group 12: Interoperability
    IMPORT_STD = 0x00010001,
    IMPORT_CII = 0x00010002,
    IMPORT_DXF = 0x00010003,
    IMPORT_DWG = 0x00010004,
    EXPORT_STD = 0x00010005,
    EXPORT_DWG = 0x00010006,

    //Action Group 13: Extensions
    
    // Add more future actions here with gaps if needed (e.g. 0x0000E000+)

    INVALID = 0xFFFFFFFF
};

struct UIControlDefinition {
	UIAction     action;           // Action ID sent to engineering thread, upon clicking this control. 
    // This is the single source of truth for all buttons, dropdowns, text fields etc.
    uint32_t     nameStringID;     // Localization ID (hardcoded for now) of the TEXT.
    char32_t     iconChar;         // Future icon font codepoint (use 'x' for now)
    uint8_t      type;             // 0=PlainText, 1=Button, 2=Dropdown trigger, 3=Textbox
    uint8_t      noOfVerticalSlots;// 1 = full height, 2/3/4 = vertical stack height
    uint8_t      verticalSlotNo;   // 0-based position inside the vertical stack
    uint8_t      zIndex;           // 0=normal, 1=dropdown trigger, 2=dropdown item
    bool         showText;         // true = show label, false = icon only
    bool         isEnabled;        // true = show this button/label etc, false = gray out this.
    uint8_t      actionGroupIndex; // 0-based index in array of UIActionGroupName for Text reference.
    uint8_t      actionSubGroupIndex; // Localization ID (hardcoded for now) of the TEXT.
};

// Action Groups are basically a set of User Control Buttons.
// This struct will be used to group buttons by top Menus, and specialized property panes in the right side.
struct UIActionGroupNames {
    uint32_t labelStringID;     // e.g. 11 = "Common"
    bool isEnabled;             // User may switch off any action groups.
    bool isMinimized;           // Used in right side property panes.
};


constexpr UIActionGroupNames topUIActionGroupNames[] = {
	// Initially marking all action group enabled, and non-minimized. User can change this at runtime.
    { 11 , true , false }, // ACTION GROUP  1: Common
    { 12 , true , false }, // ACTION GROUP  2: (2D) General
    { 13 , true , false }, // ACTION GROUP  3: (2D) Intelligent
    { 14 , true , false }, // ACTION GROUP  4: (3D) General
    { 15 , true , false }, // ACTION GROUP  5: (3D) Intelligent
    { 16 , true , false }, // ACTION GROUP  6: (3D) Simulation
    { 17 , true , false }, // ACTION GROUP  7: Design Codes
    { 18 , true , false }, // ACTION GROUP  8: Documentation
    { 19 , true , false }, // ACTION GROUP  9: 3D to 2D
    { 20 , true , false }, // ACTION GROUP 10: (4D) Time
    { 21 , true , false }, // ACTION GROUP 11: (5D) Cost
    { 22 , true , false }, // ACTION GROUP 12: Interoperability & Miscellaneous
    { 23 , true , false }, // ACTION GROUP 13: Extensions
};
constexpr size_t TotalTopUIActionGroups = std::size(topUIActionGroupNames);

// Initially I wanted to discard the idea of sub-grouping the buttons within each action groups.
// However, realized that during training / support discussion we usually need to explain the user,
// To go to specific group and specific sub group. So it remains for training & quick onboarding purpose. 

constexpr UIActionGroupNames topUIActionSubGroupNames[] = {
    // Initially marking all action sub group enabled, and non-minimized. User can change this at runtime.
    { 51 , true , false }, 
    { 52 , true , false }, 
    { 53 , true , false }, 
    { 54 , true , false }, 
    { 55 , true , false }, 
    { 56 , true , false }, 
    { 57 , true , false }, 
    { 58 , true , false }, 
    { 59 , true , false }, 
    { 60 , true , false }, 
    { 61 , true , false }, 
    { 62 , true , false }, 
    { 63 , true , false }, 
    { 65 , true , false }, 
    { 66 , true , false },
    { 67 , true , false },
    { 68 , true , false },
    { 69 , true , false },
    { 70 , true , false },
};
constexpr size_t TotalTopUIActionSubGroups = std::size(topUIActionSubGroupNames);

// COMPILE-TIME GIANT ARRAY . Lists ALL top primary buttons (excliding right side pane) available in application.
// This is the single source of truth. ~80+ controls shown here. we can extend to 500+ easily.

constexpr UIControlDefinition AllUIControls[] = {
    // ACTION GROUP 11: Common
    // Subgroup : Project Organization
    { UIAction::PROJECT_OPEN,          1001, U'x', 1, 3, 0, 0, true, false, 0 , 0 },
    { UIAction::PROJECT_SAVE,          1003, U'x', 1, 3, 1, 0, true, false, 0 , 0 },
    { UIAction::PROJECT_CLOSE,         1005, U'x', 1, 3, 2, 0, true, false, 0 , 0 },

    // Subgroup : View
    { UIAction::VIEW_TREE,             1007, U'x', 1, 2, 0, 0, true, false, 0 , 1 },
    { UIAction::VIEW_PERSPECTIVE_ISO_DROPDOWN, 1009, U'x', 2, 2, 1, 1, true, false, 0 , 1 }, // Dropdown
    { UIAction::VIEW_MAX_ZOOM,         1011, U'x', 1, 3, 0, 0, true, false, 0 , 1 },
    { UIAction::VIEW_ROTATE,           1013, U'x', 1, 3, 1, 0, true, false, 0 , 1 },
    { UIAction::VIEW_PAN,              1015, U'x', 1, 3, 2, 0, true, false, 0 , 1 },
    // Subgroup : Select
    { UIAction::SELECT_GENERAL,        1017, U'x', 1, 1, 0, 0, true, false, 0 , 2 },
    { UIAction::SELECT_PIPES,          1019, U'x', 1, 3, 0, 0, true, false, 0 , 2 },
    { UIAction::SELECT_FITTINGS,       1021, U'x', 1, 3, 1, 0, true, false, 0 , 2 },
    { UIAction::SELECT_REINFORCEMENT,  99, U'x', 1, 3, 2, 0, true, false, 0 , 2 },
    { UIAction::SELECT_2D_ONLY,        99, U'x', 1, 3, 0, 0, true, false, 0 , 2 },
    { UIAction::SELECT_TEXT,           99, U'x', 1, 3, 1, 0, true, false, 0 , 2 },
    { UIAction::SELECT_LINES,          99, U'x', 1, 3, 2, 0, true, false, 0 , 2 }, 
    // ACTION GROUP 12: (2D) General
    // Subgroup : Create 2D Shapes
    { UIAction::CREATE_LINE,           1023, U'x', 1, 2, 0, 0, true, false, 1 , 4 },
    { UIAction::CREATE_POLYLINE,       1025, U'x', 1, 2, 1, 0, true, false, 1 , 4 },
    { UIAction::CREATE_CIRCLE,         1027, U'x', 1, 3, 0, 0, true, false, 1 , 4 },
    { UIAction::CREATE_ARC,            1029, U'x', 1, 3, 1, 0, true, false, 1 , 4 },
    { UIAction::CREATE_ELLIPSE,        99, U'x', 1, 3, 2, 0, true, false, 1 , 4 },
    { UIAction::CREATE_TEXT,           99, U'x', 1, 2, 0, 0, true, false, 1 , 4 },
    { UIAction::CREATE_MULTITEXT,      99, U'x', 1, 2, 1, 0, true, false, 1 , 4 },

    // SubGroup: Edit
    { UIAction::EDIT_COPY,             12, U'x', 1, 3, 0, 0, true, false, 1 , 5 },
    { UIAction::EDIT_OFFSET,           12, U'x', 1, 3, 1, 0, true, false, 1 , 5 },
    { UIAction::EDIT_MOVE,             12, U'x', 1, 3, 2, 0, true, false, 1 , 5 },

    // ACTION GROUP 13: (2D) Advanced
    // Subgroup : Process Equipments
    { UIAction::CREATE_VVESSEL,        13, U'x', 1, 3, 0, 0, true, false, 2 , 5 },
    { UIAction::CREATE_HVESSEL,        13, U'x', 1, 3, 1, 0, true, false, 2 , 5 },
    { UIAction::CREATE_EXCHANGE,       13, U'x', 1, 3, 2, 0, true, false, 2 , 5 },
    { UIAction::CREATE_PIPE,           13, U'x', 1, 3, 0, 0, true, false, 2 , 5 },
    { UIAction::CREATE_INSTRUMENT,     13, U'x', 1, 3, 1, 0, true, false, 2 , 5 },
    { UIAction::EDIT_PARAMETER,        13, U'x', 1, 3, 2, 0, true, false, 2 , 5 },

    // ACTION GROUP 14: (3D)
    // Subgroup : Basic
    { UIAction::CREATE_FOLDER,         1031, U'x', 1, 2, 0, 0, true, false, 3 , 6 },
    { UIAction::CREATE_GRID,           1033, U'x', 1, 2, 1, 0, true, false, 3 , 6 },
    { UIAction::CREATE_STRUCTURE,      1035, U'x', 1, 2, 0, 0, true, false, 3 , 6 },
    { UIAction::CREATE_LINES_3D,       1037, U'x', 1, 2, 1, 0, true, false, 3 , 6 },

    // ACTION GROUP 15: (3D) Intelligent
    // Subgroup : Concrete
    { UIAction::CONCRETE_COLUMN,       99, U'x', 1, 3, 0, 0, true, false, 4 , 7 },
    { UIAction::CONCRETE_BEAM,         99, U'x', 1, 3, 1, 0, true, false, 4 , 7 },
    { UIAction::CONCRETE_SLAB,         99, U'x', 1, 3, 2, 0, true, false, 4 , 7 },
    { UIAction::CONCRETE_CURVED_SLAB,  99, U'x', 1, 3, 0, 0, true, false, 4 , 7 },
    { UIAction::CONCRETE_DOME,         99, U'x', 1, 3, 1, 0, true, false, 4 , 7 },
    { UIAction::CONCRETE_PILE,         99, U'x', 1, 3, 2, 0, true, false, 4 , 7 },
    // Subgroup : Reinforcement
    { UIAction::REINFORCEMENT_LINEAR,  99, U'x', 1, 2, 0, 0, true, false, 4 , 8 },
    { UIAction::REINFORCEMENT_SHAPED_DROPDOWN, 99, U'x', 2, 2, 1, 1, true, false, 4 , 8 },

    // Subgroup : Steel, FRP, Glass
    { UIAction::STEEL_COLUMN,          99, U'x', 1, 2, 0, 0, true, false, 4 , 5 },
    { UIAction::STEEL_BEAM,            99, U'x', 1, 2, 0, 0, true, false, 4 , 5 },
    { UIAction::FRP_COLUMN,            99, U'x', 1, 3, 0, 0, true, false, 4 , 5 },
    { UIAction::FRP_BEAM,              99, U'x', 1, 3, 1, 0, true, false, 4 , 5 },
    { UIAction::GLASS_PLATE,           99, U'x', 1, 3, 2, 0, true, false, 4 , 5 },

    // Subgroup : Equipments
    { UIAction::EQUIPMENT_VVESSEL,     99, U'x', 1, 3, 0, 0, true, false, 4 , 6 },
    { UIAction::EQUIPMENT_HVESSEL,     99, U'x', 1, 3, 1, 0, true, false, 4 , 6 },
    { UIAction::EQUIPMENT_EXCHANGER,   99, U'x', 1, 3, 2, 0, true, false, 4 , 6 },
    { UIAction::EQUIPMENT_PUMP,        99, U'x', 1, 3, 0, 0, true, false, 4 , 6 },

    // Subgroup : Piping
    { UIAction::CREATE_PIPING,         99, U'x', 1, 3, 0, 0, true, false, 4 , 7 },
    { UIAction::CREATE_SPOOL,          99, U'x', 1, 3, 1, 0, true, false, 4 , 7 },
    { UIAction::CREATE_VALVE,          99, U'x', 1, 3, 2, 0, true, false, 4 , 7 },
    { UIAction::CREATE_ELBOW,          99, U'x', 1, 3, 0, 0, true, false, 4 , 7 },
    { UIAction::CREATE_T,              99, U'x', 1, 3, 1, 0, true, false, 4 , 7 },
    { UIAction::CREATE_Y,              99, U'x', 1, 3, 2, 0, true, false, 4 , 7 },
    { UIAction::INSTRUMENT_PG,         99, U'x', 1, 3, 0, 0, true, false, 4 , 7 },
    { UIAction::INSTRUMENT_TG,         99, U'x', 1, 3, 1, 0, true, false, 4 , 7 },
    { UIAction::EDIT_EXTEND,           99, U'x', 1, 3, 2, 0, true, false, 4 , 7 },
    { UIAction::EDIT_STRETCH,          99, U'x', 1, 3, 0, 0, true, false, 4 , 7 },

	// ACTION GROUP 16: Simulation and Analysis
    // Subgroup : Loads & Combinations
    { UIAction::LOAD_CASE,             99, U'x', 1, 3, 0, 0, true, false, 5 , 8 },
    { UIAction::LOAD_COMBINATIONS,     99, U'x', 1, 3, 1, 0, true, false, 5 , 8 },
    { UIAction::LOAD_SELF_WEIGHT,      99, U'x', 1, 3, 2, 0, true, false, 5 , 8 },
    { UIAction::LOAD_UNIFORM,          99, U'x', 1, 3, 0, 0, true, false, 5 , 8 },
    { UIAction::LOAD_TRAPEZOIDAL,      99, U'x', 1, 3, 1, 0, true, false, 5 , 8 },
    { UIAction::LOAD_PRESSURE,         99, U'x', 1, 3, 2, 0, true, false, 5 , 8 },
    { UIAction::LOAD_TEMPERATURE,      99, U'x', 1, 3, 0, 0, true, false, 5 , 8 },
    // Subgroup : Supports
    { UIAction::SUPPORT_FIXED,         99, U'x', 1, 3, 0, 0, true, false, 5 , 9 },
    { UIAction::SUPPORT_PINNED,        99, U'x', 1, 3, 1, 0, true, false, 5 , 9 },
    { UIAction::SUPPORT_ROLLER,        99, U'x', 1, 3, 2, 0, true, false, 5 , 9 },

	// Subgroup : Analysis Types
    { UIAction::ANALYSIS_3D_FRAME,     99, U'x', 1, 3, 0, 0, true, false, 5 , 10 },
    { UIAction::ANALYSIS_STATIC,       99, U'x', 1, 3, 1, 0, true, false, 5 , 10 },
    { UIAction::ANALYSIS_SPECTRUM,     99, U'x', 1, 3, 2, 0, true, false, 5 , 10 },
    { UIAction::ANALYSIS_TIME_HISTORY, 99, U'x', 1, 3, 0, 0, true, false, 5 , 10 },

    // ACTION GROUP 17: Code Checking
	// Subgroup : Indian (BIS)
    { UIAction::CODE_CIVIL_IS456,      99, U'x', 1, 3, 0, 0, true, false, 6 , 11 },
    { UIAction::CODE_CIVIL_IS13920,    99, U'x', 1, 3, 1, 0, true, false, 6 , 11 },
    { UIAction::CODE_CIVIL_IS800,      99, U'x', 1, 3, 2, 0, true, false, 6 , 11 },

    // Subgroup : ASME
    { UIAction::CODE_MECH_ASME_VIII,   99, U'x', 1, 3, 0, 0, true, false, 6 , 12 },

    // ACTION GROUP 18: Documentation
        
    // ACTION GROUP 19: 3D->2D
    // Subgroup : Drawing Extraction
    { UIAction::GENERAL_DRAWING,       19, U'x', 1, 3, 0, 0, true, false, 8 , 13 },
    { UIAction::GENERAL_SHEET,         19, U'x', 1, 3, 1, 0, true, false, 8 , 13 },
    { UIAction::GENERAL_3D2DGA,        19, U'x', 1, 3, 2, 0, true, false, 8 , 13 },
    { UIAction::GENERAL_ASSEMBLY,      19, U'x', 1, 3, 0, 0, true, false, 8 , 13 },
    { UIAction::GENERAL_ISOMETRIC,     19, U'x', 1, 3, 1, 0, true, false, 8 , 13 },
    { UIAction::GENERAL_TABLES,        19, U'x', 1, 3, 2, 0, true, false, 8 , 13 },

    // ACTION GROUP 20: Time
    // ACTION GROUP 21: Cost

    // ACTION GROUP 22: Interoperability & Miscellaneous.
	// Subgroup : Import & Export
    { UIAction::IMPORT_STD,            1045, U'x', 1, 3, 0, 0, true, false, 11 , 14 },
    { UIAction::IMPORT_CII,            1047, U'x', 1, 3, 1, 0, true, false, 11 , 14 },
    { UIAction::IMPORT_DXF,            1049, U'x', 1, 3, 2, 0, true, false, 11 , 14 },
    { UIAction::IMPORT_DWG,            1051, U'x', 1, 3, 0, 0, true, false, 11 , 14 },
    { UIAction::EXPORT_STD,            1053, U'x', 1, 3, 1, 0, true, false, 11 , 14 },
    { UIAction::EXPORT_DWG,            1055, U'x', 1, 3, 2, 0, true, false, 11 , 14 },
    // ACTION GROUP 23: Extensions
	// Subgroup : All Active Extensions (This will be dynamic in future, but we can hardcode few for now)
    { UIAction::CODE_CIVIL_IS456,      99, U'x', 1, 1, 0, 0, true, false, 12 , 15 }
};

constexpr size_t TotalUIControls = std::size(AllUIControls);
