// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
#pragma once
#include <cstdint>
#include <unordered_map>

#include <array>
#include "UserInterface-TextTranslations.h"   // localization

/*
This file is our User Inteface Design document.
Further, codes common to DirectX12 / Vulkan / Metal engines are defined in this file itself.

User Interface Design: Render the entire UI in DirectX12 itself. UI is a post-geometry overlay.
Fundamental UI Philosophy: Immediate Mode UI (initially). Late stage, Retained mode for Top Ribbons/Active forms.
Pipeline: RenderFrame(){ Render3DScene() RenderUIOverlay() Present() } This file represents UI part.
Rendering Order: Clear > Render3D > DisableDepth > EnableBlend > RenderUI > Present
UI Coordinate System : Use pixel space. Origin: (0,0) = top-left. Screen: X → right, Y → down
Orthographic matrix: float4x4 Ortho = { 2/W, 0, 0, -1, 0, -2/H, 0, 1,  0, 0, 1, 0, 0, 0, 0, 1 }
This allows vertices to be placed directly in pixels.
UI Vertex is different from 3D scene vertex because it mandatorily refers to a texture needing u/v coordinates.
Tab 0 stores common textures and UI elements.
3 primitives:
1st: Rectangles Used for buttons / backgrounds / panels / tab bar, Rendered as: 2 triangles
2nd: Text Rendered via: glyph atlas texture, 3rd: Icons, Also from texture atlas.

We will use FreeType to keep maximum cross platform code base between Windows / Linux / Mac / Android / iOS.
HarfBuzz for Unicode shaping. Initial implementation will skip this and have ASCII characters only.

At startup:
Load font file (TTF) or desired Language / Script. ( All 18 indian scheduled languages covered. )
Generate glyph bitmaps. Pack into texture atlas. Upload to GPU
Glyph packing algorithm: Skyline bin packer

Dedicated Root signature (uiRootSignature), Pipeline State Object (uiPipelineState)
Vertex shader: position → clip space, uv → pass through, color → pass through
Pixel shader: sample atlas, multiply color,
Enable: alpha blending, Blend: SrcAlpha, InvSrcAlpha

Use: DrawIndexedInstanced, No ExecuteIndirect needed. Batch everything.
When drawing text: for each character, lookup glyph, append quad

There are only 2 themes. Light and Dark. No colorful themes. System Light / Dark theme to be followed by default.
This is to facilitate color as discipline code or visually distinguishing different UI elements.
Our initial implementation will not have any Icons !
During advanced stage of development, dedicated fonts depicting the icon will be constructed.
So that same font rendering codes also generates the Icons ! No PNG embedded icon resource at all.
Initial Memory Budget: Font atlas ~4MB, Icon atlas ~2MB, Vertex buffer ~1MB, Index buffer ~256KB

UI Layout:
----------------------------------------------
| TAB BAR    4mm High           MIN-MAX-CLOSE|
--------------------1px-----------------------
| RIBBON    20mm High                        |
--------------------1px-----------------------
| VIEW LIST ( Currently only 1)   4mm High   |
--------------------1px-----------------------
| I |                           |Action  | I |
| C |                           |Pane    | C |
| O |       3D VIEWPORT         |As per  | O |
| N |                           |Right   | N |
| S |                           |Buttons | S |
----------------------------------------------
| What next action user needs to take text   |
----------------------------------------------

Pixels = Millimeters * (Monitor_DPI / 25.4f)

In शंकर::InitD3DPerTab add if (tab.tabID == 0) InitUIResources(tab);
Create the atlas texture once (committed resource, DEFAULT heap).
Upload via Copy Queue exactly like geometry pages (reuse your upload ring buffer you are about to add).
Mark it published immediately and never touch again.
All text in UI shall be mandatorily any of the size : 1.5mm, 2.5mm(default), 4mm. No customizable size.

Ribbon groups will be static compile time. Left and Right side buttons will be partially static and
partially dynamical generated by engineering threads. 

Each button will have  following:
1. An integer number action ID, to signal to engineering thread what to do. 
    Action integer IDs can have gaps for future buttons.
2. 1 special "Icon" alphabet , along with a Icon size.
3. An integer string id. This string id will be localized to ~45 languages also at compile time in separate 
    localization.h file ).
4. Width & Height of Icon in pixels. This will start with default value at compile time, 
    but will be multiplied by a specific factor based on screen DPI at runtime of owning monitor.
5. 1 uint8 ZIndex to handle small drop down menu buttons. To fasciliate 1 active dropdown at a time.

Definitions of ribbon tab groups shall be different from basic button list. 
Such that user could add the same buttons at different locations. Example apart from main location in ribbon, 
a button could also be added to Quick Favorite bar / button list in the right side of screen pane.


-- Phased Rollout ( Phase 4 checklist) --

Phase 4A – Tab Bar only (1–2 days)
Hard-coded tab names from publishedTabIndexes.
Colored rects + simple text (even without atlas yet — use dummy color quads).
Clicking changes activeTabIndex and triggers re-render.

Phase 4B – Font Atlas + Text (next)
Add stb_truetype or FreeType atlas.
Render real tab labels + button text.

Phase 4C – Ribbon Bar
8–10 buttons with rect + text (icons later).
Click handlers queue actions to the active tab’s engineering thread.

Phase 4D – Icons & Polish
Custom Font for Icons.
Hover glow, pressed state, tooltips (delayed text draw).

Future: regenerate atlas on WM_DPICHANGED
Far Future:
Translator / AI edits: Hindi.csv, German.csv, Tamil.csv
Build step runs: generate_ui_text_table.py
Script generates: UserInterface-Text.generated.h
Compiler builds: static constexpr translation tables
Runtime: no file loading, no parsing, pure compile-time arrays
*/

// UI Layout Constants (millimeters)
constexpr float UI_TAB_BAR_HEIGHT_MM = 4.0f;
constexpr float UI_RIBBON_HEIGHT_MM = 20.0f;
constexpr float UI_VIEWLIST_HEIGHT_MM = 4.0f;
constexpr float UI_DIVIDER_WIDTH_PX = 1.0f;
constexpr float UI_BUTTON_WIDTH_MM = 8.0f;
constexpr float UI_BUTTON_GAP_MM = 1.0f;
constexpr float UI_GROUP_GAP_MM = 5.0f;

// Colors (ABGR)
constexpr uint32_t COLOR_UI_BG_DARK = 0xFF1E1E1E;
constexpr uint32_t COLOR_UI_TAB_ACTIVE = 0xFF2D2D30;
constexpr uint32_t COLOR_UI_TAB_INACTIVE = 0xFF3E3E42;
constexpr uint32_t COLOR_UI_TAB_HOVER = 0xFF3F3F46;
constexpr uint32_t COLOR_UI_TEXT = 0xFFFFFFFF;

struct UIVertex {// Vertex format
    float x, y, u, v;
    uint32_t color; // ABGR format for DX12 standard
};

struct Glyph { // Store glyph info: Glyph metadata (Phase 4B)
    float uvMinX, uvMinY, uvMaxX, uvMaxY; // Normalized UV coordinates in the atlas (0.0 to 1.0)
    int width, height; // Pixel dimensions for drawing the quad
    int bearingX, bearingY; // Positional offsets (Crucial for baseline alignment)
    int advanceX;
};

// Use char32_t for full UTF-32 Unicode support (necessary for all languages)
inline std::unordered_map<char32_t, Glyph> glyphLookup; // Lookup table.

struct UIButton { // UI Button abstraction
    uint32_t id; // Unique hash for immediate mode tracking
    //RECT physicalRect; // Calculated dynamically based on DPI
    const wchar_t* label; // UTF-32 string for HarfBuzz
    int iconIndex; // -1 = no icon, else index into sprite sheet
    char32_t iconCodePoint;// The Unicode point for custom icon font
    bool enabled;
};

struct UITabBarState { // Tab bar state
    int hoveredTab = -1;
    int activeTab; // copied from window.activeTabIndex
};

///////////////////////////////////////////////////////////
struct UIInput {
    // Mouse position in client pixels (top-left origin). Float for consistent math with UI layout.
    float mouseX = 0.0f, mouseY = 0.0f;
    // Persistent button state
    bool leftButtonDown = false, rightButtonDown = false, middleButtonDown = false;
    // Rising/falling edge for this exact frame (used by immediate-mode hit-testing)
    bool leftButtonPressedThisFrame = false,  leftButtonReleasedThisFrame = false;
    bool rightButtonPressedThisFrame = false, middleButtonPressedThisFrame = false;
    int mouseWheelDelta = 0;          // WM_MOUSEWHEEL
    // Modifiers — per-window snapshot (synced with GetAsyncKeyState in WndProc)
    bool shiftDown = false, ctrlDown = false, altDown = false;

    // Text input buffer for future text fields / search boxes (WM_CHAR)
    char32_t textInputThisFrame[32] = {};
    uint8_t  textInputCount = 0; // 0–31 chars this frame. We discard key inputs if we are unable to process.

    // Optional hotkey raw keys this frame (can be added later as a small bitset)
};


// Thread-safe push (lock-free ring buffer style – reuse your MemoryManagerGPU ring buffer idea)
extern std::atomic<uint32_t> actionWriteIndex;
constexpr uint32_t ACTION_RING_SIZE = 4096;

// Call from UI thread:
inline void PushUIAction(uint32_t id, uint32_t p1 = 0, uint32_t p2 = 0) {
    uint32_t idx = actionWriteIndex.fetch_add(1, std::memory_order_relaxed) % ACTION_RING_SIZE;
    // actionRing[idx] = { id, p1, p2, /*timestamp*/ };
    // Engineering thread reads with its own readIndex (standard ring-buffer)
}

// These are exhausting list of identified action user can perform in our application.
enum class UIAction : uint32_t {

    //Action Group 1: Common
    PROJECT_OPEN = 0x00002005,
    PROJECT_SAVE = 0x00002006,
    PROJECT_CLOSE = 0x00002007,

    VIEW_TREE = 0x00004003,
    VIEW_PERSPECTIVE_ISO_DROPDOWN = 0x00004004,   // Dropdown trigger
    VIEW_MAX_ZOOM = 0x00004005,
    VIEW_ROTATE = 0x00004006,
    VIEW_PAN = 0x00004007,

    SELECT_GENERAL = 0x00005003,
    SELECT_PIPES = 0x00005004,
    SELECT_FITTINGS = 0x00005005,
    SELECT_REINFORCEMENT = 0x00005006,
    SELECT_2D_ONLY = 0x00005007,
    SELECT_TEXT = 0x00005008,
    SELECT_LINES = 0x00005009,

    //Action Group 2: (2D) General
    CREATE_LINE = 0x00006001,
    CREATE_POLYLINE = 0x00006002,
    CREATE_CIRCLE = 0x00006003,
    CREATE_ARC = 0x00006004,
    CREATE_ELLIPSE = 0x00006005,
    CREATE_TEXT = 0x00006006,
    CREATE_MULTITEXT = 0x00006007,

    EDIT_COPY = 0x00006008,
    EDIT_OFFSET = 0x00006009,
    EDIT_MOVE = 0x00006010,

    //Action Group 3: "(2D) P&ID"
    CREATE_VVESSEL = 0x00007001,
    CREATE_HVESSEL = 0x00007002,
    CREATE_EXCHANGE = 0x00007003,
    CREATE_PIPE = 0x00007004,
    CREATE_INSTRUMENT = 0x00007005,
    EDIT_PARAMETER = 0x00007006,

    //Action Group 4: (3D) General
    CREATE_FOLDER = 0x00008001,
    CREATE_GRID = 0x00008002,
    CREATE_STRUCTURE = 0x00008003,
    CREATE_LINES_3D = 0x00008004,
    CONCRETE_COLUMN = 0x00008005,
    CONCRETE_BEAM = 0x00008006,
    CONCRETE_SLAB = 0x00008007,
    CONCRETE_CURVED_SLAB = 0x00008008,
    CONCRETE_DOME = 0x00008009,
    CONCRETE_PILE = 0x00008010,
    REINFORCEMENT_LINEAR = 0x00008011,
    REINFORCEMENT_SHAPED_DROPDOWN = 0x00008012,   // Dropdown trigger
    STEEL_COLUMN = 0x00008013,
    STEEL_BEAM = 0x00008014,
    FRP_COLUMN = 0x00008015,
    FRP_BEAM = 0x00008016,
    GLASS_PLATE = 0x00008017,

    //Action Group 5: (3D) Equipment
    EQUIPMENT_VVESSEL = 0x00009001,
    EQUIPMENT_HVESSEL = 0x00009002,
    EQUIPMENT_EXCHANGER = 0x00009003,
    EQUIPMENT_PUMP = 0x00009004,

    //Action Group 6: (3D) Piping
    CREATE_PIPING = 0x0000A001,
    CREATE_SPOOL = 0x0000A002,
    CREATE_VALVE = 0x0000A003,
    CREATE_ELBOW = 0x0000A004,
    CREATE_T = 0x0000A005,
    CREATE_Y = 0x0000A006,
    INSTRUMENT_PG = 0x0000A007,
    INSTRUMENT_TG = 0x0000A008,
    EDIT_EXTEND = 0x0000A009,
    EDIT_STRETCH = 0x0000A010,

    //Action Group 7: Analysis and Simulation
    LOAD_CASE = 0x0000B001,
    LOAD_COMBINATIONS = 0x0000B002,
    LOAD_SELF_WEIGHT = 0x0000B003,
    LOAD_UNIFORM = 0x0000B004,
    LOAD_TRAPEZOIDAL = 0x0000B005,
    LOAD_PRESSURE = 0x0000B006,
    LOAD_TEMPERATURE = 0x0000B007,

    SUPPORT_FIXED = 0x0000B008,
    SUPPORT_PINNED = 0x0000B009,
    SUPPORT_ROLLER = 0x0000B010,

    ANALYSIS_3D_FRAME = 0x0000B011,
    ANALYSIS_STATIC = 0x0000B012,
    ANALYSIS_SPECTRUM = 0x0000B013,
    ANALYSIS_TIME_HISTORY = 0x0000B014,

    //Action Group 8: Code Checking
    CODE_CIVIL_IS456 = 0x0000C001,
    CODE_CIVIL_IS13920 = 0x0000C002,
    CODE_CIVIL_IS800 = 0x0000C003,
    CODE_MECH_ASME_VIII = 0x0000C004,

    //Action Group 9: 3D to 2D
    GENERAL_DRAWING = 0x0000D001,
    GENERAL_SHEET = 0x0000D002,
    GENERAL_3D2DGA = 0x0000D003,
    GENERAL_ASSEMBLY = 0x0000D004,
    GENERAL_ISOMETRIC = 0x0000D005,
    GENERAL_TABLES = 0x0000D006,

    //Action Group 10: (4D) Time
    // 0x0000E000 series reserved for this.
    
    //Action Group 11: (5D) Cost
    // 0x0000F000 series reserved for this.
    
    //Action Group 12: Interoperability
    IMPORT_STD = 0x00010001,
    IMPORT_CII = 0x00010002,
    IMPORT_DXF = 0x00010003,
    IMPORT_DWG = 0x00010004,
    EXPORT_STD = 0x00010005,
    EXPORT_DWG = 0x00010006,

    //Action Group 13: Extensions
    
    // Add more future actions here with gaps if needed (e.g. 0x0000E000+)

    INVALID = 0xFFFFFFFF
};

struct UIControlDefinition {
    UIAction     action;           // Action ID sent to engineering thread
    uint32_t     nameStringID;     // Localization ID (hardcoded for now) of the TEXT.
    char32_t     iconChar;         // Future icon font codepoint (use 'x' for now)
    uint8_t      type;             // 0=PlainText, 1=Button, 2=Dropdown trigger, 3=Textbox
    uint8_t      noOfVerticalSlots;// 1 = full height, 2/3/4 = vertical stack height
    uint8_t      verticalSlotNo;   // 0-based position inside the vertical stack
    uint8_t      zIndex;           // 0=normal, 1=dropdown trigger, 2=dropdown item
    float        defaultWidthPX;   // Base width before DPI scaling
    bool         showText;         // true = show label, false = icon only
    bool         isEnabled;        // true = show this button/label etc, false = gray out this.
    uint8_t      actionGrpupIndex; // 0-based index in array of UIActionGroupName for Text reference.
    uint32_t     actionSubGroupID; // Localization ID (hardcoded for now) of the TEXT.
};

// Action Groups are basically a set of User Control Buttons.
// This struct will be used to group buttons by top Menus, and specialized property panes in the right side.
struct UIActionGroup {
    uint32_t labelStringID;     // e.g. 10001 = "Common"
    uint16_t firstControlIndex; // Index into giant AllUIControls array
    uint8_t index;              // Simple index to assist with order in future.
    bool isEnabled;             // User may switch off any action groups.
    bool isMinimized;           // Used in right side property panes.
};

constexpr UIActionGroup topUIActionGroups[] = {
    { 10001 , 0 , true }, // ACTION GROUP  1: Common
    { 10002 , 0 , true }, // ACTION GROUP  2: (2D) General
    { 10003 , 0 , true }, // ACTION GROUP  3: (2D) P&ID
    { 10004 , 0 , true }, // ACTION GROUP  4: (3D) General
    { 10005 , 0 , true }, // ACTION GROUP  5: (3D) Equipment
    { 10006 , 0 , true }, // ACTION GROUP  6: (3D) Piping
    { 10007 , 0 , true }, // ACTION GROUP  7: Simulation
    { 10008 , 0 , true }, // ACTION GROUP  8: Code Checking
    { 10009 , 0 , true }, // ACTION GROUP  9: 3D to 2D
    { 10010 , 0 , true }, // ACTION GRPUP 10: (4D) Time
    { 10011 , 0 , true }, // ACTION GROUP 11: (5D) Cost
    { 10012 , 0 , true }, // ACTION GROUP 12: Interoperability & Miscellaneous
    { 10013 , 0 , true }, // ACTION GROUP 13: Extensions
};

// Initially I wanted to discard the idea of sub-grouping the buttons within each action groups.
// However, realized that during training / support discussion we usually need to explain the user,
// To go to specific group and specific sub group. So it ramins for training & quick onboarding purpose. 

// COMPILE-TIME GIANT ARRAY . Lists ALL top primary buttons (excliding right side pane) available in application.
// This is the single source of truth. ~80+ controls shown here. we can extend to 500+ easily.

constexpr UIControlDefinition AllUIControls[] = {
    // ACTION GROUP 1: Common
    // SubGroup: Project Organization
    { UIAction::PROJECT_OPEN,          2005, U'x', 1, 1, 0, 0, 85.0f, true, false, 1 , 200001 },
    { UIAction::PROJECT_SAVE,          2006, U'x', 1, 1, 0, 0, 85.0f, true, false, 1 , 200001 },
    { UIAction::PROJECT_CLOSE,         2007, U'x', 1, 1, 0, 0, 85.0f, true, false, 1 , 200001 },

    // SubGroup: View
    { UIAction::VIEW_TREE,             4003, U'x', 1, 1, 0, 0, 70.0f, true, false, 1 , 200001 },
    { UIAction::VIEW_PERSPECTIVE_ISO_DROPDOWN, 4004, U'x', 2, 1, 0, 1, 110.0f, true, false, 1 , 200001 }, // Dropdown
    { UIAction::VIEW_MAX_ZOOM,         4005, U'x', 1, 1, 0, 0, 70.0f, true, false, 1 , 200001 },
    { UIAction::VIEW_ROTATE,           4006, U'x', 1, 1, 0, 0, 70.0f, true, false, 1 , 200001 },
    { UIAction::VIEW_PAN,              4007, U'x', 1, 1, 0, 0, 70.0f, true, false, 1 , 200001 },

    // SubGroup: Select
    { UIAction::SELECT_GENERAL,        5003, U'x', 1, 1, 0, 0, 80.0f, true, false, 1 , 200001 },
    { UIAction::SELECT_PIPES,          5004, U'x', 1, 1, 0, 0, 80.0f, true, false, 1 , 200001 },
    { UIAction::SELECT_FITTINGS,       5005, U'x', 1, 1, 0, 0, 80.0f, true, false, 1 , 200001 },
    { UIAction::SELECT_REINFORCEMENT,  5006, U'x', 1, 1, 0, 0, 80.0f, true, false, 1 , 200001 },
    { UIAction::SELECT_2D_ONLY,        5007, U'x', 1, 1, 0, 0, 80.0f, true, false, 1 , 200001 },
    { UIAction::SELECT_TEXT,           5008, U'x', 1, 1, 0, 0, 80.0f, true, false, 1 , 200001 },
    { UIAction::SELECT_LINES,          5009, U'x', 1, 1, 0, 0, 80.0f, true, false, 1 , 200001 },

    // ACTION GROUP 2: (2D) General
    // SubGroup: Create 2D Shapes
    { UIAction::CREATE_LINE,           6001, U'x', 1, 1, 0, 0, 75.0f, true, false, 2 , 200001 },
    { UIAction::CREATE_POLYLINE,       6002, U'x', 1, 1, 0, 0, 75.0f, true, false, 2 , 200001 },
    { UIAction::CREATE_CIRCLE,         6003, U'x', 1, 1, 0, 0, 75.0f, true, false, 2 , 200001 },
    { UIAction::CREATE_ARC,            6004, U'x', 1, 1, 0, 0, 75.0f, true, false, 2 , 200001 },
    { UIAction::CREATE_ELLIPSE,        6005, U'x', 1, 1, 0, 0, 75.0f, true, false, 2 , 200001 },
    { UIAction::CREATE_TEXT,           6006, U'x', 1, 1, 0, 0, 75.0f, true, false, 2 , 200001 },
    { UIAction::CREATE_MULTITEXT,      6007, U'x', 1, 1, 0, 0, 75.0f, true, false, 2 , 200001 },

    // SubGroup: Edit
    { UIAction::EDIT_COPY,             6008, U'x', 1, 1, 0, 0, 70.0f, true, false, 2 , 200001 },
    { UIAction::EDIT_OFFSET,           6009, U'x', 1, 1, 0, 0, 70.0f, true, false, 2 , 200001 },
    { UIAction::EDIT_MOVE,             6010, U'x', 1, 1, 0, 0, 70.0f, true, false, 2 , 200001 },

    // ACTION GROUP 3: (2D) P&ID
    { UIAction::CREATE_VVESSEL,        7001, U'x', 1, 1, 0, 0, 85.0f, true, false, 3 , 200001 },
    { UIAction::CREATE_HVESSEL,        7002, U'x', 1, 1, 0, 0, 85.0f, true, false, 3 , 200001 },
    { UIAction::CREATE_EXCHANGE,       7003, U'x', 1, 1, 0, 0, 85.0f, true, false, 3 , 200001 },
    { UIAction::CREATE_PIPE,           7004, U'x', 1, 1, 0, 0, 85.0f, true, false, 3 , 200001 },
    { UIAction::CREATE_INSTRUMENT,     7005, U'x', 1, 1, 0, 0, 85.0f, true, false, 3 , 200001 },
    { UIAction::EDIT_PARAMETER,        7006, U'x', 1, 1, 0, 0, 90.0f, true, false, 3 , 200001 },

    // ACTION GROUP 4: (3D) General
    { UIAction::CREATE_FOLDER,         8001, U'x', 1, 1, 0, 0, 70.0f, true, false, 4 , 200001 },
    { UIAction::CREATE_GRID,           8002, U'x', 1, 1, 0, 0, 70.0f, true, false, 4 , 200001 },
    { UIAction::CREATE_STRUCTURE,      8003, U'x', 1, 1, 0, 0, 70.0f, true, false, 4 , 200001 },
    { UIAction::CREATE_LINES_3D,       8004, U'x', 1, 1, 0, 0, 70.0f, true, false, 4 , 200001 },

    // Concrete
    { UIAction::CONCRETE_COLUMN,       8005, U'x', 1, 1, 0, 0, 80.0f, true, false, 4 , 200001 },
    { UIAction::CONCRETE_BEAM,         8006, U'x', 1, 1, 0, 0, 80.0f, true, false, 4 , 200001 },
    { UIAction::CONCRETE_SLAB,         8007, U'x', 1, 1, 0, 0, 80.0f, true, false, 4 , 200001 },
    { UIAction::CONCRETE_CURVED_SLAB,  8008, U'x', 1, 1, 0, 0, 80.0f, true, false, 4 , 200001 },
    { UIAction::CONCRETE_DOME,         8009, U'x', 1, 1, 0, 0, 80.0f, true, false, 4 , 200001 },
    { UIAction::CONCRETE_PILE,         8010, U'x', 1, 1, 0, 0, 80.0f, true, false, 4 , 200001 },

    // Reinforcement
    { UIAction::REINFORCEMENT_LINEAR,  8011, U'x', 1, 1, 0, 0, 85.0f, true, false, 4 , 200001 },
    { UIAction::REINFORCEMENT_SHAPED_DROPDOWN, 8012, U'x', 2, 1, 0, 1, 110.0f, true, false, 4 , 200001 },

    // Steel, FRP, Glass
    { UIAction::STEEL_COLUMN,          8013, U'x', 1, 1, 0, 0, 80.0f, true, false, 4 , 200001 },
    { UIAction::STEEL_BEAM,            8014, U'x', 1, 1, 0, 0, 80.0f, true, false, 4 , 200001 },
    { UIAction::FRP_COLUMN,            8015, U'x', 1, 1, 0, 0, 80.0f, true, false, 4 , 200001 },
    { UIAction::FRP_BEAM,              8016, U'x', 1, 1, 0, 0, 80.0f, true, false, 4 , 200001 },
    { UIAction::GLASS_PLATE,           8017, U'x', 1, 1, 0, 0, 80.0f, true, false, 4 , 200001 },

    // ACTION GROUP 5: (3D) Equipment
    { UIAction::EQUIPMENT_VVESSEL,     9001, U'x', 1, 1, 0, 0, 85.0f, true, false, 5 , 200001 },
    { UIAction::EQUIPMENT_HVESSEL,     9002, U'x', 1, 1, 0, 0, 85.0f, true, false, 5 , 200001 },
    { UIAction::EQUIPMENT_EXCHANGER,   9003, U'x', 1, 1, 0, 0, 85.0f, true, false, 5 , 200001 },
    { UIAction::EQUIPMENT_PUMP,        9004, U'x', 1, 1, 0, 0, 85.0f, true, false, 5 , 200001 },

    // ACTION GROUP 6: (3D) Piping
    { UIAction::CREATE_PIPING,         0xA001, U'x', 1, 1, 0, 0, 80.0f, true, false, 6 , 200001 },
    { UIAction::CREATE_SPOOL,          0xA002, U'x', 1, 1, 0, 0, 80.0f, true, false, 6 , 200001 },
    { UIAction::CREATE_VALVE,          0xA003, U'x', 1, 1, 0, 0, 80.0f, true, false, 6 , 200001 },
    { UIAction::CREATE_ELBOW,          0xA004, U'x', 1, 1, 0, 0, 80.0f, true, false, 6 , 200001 },
    { UIAction::CREATE_T,              0xA005, U'x', 1, 1, 0, 0, 80.0f, true, false, 6 , 200001 },
    { UIAction::CREATE_Y,              0xA006, U'x', 1, 1, 0, 0, 80.0f, true, false, 6 , 200001 },
    { UIAction::INSTRUMENT_PG,         0xA007, U'x', 1, 1, 0, 0, 75.0f, true, false, 6 , 200001 },
    { UIAction::INSTRUMENT_TG,         0xA008, U'x', 1, 1, 0, 0, 75.0f, true, false, 6 , 200001 },
    { UIAction::EDIT_EXTEND,           0xA009, U'x', 1, 1, 0, 0, 70.0f, true, false, 6 , 200001 },
    { UIAction::EDIT_STRETCH,          0xA010, U'x', 1, 1, 0, 0, 70.0f, true, false, 6 , 200001 },

    // ACTION GROUP 7: Analyze
    { UIAction::LOAD_CASE,             0xB001, U'x', 1, 1, 0, 0, 80.0f, true, false, 7 , 200001 },
    { UIAction::LOAD_COMBINATIONS,     0xB002, U'x', 1, 1, 0, 0, 80.0f, true, false, 7 , 200001 },
    { UIAction::LOAD_SELF_WEIGHT,      0xB003, U'x', 1, 1, 0, 0, 80.0f, true, false, 7 , 200001 },
    { UIAction::LOAD_UNIFORM,          0xB004, U'x', 1, 1, 0, 0, 80.0f, true, false, 7 , 200001 },
    { UIAction::LOAD_TRAPEZOIDAL,      0xB005, U'x', 1, 1, 0, 0, 80.0f, true, false, 7 , 200001 },
    { UIAction::LOAD_PRESSURE,         0xB006, U'x', 1, 1, 0, 0, 80.0f, true, false, 7 , 200001 },
    { UIAction::LOAD_TEMPERATURE,      0xB007, U'x', 1, 1, 0, 0, 80.0f, true, false, 7 , 200001 },

    { UIAction::SUPPORT_FIXED,         0xB008, U'x', 1, 1, 0, 0, 75.0f, true, false, 7 , 200001 },
    { UIAction::SUPPORT_PINNED,        0xB009, U'x', 1, 1, 0, 0, 75.0f, true, false, 7 , 200001 },
    { UIAction::SUPPORT_ROLLER,        0xB010, U'x', 1, 1, 0, 0, 75.0f, true, false, 7 , 200001 },

    { UIAction::ANALYSIS_3D_FRAME,     0xB011, U'x', 1, 1, 0, 0, 90.0f, true, false, 7 , 200001 },
    { UIAction::ANALYSIS_STATIC,       0xB012, U'x', 1, 1, 0, 0, 90.0f, true, false, 7 , 200001 },
    { UIAction::ANALYSIS_SPECTRUM,     0xB013, U'x', 1, 1, 0, 0, 90.0f, true, false, 7 , 200001 },
    { UIAction::ANALYSIS_TIME_HISTORY, 0xB014, U'x', 1, 1, 0, 0, 90.0f, true, false, 7 , 200001 },

    // ACTION GROUP 8: Code Checking
    { UIAction::CODE_CIVIL_IS456,      0xC001, U'x', 1, 1, 0, 0, 85.0f, true, false, 8 , 200001 },
    { UIAction::CODE_CIVIL_IS13920,    0xC002, U'x', 1, 1, 0, 0, 85.0f, true, false, 8 , 200001 },
    { UIAction::CODE_CIVIL_IS800,      0xC003, U'x', 1, 1, 0, 0, 85.0f, true, false, 8 , 200001 },
    { UIAction::CODE_MECH_ASME_VIII,   0xC004, U'x', 1, 1, 0, 0, 95.0f, true, false, 8 , 200001 },

    // ACTION GROUP 9: 3D->2D
    { UIAction::GENERAL_DRAWING,       0xD001, U'x', 1, 1, 0, 0, 85.0f, true, false, 9 , 200001 },
    { UIAction::GENERAL_SHEET,         0xD002, U'x', 1, 1, 0, 0, 85.0f, true, false, 9 , 200001 },
    { UIAction::GENERAL_3D2DGA,        0xD001, U'x', 1, 1, 0, 0, 85.0f, true, false, 9 , 200001 },
    { UIAction::GENERAL_ASSEMBLY,      0xD002, U'x', 1, 1, 0, 0, 85.0f, true, false, 9 , 200001 },
    { UIAction::GENERAL_ISOMETRIC,     0xD003, U'x', 1, 1, 0, 0, 85.0f, true, false, 9 , 200001 },
    { UIAction::GENERAL_TABLES,        0xD004, U'x', 1, 1, 0, 0, 85.0f, true, false, 9 , 200001 },

    // ACTION GROUP 10: Time
    // ACTION GROUP 11: Cost

    // ACTION GROUP 12: Interoperability & Miscellaneous.
    { UIAction::IMPORT_STD,            0xE001, U'x', 1, 1, 0, 0, 70.0f, true, false, 12 , 200001 },
    { UIAction::IMPORT_CII,            0xE002, U'x', 1, 1, 0, 0, 70.0f, true, false, 12 , 200001 },
    { UIAction::IMPORT_DXF,            0xE003, U'x', 1, 1, 0, 0, 70.0f, true, false, 12 , 200001 },
    { UIAction::IMPORT_DWG,            0xE004, U'x', 1, 1, 0, 0, 70.0f, true, false, 12 , 200001 },
    { UIAction::EXPORT_STD,            0xE005, U'x', 1, 1, 0, 0, 70.0f, true, false, 12 , 200001 },
    { UIAction::EXPORT_DWG,            0xE006, U'x', 1, 1, 0, 0, 70.0f, true, false, 12 , 200001 },

    // ACTION GROUP 13: Extensions
    { UIAction::CODE_CIVIL_IS456,      0xC001, U'x', 1, 1, 0, 0, 85.0f }
};

constexpr size_t TotalUIControls = std::size(AllUIControls);
