#pragma once
// Auto-generated by UserInterfaceTranslationCompiler.py - DO NOT EDIT MANUALLY
// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.

#include <cstdint>
#include "UserInterface-TextTranslations.h"

namespace UITranslations
{
    /**
     * Returns the localized UTF-32 string for the given stringID and language.
     * If the translation is missing/empty, English (index 0) is returned as fallback.
     * Returns empty string if the stringID is unknown.
     */
    const char32_t* GetUILocalizedString(uint32_t stringID, UILanguage language);
}
