// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
#pragma once
#include <iostream>
#include <cstdint>
#include <unordered_map>
#include <array>
#include <vector>

#include <ft2build.h>
#include FT_FREETYPE_H

#include "ListOfCommands.h"
#include "SVGIconRenderer.h"
#include "FontManager.h" // FreeType font atlas generation
#include "UserInterface-TextTranslations.h" // localization
#include "UserInterfaceTranslationCompiled.h"
#include <deque>
#include <mutex>

/*
This file is our User Inteface Design document.
Further, codes common to DirectX12 / Vulkan / Metal engines are defined in this file itself.

User Interface Design: Render the entire UI in DirectX12 itself. UI is a post-geometry overlay.
Fundamental UI Philosophy: Immediate Mode UI (initially). Late stage, Retained mode for Top Ribbons/Active forms.
Pipeline: RenderFrame(){ Render3DScene() RenderUIOverlay() Present() } This file represents UI part.
Rendering Order: Clear > Render3D > DisableDepth > EnableBlend > RenderUI > Present
UI Coordinate System : Use pixel space. Origin: (0,0) = top-left. Screen: X → right, Y → down
Orthographic matrix: float4x4 Ortho = { 2/W, 0, 0, -1, 0, -2/H, 0, 1,  0, 0, 1, 0, 0, 0, 0, 1 }
This allows vertices to be placed directly in pixels.
UI Vertex is different from 3D scene vertex because it mandatorily refers to a texture needing u/v coordinates.
Tab 0 stores common textures and UI elements.
3 primitives:
1st: Rectangles Used for buttons / backgrounds / panels / tab bar, Rendered as: 2 triangles
2nd: Text Rendered via: glyph atlas texture, 3rd: Icons, Also from texture atlas.

We will use FreeType to keep maximum cross platform code base between Windows / Linux / Mac / Android / iOS.
HarfBuzz for Unicode shaping. Initial implementation will skip this and have ASCII characters only.

At startup:
Load font file (TTF) or desired Language / Script. ( All 18 indian scheduled languages covered. )
Generate glyph bitmaps. Pack into texture atlas. Upload to GPU
Glyph packing algorithm: Skyline bin packer

Dedicated Root signature (uiRootSignature), Pipeline State Object (uiPipelineState)
Vertex shader: position → clip space, uv → pass through, color → pass through
Pixel shader: sample atlas, multiply color,
Enable: alpha blending, Blend: SrcAlpha, InvSrcAlpha

Use: DrawIndexedInstanced, No ExecuteIndirect needed. Batch everything.
When drawing text: for each character, lookup glyph, append quad

There are only 2 themes. Light and Dark. No colorful themes. System Light / Dark theme to be followed by default.
This is to facilitate color as discipline code or visually distinguishing different UI elements.
Our initial implementation will not have any Icons !
During advanced stage of development, dedicated fonts depicting the icon will be constructed.
So that same font rendering codes also generates the Icons ! No PNG embedded icon resource at all.
Initial Memory Budget: Font atlas ~4MB, Icon atlas ~2MB, Vertex buffer ~1MB, Index buffer ~256KB

UI Layout:
----------------------------------------------
| TAB BAR    4mm High           MIN-MAX-CLOSE|
--------------------1px-----------------------
| ACTION GROUP    24mm High                  |
--------------------1px-----------------------
| VIEW LIST ( Currently only 1)   4mm High   |
--------------------1px-----------------------
| I |                           |Action  | I |
| C |                           |Pane    | C |
| O |       3D VIEWPORT         |As per  | O |
| N |                           |Right   | N |
| S |                           |Buttons | S |
----------------------------------------------
| What next action user needs to take text   |
----------------------------------------------

Pixels = Millimeters * (Monitor_DPI / 25.4f)

In शंकर::InitD3DPerTab add if (tab.tabID == 0) InitUIResources(tab);
Create the atlas texture once (committed resource, DEFAULT heap).
Upload via Copy Queue exactly like geometry pages (reuse your upload ring buffer you are about to add).
Mark it published immediately and never touch again.
All text in UI shall be mandatorily any of the size : 1.5mm, 2.5mm(default), 4mm. No customizable size.

Ribbon groups will be static compile time. Left and Right side buttons will be partially static and
partially dynamical generated by engineering threads. 

Each button will have  following:
1. An integer number action ID, to signal to engineering thread what to do. 
    Action integer IDs can have gaps for future buttons.
2. 1 special "Icon" alphabet , along with a Icon size.
3. An integer string id. This string id will be localized to ~45 languages also at compile time in separate 
    localization.h file ).
4. Width & Height of Icon in pixels. This will start with default value at compile time, 
    but will be multiplied by a specific factor based on screen DPI at runtime of owning monitor.
5. 1 uint8 ZIndex to handle small drop down menu buttons. To facilitate 1 active dropdown at a time.

Definitions of ribbon tab groups shall be different from basic button list. 
Such that user could add the same buttons at different locations. Example apart from main location in ribbon, 
a button could also be added to Quick Favorite bar / button list in the right side of screen pane.

All UI strings are compile time assigned an immutable uint32 ID to translation vsv file.
Each language get's its own translation csv file. Ex:
UserInterfaceTranslation_<2 digit language code>_languageName.csv

WorldID, ShortWordName, English, Human, Comments, ChatGPT, Gemini, Grok, Claude  
1, Home, Home, Home Button, Home Button, Home Button, Home Button, Home Button, Home Button
2, Copy, Copy, Copy Button, Copy Button, Copy Button, Copy Button, Copy Button, Copy Button
3, Edit, Edit, Edit Button, Edit Button, Edit Button, Edit Button, Edit Button, Edit Button
4, Draw, Draw, Draw Button, Draw Button, Draw Button, Draw Button, Draw Button, Draw Button
5, Erase, Erase, Erase Button, Erase Button, Erase Button, Erase Button, Erase Button, Erase Button
6, Close, Close, Close Button, Close Button, Close Button, Close Button, Close(Button), Close(Button)
 
Corresponding statically compiled translated header need to be generated as part of build process.
This CSV to .h translation will happen using a python script named UserInterfaceTranslationCompiler.py file. 
All of the csv, .py and .h/.cpp shall be checked into git. Compiled code will produce following 2 files only.
They will represent all languages.
 
UserInterfaceTranslationCompiled.h
UserInterfaceTranslationCompiled.cpp
 
C++ code will provide a simple function to return string for corresponding integer string ID.
All unique alphabet combination shall be rendered in a single texture atlas and handed over 2D buffer
    for uploading to GPU by UI handling code.
This texture preparation shall happen at the beginning of application launch in an async thread.
Till the time this thread completes its texture atlas preparation, UI handler code will keep displaying a blank space.
For string which have a missing translation corresponding English word shall be displayed. At a time,
texture atlas of only 1 language shall be active.
The font files will come from byte steam already loaded by other part of code from embedded Resource.
 
Initial translation shall be performed by AI translator file named UserInterfaceTranslationByAI.py

-- Phased Rollout ( Phase 4 checklist) --


Phase 4C – Ribbon Bar
Click handlers queue actions to the active tab’s engineering thread.

Phase 4D – Icons & Polish
Custom Font for Icons.
Hover glow, pressed state, tooltips (delayed text draw).

Future: regenerate atlas on WM_DPICHANGED
Far Future:
Translator / AI edits: Hindi.csv, German.csv, Tamil.csv
Build step runs: generate_ui_text_table.py
Script generates: UserInterface-Text.generated.h
Compiler builds: static constexpr translation tables
Runtime: no file loading, no parsing, pure compile-time arrays
*/

// UI Layout Constants (millimeters)
constexpr float UI_TEXT_HEIGHT_MM = 2.5f; // EIL's recommended text hight for printed drawing is 2.5mm.
// Perhaps this is also good for UI text to maintain consistency between printed and on-screen drawings.
// TODO: Latter, we will allow user to customize text height from settings.
constexpr float UI_TAB_BAR_HEIGHT_MM = 4.0f;
constexpr float UI_INTERNAL_TAB_BAR_HEIGHT_MM = 4.0f;
constexpr float UI_ACTION_GROUP_LABEL_HEIGHT_MM = 4.0f;
constexpr float UI_ACTION_GROUP_HEIGHT_MM = 12.0f; // Divisible by 2/3/4
constexpr float UI_VIEWLIST_HEIGHT_MM = 4.0f;
constexpr float UI_DIVIDER_GAP_PX = 1.0f;
constexpr float UI_BUTTON_HEIGHT_MM = 3.0f; // Text is 2.5mm.
constexpr float UI_BUTTON_WIDTH_MM = 8.0f;
constexpr float UI_BUTTON_GAP_MM = 1.0f;
constexpr float UI_ICON_SIZE_MM = 4.0f;
// Minimum DPI used for ALL DPI->pixel UI layout math. On coarse monitors (e.g. 92 DPI) the true
// physical size would minify icons/text below legibility; clamping the layout DPI to this floor
// drives the whole ribbon as if it were 127 DPI (where UI_ICON_SIZE_MM == 20 px), so icons, text and
// bands scale up together and nothing clips. Monitors already above this are unaffected.
constexpr float UI_MIN_LAYOUT_DPI = 127.0f;
constexpr float UI_GROUP_GAP_MM = 5.0f; // We would rather keep it 2 pixel fixed width.
constexpr float UI_BUTTON_CORNER_RADIUS_MM = 2.0f;

// Right-side icon bar + object properties pane (website/content/software/propertiesPane.md).
constexpr float UI_RIGHT_ICONBAR_WIDTH_MM = 8.0f;
constexpr float UI_RIGHT_PANE_WIDTH_MM = 64.0f;

constexpr uint32_t UI_MAX_ATLAS_TEXTURES = 10;
constexpr uint32_t UI_ENGLISH_ATLAS_SLOT = 0;
constexpr uint32_t UI_ICON_ATLAS_SLOT = 1;
constexpr uint32_t UI_FIRST_DYNAMIC_SCRIPT_ATLAS_SLOT = 2;

// Colors (ABGR)
constexpr uint32_t COLOR_UI_TAB_ACTIVE = 0xFF2D2D30;
constexpr uint32_t COLOR_UI_TAB_INACTIVE = 0xFF3E3E42;

struct UIVertex {// Vertex format
    float x, y, u, v;
    uint32_t color; // ABGR format for DX12 standard
    uint32_t atlasIndex; // Index into the UI SRV atlas array. 0 = English, 1 = icons/shape coverage.
};

struct Glyph { // Store glyph info: Glyph metadata (Phase 4B)
    float uvMinX, uvMinY, uvMaxX, uvMaxY; // Normalized UV coordinates in the atlas (0.0 to 1.0)
    int width, height; // Pixel dimensions for drawing the quad
    int bearingX, bearingY; // Positional offsets (Crucial for baseline alignment)
    int advanceX;
};

// Use char32_t for full UTF-32 Unicode support (necessary for all languages)
inline std::unordered_map<char32_t, Glyph> glyphLookup; // Lookup table.
// The icon glyph lookup (private-use codepoints for monochrome UI icons) is per monitor now: its UVs
// depend on the monitor's icon cell size, which varies with DPI. It lives inside IconAtlasCPU below.
extern std::string charset;

struct AtlasBitmap {
    int width;
    int height;
    int bytesPerPixel = 1; // 1 channel (R8) or 4 channels (RGBA8)
    std::vector<uint8_t> pixels;
};

inline AtlasBitmap BuildFontAtlas() {
    const int atlasW = 512;
    const int atlasH = 512;

    AtlasBitmap atlas;
    atlas.width = atlasW;
    atlas.height = atlasH;
    atlas.pixels.resize(atlasW * atlasH, 0);

    int penX = 0;
    int penY = 0;
    int rowHeight = 0;

    for (char c : charset)
    {
        if (FT_Load_Char(ftFace, c, FT_LOAD_RENDER)) continue;

        FT_GlyphSlot g = ftFace->glyph;

        if (penX + g->bitmap.width >= atlasW) {
            penX = 0;
            penY += rowHeight;
            rowHeight = 0;
        }

        // Copy bitmap
        for (int y = 0; y < (int)g->bitmap.rows; y++) {
            for (int x = 0; x < (int)g->bitmap.width; x++) {
                int dst = (penY + y) * atlasW + (penX + x);
                atlas.pixels[dst] = g->bitmap.buffer[y * g->bitmap.pitch + x];
            }
        }

        // Store glyph metadata
        Glyph glyph{};
        glyph.uvMinX = (float)penX / atlasW;
        glyph.uvMinY = (float)penY / atlasH;
        glyph.uvMaxX = (float)(penX + g->bitmap.width) / atlasW;
        glyph.uvMaxY = (float)(penY + g->bitmap.rows) / atlasH;

        glyph.width = g->bitmap.width;
        glyph.height = g->bitmap.rows;
        glyph.bearingX = g->bitmap_left;
        glyph.bearingY = g->bitmap_top;
        glyph.advanceX = g->advance.x >> 6;

        glyphLookup[c] = glyph;

        penX += g->bitmap.width + 1;
        int glyphHeight = (int)g->bitmap.rows;
        if (glyphHeight > rowHeight) { rowHeight = glyphHeight; }
    }

    return atlas;
}

struct UIButton { // UI Button abstraction
    uint32_t id; // Unique hash for immediate mode tracking
    //RECT physicalRect; // Calculated dynamically based on DPI
    const wchar_t* label; // UTF-32 string for HarfBuzz
    int iconIndex; // -1 = no icon, else index into sprite sheet
    char32_t iconCodePoint;// The Unicode point for custom icon font
    bool enabled;
};

struct UITabBarState { // Tab bar state
    int hoveredTab = -1;
    int activeTab; // copied from window.activeTabIndex
};

struct UIInput {
    // Mouse position in client pixels (top-left origin). Float for consistent math with UI layout.
    float mouseX = 0.0f, mouseY = 0.0f;
    // Persistent button state
    bool leftButtonDown = false, rightButtonDown = false, middleButtonDown = false;
    // Rising/falling edge for this exact frame (used by immediate-mode hit-testing)
    bool leftButtonPressedThisFrame = false,  leftButtonReleasedThisFrame = false;
    bool leftButtonDoubleClickedThisFrame = false;
    bool rightButtonPressedThisFrame = false, middleButtonPressedThisFrame = false;
    int mouseWheelDelta = 0;          // WM_MOUSEWHEEL
    // Modifiers — per-window snapshot (synced with GetAsyncKeyState in WndProc)
    bool shiftDown = false, ctrlDown = false, altDown = false;

    // Text input buffer for future text fields / search boxes (WM_CHAR)
    char32_t textInputThisFrame[32] = {};
    uint8_t  textInputCount = 0; // 0–31 chars this frame. We discard key inputs if we are unable to process.

    // Optional hotkey raw keys this frame (can be added later as a small bitset)
};

// Reusable immediate-mode dropdown state (Insert Asset pane; future setting panes). The caller
// owns one instance per dropdown (usually on SingleUIWindow) and draws it via BuildUIDropdown.
struct UIDropdownState {
    bool isOpen = false;
};

// Editable text-field state (UI/render thread owned). One in-progress edit per window.
// Keystrokes mutate this buffer only; the committed value reaches the engineering thread on Enter.
struct UITextEditState {
    uint64_t focusedFieldKey = 0; // 0 = none. Key = hash(objectId, fieldIndex).
    char32_t buffer[32] = {};     // Numeric entry never needs more.
    uint8_t  length = 0;
    uint8_t  caret = 0;
    uint64_t editingObjectId = 0; // Guard: commit only to the object the edit started on.
};

struct UIColors { // Standard UI Colours (ABGR format for DX12)
    // The default values specified here are for theme "Light". 
    // These can be overridden by other themes (e.g. Dark) or by user customizations.
    uint32_t tabBackground = 0xFFD4E5DD; //rgba(221, 229, 212)
    uint32_t tabBackgroundText = 0xFF4E6254; //rgba(84, 98, 78) + Corner smoothening color?
    //tabActive is also the background color of action group surrounding.
    uint32_t tabActive = 0xFFF1FBF8; //rgba(248, 251, 241)
    uint32_t tabActiveText = 0xFF171D19; //rgba(25, 29, 23)
    uint32_t tabBackgroundHover = 0xFFC4D5CD; // 1 Shade darker than tabBackground.

    uint32_t actionGroupBackground = 0xFFFFFFFF;
    uint32_t actionGroupSeperator = 0xFFD1D1D1; //rgba(209, 209, 209)
    uint32_t actionGroupHoverBackground = 0xFFFF9933; // Orange in Indian Flag
    uint32_t actionText = 0xFF242424; //rgba(36, 36, 36) + Corner smoothening color?
    //Action icon color is stored inside the button itself. Different icons = different colors.
    uint32_t actionIconDisabled = 0xFF888888; //rgba(136, 136, 136)
};

// The palette every overlay draws with (defined in UserInterface.cpp).
extern UIColors uiActiveColors;


// Thread-safe push (lock-free ring buffer style – reuse your MemoryManagerGPU ring buffer idea)
extern std::atomic<uint32_t> actionWriteIndex;
constexpr uint32_t ACTION_RING_SIZE = 4096;
// Simpler thread-safe queue for UI -> Engine actions (protected by mutex)
struct UIActionEntry {
    uint32_t id;
    uint64_t p1;
    uint64_t p2;
    uint64_t p3 = 0; // Third payload word (property commits need tab+field, id and value all together).
};

// Property edit commit: UI (render thread) -> engineering thread. Payload packing documented at
// website/content/software/propertiesPane.md §5. p1 = (tabIndex << 8) | fieldIndex,
// p2 = objectMemoryId, p3 = std::bit_cast<uint64_t>(double value).
constexpr uint32_t kPropertyCommitUIAction = 0xE0000020u;

namespace InternalSubTabs {
constexpr uint32_t kOpenUIAction = 0xE0000010u;
constexpr uint32_t kActivateUIAction = 0xE0000011u;
constexpr uint32_t kCloseUIAction = 0xE0000012u;
constexpr uint32_t kExtractUIAction = 0xE0000013u; // p1 = tab index, p2 = containerMemoryId.
}

// Window management (only the UI thread creates/destroys OS windows; render threads request).
constexpr uint32_t kExtractTabUIAction = 0xE0000030u;      // p1 = tab id dragged out of the tab band.
constexpr uint32_t kCloseViewWindowUIAction = 0xE0000031u; // p1 = tab index, p2 = sub-tab slot.

//TODO: WARNING: Get rid of mutex and use lock-free multi producer single consumer ring buffer for this.
extern std::mutex g_actionQueueMutex;
extern std::deque<UIActionEntry> g_actionQueue;

constexpr char32_t UIIconForCommand(Commands command) noexcept {
    return SVGIconRenderer::IconForID(static_cast<uint32_t>(command));
}

// Call from UI thread: push an action into the global action queue
inline void PushUIAction(uint32_t id, uint64_t p1 = 0, uint64_t p2 = 0, uint64_t p3 = 0) {
    std::lock_guard<std::mutex> lk(g_actionQueueMutex);
    g_actionQueue.push_back({ id, p1, p2, p3 });
    // actionRing[idx] = { id, p1, p2, /*timestamp*/ };
    // Engineering thread reads with its own readIndex (standard ring-buffer)
}


struct UIControlDefinition {
	Commands     action;           // Action ID sent to engineering thread, upon clicking this control. 
    // This is the single source of truth for all buttons, dropdowns, text fields etc.
    UITextID     nameStringID;     // Localization ID (hardcoded for now) of the TEXT.
    char32_t     iconChar;         // Future icon font codepoint (use 'x' for now)
    uint8_t      type;             // 0=PlainText, 1=Button, 2=Dropdown trigger, 3=Textbox
    uint8_t      noOfVerticalSlots;// 1 = full height, 2/3/4 = vertical stack height
    uint8_t      verticalSlotNo;   // 0-based position inside the vertical stack
    uint8_t      zIndex;           // 0=normal, 1=dropdown trigger, 2=dropdown item
    bool         showText;         // true = show label, false = icon only
    // false = the command has no handler in Main.cpp ProcessPendingUIActions() yet. Such a control
    // renders its label and icon in kUIDisabledTextGray and ignores hover/click. Flip to true in the
    // same commit that wires the command up, else the new button stays gray and inert.
    bool         isEnabled;
    uint8_t      actionGroupIndex; // 0-based index in array of UIActionGroupName for Text reference.
    uint8_t      actionSubGroupIndex; // Localization ID (hardcoded for now) of the TEXT.
};

// Action Groups are basically a set of User Control Buttons.
// This struct will be used to group buttons by top Menus, and specialized property panes in the right side.
struct UIActionGroupNames {
    UITextID labelStringID;     // e.g. 11 = "Common"
    bool isEnabled;             // User may switch off any action groups.
    bool isMinimized;           // Used in right side property panes.
};


constexpr UIActionGroupNames topUIActionGroupNames[] = {
	// Initially marking all action group enabled, and non-minimized. User can change this at runtime.
    { UITextID::Common, true, false },          // ACTION GROUP  0: Common
    { UITextID::General2D, true, false },       // ACTION GROUP  1: (2D) General
    { UITextID::Intelligent2D, true, false },   // ACTION GROUP  2: (2D) Intelligent
    { UITextID::General3D, true, false },       // ACTION GROUP  3: (3D) General
    { UITextID::Intelligent3D, true, false },   // ACTION GROUP  4: (3D) Intelligent
    { UITextID::Simulation, true, false },      // ACTION GROUP  5: Simulation
    { UITextID::CodeChecking, true, false },    // ACTION GROUP  6: Code Checking
    { UITextID::Documentation, true, false },   // ACTION GROUP  7: Documentation
    { UITextID::ThreeDtoTwoD, true, false },    // ACTION GROUP  8: 3D to 2D
    { UITextID::Time4D, true, false },          // ACTION GROUP  9: (4D) Time
    { UITextID::Cost5D, true, false },          // ACTION GROUP 10: (5D) Cost
    { UITextID::Utility, true, false },         // ACTION GROUP 11: Utility
    { UITextID::Extension, true, false },       // ACTION GROUP 12: Extensions
};
constexpr size_t TotalTopUIActionGroups = std::size(topUIActionGroupNames);

// Initially I wanted to discard the idea of sub-grouping the buttons within each action groups.
// However, realized that during training / support discussion we usually need to explain the user,
// To go to specific group and specific sub group. So it remains for training & quick onboarding purpose. 

constexpr UIActionGroupNames topUIActionSubGroupNames[] = {
    // Initially marking all action sub group enabled, and non-minimized. User can change this at runtime.
    { UITextID::Organize, true, false },
    { UITextID::View, true, false },
    { UITextID::Select, true, false },
    { UITextID::Modify, true, false },
    { UITextID::Basic, true, false },
    { UITextID::Create, true, false },
    { UITextID::Search, true, false },
    { UITextID::ProcessEquipment, true, false },
    { UITextID::Premitives, true, false },
    { UITextID::Reinforcement, true, false },
    { UITextID::Equipments, true, false },
    { UITextID::Piping, true, false },
    { UITextID::Supports, true, false },
    { UITextID::Analysis, true, false },
    { UITextID::Structural, true, false },
    { UITextID::Mechanical, true, false },
    { UITextID::Extraction, true, false },
    { UITextID::FreeForm, true, false },
    { UITextID::Helpers, true, false },
    { UITextID::LoadGenerators, true, false },
    { UITextID::ImportExport, true, false },
    { UITextID::ActiveExtensions, true, false },
    { UITextID::Civil, true, false },
    { UITextID::General, true, false },
};
constexpr size_t TotalTopUIActionSubGroups = std::size(topUIActionSubGroupNames);

// COMPILE-TIME GIANT ARRAY . Lists ALL top primary buttons (excliding right side pane) available in application.
// This is the single source of truth. ~80+ controls shown here. we can extend to 500+ easily.

constexpr UIControlDefinition AllUIControls[] = {
    // ACTION GROUP 0: Common
    // Subgroup : Organize
    { Commands::PROJECT_OPEN,          UITextID::PROJECT_OPEN, UIIconForCommand(Commands::PROJECT_OPEN), 1, 3, 0, 0, true, true, 0 , 0 },
    { Commands::PROJECT_SAVE,          UITextID::PROJECT_SAVE, UIIconForCommand(Commands::PROJECT_SAVE), 1, 3, 1, 0, true, true, 0 , 0 },
    { Commands::PROJECT_PRINT,         UITextID::PROJECT_PRINT, UIIconForCommand(Commands::PROJECT_PRINT), 1, 3, 2, 0, true, true, 0 , 0 }, //Print visible Page2D / 3D scene.
    { Commands::PROJECT_CLOSE,         UITextID::PROJECT_CLOSE, UIIconForCommand(Commands::PROJECT_CLOSE), 1, 3, 0, 0, true, true, 0 , 0 },
    { Commands::CREATE_FOLDER,         UITextID::CREATE_FOLDER, UIIconForCommand(Commands::CREATE_FOLDER), 1, 3, 1, 0, true, true, 0 , 0 }, //Dropdown: Copy/Delete/Duplicate Folder
    { Commands::CREATE_PAGE2D,         UITextID::CREATE_PAGE2D, UIIconForCommand(Commands::CREATE_PAGE2D), 1, 3, 2, 0, true, true, 0 , 0 }, //Represents a 2D sheet.
    { Commands::CREATE_SCENE3D,        UITextID::CREATE_SCENE3D, UIIconForCommand(Commands::CREATE_SCENE3D), 1, 3, 0, 0, true, true, 0 , 0 }, //Represents a 3D world.
    { Commands::FOLDER_VISIBILITY,     UITextID::FOLDER_VISIBILITY, UIIconForCommand(Commands::FOLDER_VISIBILITY), 1, 1, 0, 0, true, true, 0 , 0 }, //Toggle Heirarchy ON/OFF

    // Subgroup : Search
    // Text box to search for objects in current view. Search happens in current view only to keep it simple.
    { Commands::SEARCH_BOX,            UITextID::SEARCH_BOX, UIIconForCommand(Commands::SEARCH_BOX), 2, 3, 0, 1, true, false, 0 , 6 },
    { Commands::SEARCH_NORMAL,         UITextID::SEARCH_NORMAL, UIIconForCommand(Commands::SEARCH_NORMAL), 2, 3, 1, 1, true, false, 0 , 6 },
    { Commands::SEARCH_ADVANCED,       UITextID::SEARCH_ADVANCED, UIIconForCommand(Commands::SEARCH_ADVANCED), 2, 3, 2, 1, true, false, 0 , 6 }, // Dedicated sidebar in future.
    { Commands::SEARCH_PREVIOUS,       UITextID::SEARCH_PREVIOUS, UIIconForCommand(Commands::SEARCH_PREVIOUS), 2, 2, 0, 1, true, false, 0 , 6 },
    { Commands::SEARCH_NEXT,           UITextID::SEARCH_NEXT, UIIconForCommand(Commands::SEARCH_NEXT), 2, 2, 1, 1, true, false, 0 , 6 },

    // Subgroup : Select
    { Commands::SELECT_ANYTHING,       UITextID::SELECT_ANYTHING, UIIconForCommand(Commands::SELECT_ANYTHING), 1, 3, 0, 0, true, false, 0 , 2 },
    { Commands::SELECT_PIPING,         UITextID::SELECT_PIPING, UIIconForCommand(Commands::SELECT_PIPING), 1, 3, 1, 0, true, false, 0 , 2 },
    { Commands::SELECT_BEAMCOLUMNS,    UITextID::SELECT_BEAMCOLUMNS, UIIconForCommand(Commands::SELECT_BEAMCOLUMNS), 1, 3, 2, 0, true, false, 0 , 2 },
    { Commands::SELECT_REINFORCEMENT,  UITextID::SELECT_REINFORCEMENT, UIIconForCommand(Commands::SELECT_REINFORCEMENT), 1, 3, 0, 0, true, false, 0 , 2 },
    { Commands::SELECT_TEMPLATES,      UITextID::SELECT_TEMPLATES, UIIconForCommand(Commands::SELECT_TEMPLATES), 1, 3, 1, 0, true, false, 0 , 2 }, // 3D templates and 2D blocks.
    { Commands::SELECT_TEXT,           UITextID::SELECT_TEXT, UIIconForCommand(Commands::SELECT_TEXT), 1, 3, 2, 0, true, false, 0 , 2 }, // Text in 3D scene and 2D sheets.
    { Commands::SELECT_LINES,          UITextID::SELECT_LINES, UIIconForCommand(Commands::SELECT_LINES), 1, 3, 0, 0, true, false, 0 , 2 }, // Anything othe than text and templates.

    // Subgroup : View
    { Commands::ZOOM_MAX,              UITextID::ZOOM_MAX, UIIconForCommand(Commands::ZOOM_MAX), 1, 3, 0, 0, true, true, 0 , 1 }, //Fit ALL objects of active Scene3D/Page2D.
    { Commands::ZOOM_FOCUS,            UITextID::ZOOM_FOCUS, UIIconForCommand(Commands::ZOOM_FOCUS), 1, 3, 1, 0, true, true, 0 , 1 }, //Fit selected objects (all if none selected).
    { Commands::ZOOM_WINDOW,           UITextID::ZOOM_WINDOW, UIIconForCommand(Commands::ZOOM_WINDOW), 1, 3, 2, 0, true, true, 0 , 1 }, //Two clicks define a rectangle to zoom onto.
    { Commands::TOGGLE_AUTO_RANDOM,    UITextID::TOGGLE_AUTO_RANDOM, UIIconForCommand(Commands::TOGGLE_AUTO_RANDOM), 1, 3, 0, 0, true, true, 0 , 1 }, //Toggle auto-generation of random demo shapes ON/OFF.

    // ACTION GROUP 1: (2D) General
    // Subgroup : Create 2D Shapes
    { Commands::CREATE_LINE,           UITextID::CREATE_LINE, UIIconForCommand(Commands::CREATE_LINE), 1, 3, 0, 0, true, true, 1 , 5 },
    { Commands::CREATE_POLYLINE,       UITextID::CREATE_POLYLINE, UIIconForCommand(Commands::CREATE_POLYLINE), 1, 3, 1, 0, true, true, 1 , 5 },
    //Polygon Dropdown: Triangle, Rectangle, Pentagon, Hexagon, Heptagon, Octagon.
    { Commands::CREATE_POLYGON,        UITextID::CREATE_POLYGON, U'x', 1, 3, 2, 0, true, true, 1 , 5 },
    { Commands::CREATE_CIRCLE,         UITextID::CREATE_CIRCLE, UIIconForCommand(Commands::CREATE_CIRCLE), 1, 3, 0, 0, true, true, 1 , 5 },
    { Commands::CREATE_ARC,            UITextID::CREATE_ARC, UIIconForCommand(Commands::CREATE_ARC), 1, 3, 1, 0, true, true, 1 , 5 },
    { Commands::CREATE_ELLIPSE,        UITextID::CREATE_ELLIPSE, UIIconForCommand(Commands::CREATE_ELLIPSE), 1, 3, 2, 0, true, true, 1 , 5 },
    // Nurbs are very powerfull!
    // They generalize Bezier Curves, B-Splines, Conic Sections (Circle/ellipses/parabola/hyperbola)
    { Commands::CREATE_NURBS,           UITextID::CREATE_NURBS, U'x', 1, 3, 0, 0, true, false, 1 , 5 },
    { Commands::CREATE_TEXT,            UITextID::CREATE_TEXT, U'x', 1, 3, 1, 0, true, true, 1 , 5 },
    { Commands::CREATE_SPECIALTEXT,     UITextID::CREATE_SPECIALTEXT, U'x', 1, 3, 2, 0, true, false, 1 , 5 },
    { Commands::CREATE_DIMENSION,       UITextID::CREATE_DIMENSION, U'x', 1, 3, 0, 0, true, false, 1 , 5 },
    { Commands::CREATE_LEADER,          UITextID::CREATE_LEADER, U'x', 1, 3, 1, 0, true, false, 1 , 5 },
    { Commands::CREATE_RADIUS,          UITextID::CREATE_RADIUS, U'x', 1, 3, 2, 0, true, false, 1 , 5 },
    { Commands::CREATE_BLOCK,           UITextID::CREATE_BLOCK, U'x', 1, 3, 0, 0, true, false, 1 , 5 },
    { Commands::CREATE_CLOUD,           UITextID::CREATE_CLOUD, U'x', 1, 3, 1, 0, true, false, 1 , 5 },

    { Commands::CREATE_HATCH,           UITextID::CREATE_HATCH, U'x', 1, 3, 2, 0, true, false, 1 , 5 },
    { Commands::CREATE_POINT,           UITextID::CREATE_POINT, U'x', 1, 3, 0, 0, true, false, 1 , 5 },
    { Commands::CREATE_ARRAY,           UITextID::CREATE_ARRAY, U'x', 1, 3, 1, 0, true, false, 1 , 5 },
    { Commands::CREATE_GRID2D,          UITextID::CREATE_GRID2D, U'x', 1, 3, 2, 0, true, false, 1 , 5 },
    { Commands::CREATE_ASSET2D,         UITextID::CREATE_ASSET2D, U'x', 1, 3, 0, 0, true, true, 1 , 5 },
    { Commands::INSERT_ASSET2D,         UITextID::INSERT_ASSET2D, U'x', 1, 3, 1, 0, true, true, 1 , 5 },

    // SubGroup: Modify
    { Commands::EDIT_COPY,              UITextID::EDIT_COPY, U'x', 1, 3, 0, 0, true, true, 1 , 3 },
    { Commands::EDIT_MIRROR,            UITextID::EDIT_MIRROR, U'x', 1, 3, 1, 0, true, true, 1 , 3 },
    { Commands::EDIT_OFFSET,            UITextID::EDIT_OFFSET, U'x', 1, 3, 2, 0, true, true, 1 , 3 },
    { Commands::EDIT_MOVE,              UITextID::EDIT_MOVE, U'x', 1, 3, 0, 0, true, true, 1 , 3 },
    { Commands::EDIT_ROTATE,            UITextID::EDIT_ROTATE, U'x', 1, 3, 1, 0, true, true, 1 , 3 },
    { Commands::EDIT_STRETCH,           UITextID::EDIT_STRETCH, U'x', 1, 3, 2, 0, true, false, 1 , 3 },
    { Commands::EDIT_SCALE,             UITextID::EDIT_SCALE, U'x', 1, 3, 0, 0, true, false, 1 , 3 },
    { Commands::EDIT_EXTEND,            UITextID::EDIT_EXTEND, U'x', 1, 3, 1, 0, true, false, 1 , 3 },
    { Commands::EDIT_TRIM,              UITextID::EDIT_TRIM, U'x', 1, 3, 2, 0, true, false, 1 , 3 },
    { Commands::EDIT_FILLET,            UITextID::EDIT_FILLET, U'x', 1, 3, 0, 0, true, false, 1 , 3 },
    { Commands::EDIT_CHAMFER,           UITextID::EDIT_CHAMFER, U'x', 1, 3, 1, 0, true, false, 1 , 3 },
    { Commands::EDIT_EXPLODE,           UITextID::EDIT_EXPLODE, U'x', 1, 3, 2, 0, true, false, 1 , 3 },

    // ACTION GROUP 2: (2D) Advanced
    // Subgroup : Process Equipments
    // These are intelligent 2D symbols with embedded parameters. User can place them in 2D view.
    { Commands::CREATE_VVESSEL2D,       UITextID::CREATE_VVESSEL2D, U'x', 1, 3, 0, 0, true, false, 2 , 7 },
    { Commands::CREATE_HVESSEL2D,       UITextID::CREATE_HVESSEL2D, U'x', 1, 3, 1, 0, true, false, 2 , 7 },
    { Commands::CREATE_EXCHANGER2D,     UITextID::CREATE_EXCHANGER2D, U'x', 1, 3, 2, 0, true, false, 2 , 7 },
    { Commands::CREATE_FILTER2D,        UITextID::CREATE_FILTER2D, U'x', 1, 3, 0, 0, true, false, 2 , 7 },
    { Commands::CREATE_PUMP2D,          UITextID::CREATE_PUMP2D, U'x', 1, 3, 1, 0, true, false, 2 , 7 },
    { Commands::CREATE_AIRCOOLER2D,     UITextID::CREATE_AIRCOOLER2D, U'x', 1, 3, 2, 0, true, false, 2 , 7 },
    { Commands::CREATE_COMPRESSOR2D,    UITextID::CREATE_COMPRESSOR2D, U'x', 1, 3, 0, 0, true, false, 2 , 7 },
    { Commands::CREATE_PIPE2D,          UITextID::CREATE_PIPE2D, U'x', 1, 3, 1, 0, true, false, 2 , 7 },
    { Commands::CREATE_INSTRUMENT2D,    UITextID::CREATE_INSTRUMENT2D, U'x', 1, 3, 2, 0, true, false, 2 , 7 },
    { Commands::EDIT_PARAMETER,         UITextID::EDIT_PARAMETER, U'x', 1, 3, 0, 0, true, false, 2 , 7 },

    // ACTION GROUP 3: (3D)
    // These are our basic surface modeling capabilities.
    // We can use these to create complex 3D shapes using boolean operations, or direct face/edge/vertex editing.
    // Subgroup : Primitives
    { Commands::CREATE_CUBOID,          UITextID::CREATE_CUBOID, U'x', 1, 3, 0, 0, true, true, 3 , 8 },
    { Commands::CREATE_CYLINDER,        UITextID::CREATE_CYLINDER, U'x', 1, 3, 1, 0, true, true, 3 , 8 },
    { Commands::CREATE_SPHERE,          UITextID::CREATE_SPHERE, U'x', 1, 3, 0, 0, true, true, 3 , 8 },
    { Commands::CREATE_DISC,            UITextID::CREATE_DISC, U'x', 1, 3, 1, 0, true, false, 3 , 8 },
    { Commands::CREATE_PYRAMID,         UITextID::CREATE_PYRAMID, U'x', 1, 3, 2, 0, true, true, 3 , 8 }, //3/4/5/6/7/8 sided pyramid dropdown.
    { Commands::CREATE_CONE,            UITextID::CREATE_CONE, U'x', 1, 3, 0, 0, true, true, 3 , 8 },
    { Commands::CREATE_TORUS,           UITextID::CREATE_TORUS, U'x', 1, 3, 1, 0, true, true, 3 , 8 },
    { Commands::CREATE_ELLIPSOID,       UITextID::CREATE_ELLIPSOID, U'x', 1, 3, 2, 0, true, true, 3 , 8 },

    // Subgroup : Freeform. These are extreme levels ! We need them to model the turbine blades, or ship hulls etc.
    { Commands::CREATE_NURBS,           UITextID::CREATE_NURBS, U'x', 1, 2, 0, 0, true, false, 3 , 17 },
    { Commands::CREATE_SWIPE2D,         UITextID::CREATE_SWIPE2D, U'x', 1, 2, 0, 0, true, false, 3 , 17 },

    // Subgroup : Modify
    { Commands::CUTBY_PLANE,            UITextID::CUTBY_PLANE, U'x', 1, 3, 0, 0, true, false, 3 , 3 },
    { Commands::CUTBY_POLYGON,          UITextID::CUTBY_POLYGON, U'x', 1, 3, 1, 0, true, false, 3 , 3 },
    { Commands::CUTBY_PRIMITIVE,        UITextID::CUTBY_PRIMITIVE, U'x', 1, 3, 2, 0, true, false, 3 , 3 }, // Dropdown: All basic shapes.
    { Commands::CUTBY_PART,             UITextID::CUTBY_PART, U'x', 1, 3, 0, 0, true, false, 3 , 3 }, // One shape by other on screen.
    { Commands::SPLIT,                  UITextID::SPLIT, U'x', 1, 3, 1, 0, true, false, 3 , 3 }, // Dropdown: Plane/N-point On Line
    { Commands::EDGE_FILLET,            UITextID::EDGE_FILLET, U'x', 1, 3, 2, 0, true, false, 3 , 3 },
    { Commands::EDGE_CHAMFER,           UITextID::EDGE_CHAMFER, U'x', 1, 3, 0, 0, true, false, 3 , 3 },
    { Commands::HOLE_CIRCULAR,          UITextID::HOLE_CIRCULAR, U'x', 1, 3, 1, 0, true, false, 3 , 3 },
    { Commands::HOLE_RECTANGULAR,       UITextID::HOLE_RECTANGULAR, U'x', 1, 3, 2, 0, true, false, 3 , 3 },
    { Commands::HOLE_POLYGONAL,         UITextID::HOLE_POLYGONAL, U'x', 1, 3, 0, 0, true, false, 3 , 3 },

    // Subgroup : Helper
    { Commands::CREATE_GRID3D,          UITextID::CREATE_GRID3D, U'x', 1, 2, 0, 0, true, false, 3 , 18 },

    // Subgroup : Views
    { Commands::CREATE_VIEW_3D,         UITextID::CREATE_VIEW_3D, U'x', 1, 0, 0, 0, true, false, 3 , 1 }, //A plane with a inclusion offset distance.
    // Offset distance in above setting will determine object visibility into the view. Intersecting objects are also visible.
    { Commands::CREATE_TEMP_CLIP,       UITextID::CREATE_TEMP_CLIP, U'x', 2, 3, 0, 1, true, false, 3 , 1 }, // Toggle Orthographic/Isometric/Perspective
    { Commands::DELETE_TEMP_CLIP,       UITextID::DELETE_TEMP_CLIP, U'x', 1, 3, 1, 0, true, false, 3 , 1 },
    { Commands::VIEW3D_TYPE,            UITextID::VIEW3D_TYPE, U'x', 1, 3, 2, 0, true, false, 3 , 1 }, //Dropdown: Solid/Transparent/Nodal Connectivity
    { Commands::HIDE_SELECTED,          UITextID::HIDE_SELECTED, U'x', 2, 3, 0, 1, true, false, 3 , 1 },
    { Commands::HIDE_UNSELECTED,        UITextID::HIDE_UNSELECTED, U'x', 2, 3, 1, 1, true, false, 3 , 1 },
    { Commands::HIDE_RESET,             UITextID::HIDE_RESET, U'x', 2, 3, 2, 1, true, false, 3 , 1 },
    // Following 3 buttons change the behaviour of Left mouse button + drag on empty space in the view.
    { Commands::VIEW_ROTATE,            UITextID::VIEW_ROTATE, U'x', 1, 3, 0, 0, true, false, 3 , 1 }, //Dropdown: X/Y/Z Axis Rotate.
    { Commands::VIEW_PAN,               UITextID::VIEW_PAN, U'x', 1, 3, 1, 0, true, false, 3 , 1 }, //Dropdown: Pan / Tilt / Orbit
    { Commands::MAX_ZOOM_WINDOW,        UITextID::MAX_ZOOM_WINDOW, U'x', 1, 3, 2, 0, true, false, 3 , 1 }, //Zoom on all visible object.
    { Commands::MAX_ZOOM_HEIRARCHY,     UITextID::MAX_ZOOM_HEIRARCHY, U'x', 1, 3, 0, 0, true, false, 3 , 1 }, //Zoom on current heirarchy.
    { Commands::MOUSE_WINDOW_ZOOM,      UITextID::MOUSE_WINDOW_ZOOM, U'x', 1, 3, 1, 0, true, false, 3 , 1 }, // Allows user to focus on an area.
    { Commands::VIEW_PROJECTION,        UITextID::VIEW_PROJECTION, U'x', 2, 3, 2, 1, true, false, 3 , 1 }, // Toggle Orthographic/Perspective
    //Setting a view to ISOMETRIC will automatically set the view ISO angle and switch to orthographic projection.
    { Commands::VIEW_ISOMETRIC,         UITextID::VIEW_ISOMETRIC, U'x', 1, 3, 0, 0, true, false, 3 , 1 }, // Dropdown: ISO-1/2/3/4/5/6/7/8.
    // Following views are parallel to X/Y/Z axis. They are basically a 2D view of the 3D model from different sides.
    { Commands::VIEW_LEFT,              UITextID::VIEW_LEFT, U'x', 1, 3, 0, 0, true, false, 3 , 1 },
    { Commands::VIEW_RIGHT,             UITextID::VIEW_RIGHT, U'x', 1, 3, 1, 0, true, false, 3 , 1 },
    { Commands::VIEW_FRONT,             UITextID::VIEW_FRONT, U'x', 1, 3, 2, 0, true, false, 3 , 1 },
    { Commands::VIEW_BACK,              UITextID::VIEW_BACK, U'x', 1, 3, 0, 0, true, false, 3 , 1 },
    { Commands::VIEW_BOTTOM,            UITextID::VIEW_BOTTOM, U'x', 1, 3, 1, 0, true, false, 3 , 1 },
    { Commands::VIEW_TOP,               UITextID::VIEW_TOP, U'x', 1, 3, 2, 0, true, false, 3 , 1 },

    // ACTION GROUP 4: (3D) Intelligent
    // Subgroup : Organize.
    // These are essentially 3D containers to organize the model. They have some special capabilities.
    { Commands::CREATE_STRUCTURE,       UITextID::CREATE_STRUCTURE, U'x', 1, 0, 0, 0, true, false, 4 , 6 },
    // These can inherit the properties from corresponding 2D symbols. Or can have their own parameters.
    { Commands::CREATE_VVESSEL3D,       UITextID::CREATE_VVESSEL3D, U'x', 1, 3, 0, 0, true, false, 4 , 5 },
    { Commands::CREATE_HVESSEL3D,       UITextID::CREATE_HVESSEL3D, U'x', 1, 3, 1, 0, true, false, 4 , 5 },
    { Commands::CREATE_EXCHANGER3D,     UITextID::CREATE_EXCHANGER3D, U'x', 1, 3, 2, 0, true, false, 4 , 5 },
    { Commands::CREATE_FILTER3D,        UITextID::CREATE_FILTER3D, U'x', 1, 3, 0, 0, true, false, 4 , 5 },
    { Commands::CREATE_PUMP3D,          UITextID::CREATE_PUMP3D, U'x', 1, 3, 1, 0, true, false, 4 , 5 },
    { Commands::CREATE_AIRCOOLER3D,     UITextID::CREATE_AIRCOOLER3D, U'x', 1, 3, 2, 0, true, false, 4 , 5 },
    { Commands::CREATE_COMPRESSOR3D,    UITextID::CREATE_COMPRESSOR3D, U'x', 1, 3, 0, 0, true, false, 4 , 5 },
    { Commands::CREATE_PIPING3D,        UITextID::CREATE_PIPING3D, U'x', 1, 3, 1, 0, true, false, 4 , 5 },
    { Commands::EDIT_PARAMETER,         UITextID::EDIT_PARAMETER, U'x', 1, 3, 2, 0, true, false, 4 , 5 },

    // Subgroup : Structural
    // Linear Structural Elements. These are basically 3D beams and columns.
    // They can have different cross sections, and material (Concrete / Steel / Timber / FRP etc.) properties.
    { Commands::LINE_ELEMENT_COLUMN,    UITextID::LINE_ELEMENT_COLUMN, U'x', 1, 3, 0, 0, true, false, 4 , 14 },
    { Commands::LINE_ELEMENT_BEAM,      UITextID::LINE_ELEMENT_BEAM, U'x', 1, 3, 1, 0, true, false, 4 , 14 },
    { Commands::CONCRETE_SLAB_POLY,     UITextID::CONCRETE_SLAB_POLY, U'x', 1, 3, 2, 0, true, false, 4 , 14 }, //Slabs are planer polygons.
    { Commands::CONCRETE_SLAB_RECT,     UITextID::CONCRETE_SLAB_RECT, U'x', 1, 3, 0, 0, true, false, 4 , 14 }, //Rectangular only.
    { Commands::LINE_ELEMENT_WALL,      UITextID::LINE_ELEMENT_WALL, U'x', 1, 3, 1, 0, true, false, 4 , 14 }, //Dropdown: Polygonal/Ring/Arc.
    { Commands::CONCRETE_DOME,          UITextID::CONCRETE_DOME, U'x', 1, 3, 2, 0, true, false, 4 , 14 }, //Ellipsoidal dome for Nuclear!
    // Piles can essentially can be any shape assigned. Can even have buttress!
    { Commands::CREATE_PILE,            UITextID::CREATE_PILE, U'x', 1, 3, 0, 0, true, false, 4 , 14 },
    { Commands::PLATE_RECTANGULAR,      UITextID::PLATE_RECTANGULAR, U'x', 1, 3, 1, 0, true, false, 4 , 14 },
    { Commands::PLATE_POLYGONAL,        UITextID::PLATE_POLYGONAL, U'x', 1, 3, 2, 0, true, false, 4 , 14 },
    { Commands::GRATING_POLY,           UITextID::GRATING_POLY, U'x', 1, 3, 0, 0, true, false, 4 , 14 },
    { Commands::BOLT_GROUP_RECT,        UITextID::BOLT_GROUP_RECT, U'x', 1, 3, 1, 0, true, false, 4 , 14 },
    { Commands::BOLT_GROUP_CIRCULAR,    UITextID::BOLT_GROUP_CIRCULAR, U'x', 1, 3, 2, 0, true, false, 4 , 14 },

    // Subgroup : Reinforcement
    { Commands::RF_SINGLE,              UITextID::RF_SINGLE, U'x', 1, 3, 0, 0, true, false, 4 , 9 }, // Can be either single or in a set.
    { Commands::RF_REBAR_SET,           UITextID::RF_REBAR_SET, U'x', 1, 3, 1, 0, true, false, 4 , 9 }, // 3D rebar for complex geometry. Single/Set.
    { Commands::RF_COUPLER,             UITextID::RF_COUPLER, U'x', 1, 3, 2, 0, true, false, 4 , 9 },
    { Commands::RF_LAP,                 UITextID::RF_LAP, U'x', 2, 3, 0, 1, true, false, 4 , 9 },
    { Commands::RF_SURFACE_LINK,        UITextID::RF_SURFACE_LINK, U'x', 2, 3, 1, 1, true, false, 4 , 9 },
    { Commands::RF_SURFACE_UNLINK,      UITextID::RF_SURFACE_UNLINK, U'x', 2, 3, 2, 1, true, false, 4 , 9 },

    // Subgroup : Piping
    { Commands::CREATE_PIPING,          UITextID::CREATE_PIPING, U'x', 1, 3, 0, 0, true, false, 4 , 11 },
    { Commands::CREATE_SPOOL,           UITextID::CREATE_SPOOL, U'x', 1, 3, 1, 0, true, false, 4 , 11 },
    { Commands::CREATE_VALVE,           UITextID::CREATE_VALVE, U'x', 1, 3, 2, 0, true, false, 4 , 11 },
    { Commands::CREATE_ELBOW,           UITextID::CREATE_ELBOW, U'x', 1, 3, 0, 0, true, true, 4 , 11 },
    { Commands::CREATE_T,               UITextID::CREATE_T, U'x', 1, 3, 1, 0, true, true, 4 , 11 },
    { Commands::CREATE_Y,               UITextID::CREATE_Y, U'x', 1, 3, 2, 0, true, false, 4 , 11 },
    { Commands::CREATE_FLANGE,          UITextID::CREATE_FLANGE, U'x', 1, 3, 0, 0, true, true, 4 , 11 },
    { Commands::CREATE_LINE_MEMBER,     UITextID::CREATE_LINE_MEMBER, U'x', 1, 3, 1, 0, true, true, 4 , 11 },
    { Commands::INSTRUMENT_PG,          UITextID::INSTRUMENT_PG, U'x', 1, 3, 0, 0, true, false, 4 , 11 },
    { Commands::INSTRUMENT_TG,          UITextID::INSTRUMENT_TG, U'x', 1, 3, 1, 0, true, false, 4 , 11 },

    // Subgroup : Modify
    // This workson structural and piping elements both. Dropdown: Pipe Only / Structural Only / Both.
    { Commands::EDIT_EXTEND,            UITextID::EDIT_EXTEND, U'x', 1, 2, 0, 0, true, false, 4 , 3 },
    { Commands::EDIT_STRETCH,           UITextID::EDIT_STRETCH, U'x', 1, 2, 1, 0, true, false, 4 , 3 },

    // ACTION GROUP 5: Simulation and Analysis
    // Subgroup : Loads & Combinations
    { Commands::LOAD_CASE,              UITextID::LOAD_CASE, U'x', 1, 3, 0, 0, true, false, 5 , 23 },
    { Commands::LOAD_COMBINATIONS,      UITextID::LOAD_COMBINATIONS, U'x', 1, 3, 1, 0, true, false, 5 , 23 },
    { Commands::LOAD_SELF_WEIGHT,       UITextID::LOAD_SELF_WEIGHT, U'x', 1, 3, 2, 0, true, false, 5 , 23 },
    { Commands::LOAD_POINT,             UITextID::LOAD_POINT, U'x', 1, 3, 0, 0, true, false, 5 , 23 },
    { Commands::LOAD_UNIFORM,           UITextID::LOAD_UNIFORM, U'x', 1, 3, 1, 0, true, false, 5 , 23 },
    { Commands::LOAD_TRAPEZOIDAL,       UITextID::LOAD_TRAPEZOIDAL, U'x', 1, 3, 2, 0, true, false, 5 , 23 },
    { Commands::LOAD_PRESSURE,          UITextID::LOAD_PRESSURE, U'x', 1, 3, 0, 0, true, false, 5 , 23 }, // Either on Area or on a face.
    { Commands::LOAD_TEMPERATURE,       UITextID::LOAD_TEMPERATURE, U'x', 1, 3, 1, 0, true, false, 5 , 23 },
    { Commands::LOAD_TIMESERIES,        UITextID::LOAD_TIMESERIES, U'x', 1, 3, 2, 0, true, false, 5 , 23 },

    // Subgroup : Load Generators
    { Commands::LOAD_WIND_IS875,        UITextID::LOAD_WIND_IS875, U'x', 1, 3, 0, 0, true, false, 5 , 19 }, //Dropdown of all other wind codes.
    { Commands::LOAD_SEISMIC_IS1893,    UITextID::LOAD_SEISMIC_IS1893, U'x', 1, 3, 1, 0, true, false, 5 , 19 },//Dropdown of all other seismic codes.
    { Commands::LOAD_SNOW_IS875,        UITextID::LOAD_SNOW_IS875, U'x', 1, 3, 2, 0, true, false, 5 , 19 }, //Dropdown of all other snow codes.

    // Subgroup : Supports
    { Commands::SUPPORT_FIXED,          UITextID::SUPPORT_FIXED, U'x', 1, 3, 0, 0, true, false, 5 , 12 },
    { Commands::SUPPORT_PINNED,         UITextID::SUPPORT_PINNED, U'x', 1, 3, 1, 0, true, false, 5 , 12 },
    { Commands::SUPPORT_ROLLER,         UITextID::SUPPORT_ROLLER, U'x', 1, 3, 2, 0, true, false, 5 , 12 },
    { Commands::SUPPORT_PARTIAL,        UITextID::SUPPORT_PARTIAL, U'x', 1, 3, 0, 0, true, false, 5 , 12 },
    { Commands::SUPPORT_FUNCTIONAL,     UITextID::SUPPORT_FUNCTIONAL, U'x', 1, 3, 1, 0, true, false, 5 , 12 },

    // Subgroup : Analysis Types
    { Commands::ANALYSIS_3D_FRAME,      UITextID::ANALYSIS_3D_FRAME, U'x', 1, 3, 0, 0, true, false, 5 , 13 },
    { Commands::ANALYSIS_STATIC,        UITextID::ANALYSIS_STATIC, U'x', 1, 3, 1, 0, true, false, 5 , 13 },
    { Commands::ANALYSIS_SPECTRUM,      UITextID::ANALYSIS_SPECTRUM, U'x', 1, 3, 2, 0, true, false, 5 , 13 },
    { Commands::ANALYSIS_TIME_HISTORY,  UITextID::ANALYSIS_TIME_HISTORY, U'x', 1, 3, 0, 0, true, false, 5 , 13 },
    { Commands::ANALYSIS_THERMAL,       UITextID::ANALYSIS_THERMAL, U'x', 1, 3, 1, 0, true, false, 5 , 13 },

    // ACTION GROUP 6: Code Checking
    // Subgroup : Civil
    { Commands::CODE_CIVIL_IS456_LSD,   UITextID::CODE_CIVIL_IS456_LSD, U'x', 1, 3, 0, 0, true, false, 6 , 22 },
    { Commands::CODE_CIVIL_IS456_WSD,   UITextID::CODE_CIVIL_IS456_WSD, U'x', 1, 3, 1, 0, true, false, 6 , 22 },
    { Commands::CODE_CIVIL_IS13920,     UITextID::CODE_CIVIL_IS13920, U'x', 1, 3, 2, 0, true, false, 6 , 22 },
    { Commands::CODE_CIVIL_IS3370,      UITextID::CODE_CIVIL_IS3370, U'x', 1, 3, 0, 0, true, false, 6 , 22 },
    { Commands::CODE_CIVIL_ACI318,      UITextID::CODE_CIVIL_ACI318, U'x', 1, 3, 1, 0, true, false, 6 , 22 },
    { Commands::CODE_CIVIL_EUROCODE2,   UITextID::CODE_CIVIL_EUROCODE2, U'x', 1, 3, 2, 0, true, false, 6 , 22 },
    { Commands::CODE_CIVIL_GB50010,     UITextID::CODE_CIVIL_GB50010, U'x', 1, 3, 0, 0, true, false, 6 , 22 },

    { Commands::CODE_CIVIL_IS800_LSD,   UITextID::CODE_CIVIL_IS800_LSD, U'x', 1, 3, 1, 0, true, false, 6 , 22 },
    { Commands::CODE_CIVIL_IS800_WSD,   UITextID::CODE_CIVIL_IS800_WSD, U'x', 1, 3, 2, 0, true, false, 6 , 22 },
    { Commands::CODE_CIVIL_AISC360,     UITextID::CODE_CIVIL_AISC360, U'x', 1, 3, 0, 0, true, false, 6 , 22 },
    { Commands::CODE_CIVIL_EUROCODE3,   UITextID::CODE_CIVIL_EUROCODE3, U'x', 1, 3, 1, 0, true, false, 6 , 22 },
    { Commands::CODE_CIVIL_GB50017,     UITextID::CODE_CIVIL_GB50017, U'x', 1, 3, 2, 0, true, false, 6 , 22 },

    // Subgroup : Mechanical
    { Commands::CODE_MECH_ASME_VIII,    UITextID::CODE_MECH_ASME_VIII, U'x', 1, 3, 0, 0, true, false, 6 , 15 },

    // ACTION GROUP 7: Documentation
    // Subgroup : Genral
    { Commands::CREATE_PAGE,              UITextID::GENERAL_DRAWING, U'x', 1, 3, 0, 0, true, false, 7 , 23 },

    // ACTION GROUP 8: 3D->2D
    // Subgroup : Extraction
    { Commands::GENERAL_DRAWING,        UITextID::GENERAL_DRAWING, U'x', 1, 3, 0, 0, true, false, 8 , 16 },
    { Commands::GENERAL_SHEET,          UITextID::GENERAL_SHEET, U'x', 1, 3, 1, 0, true, false, 8 , 16 },
    { Commands::GENERAL_3D2DGA,         UITextID::GENERAL_3D2DGA, U'x', 1, 3, 2, 0, true, false, 8 , 16 },
    { Commands::GENERAL_ASSEMBLY,       UITextID::GENERAL_ASSEMBLY, U'x', 1, 3, 0, 0, true, false, 8 , 16 },
    { Commands::GENERAL_ISOMETRIC,      UITextID::GENERAL_ISOMETRIC, U'x', 1, 3, 1, 0, true, false, 8 , 16 },
    { Commands::GENERAL_TABLES,         UITextID::GENERAL_TABLES, U'x', 1, 3, 2, 0, true, false, 8 , 16 },

    // ACTION GROUP 9: Time
    // Subgroup : General
    { Commands::SEQUENCE_PLAY,          UITextID::SEQUENCE_PLAY, U'x', 1, 3, 0, 0, true, false, 9 , 23 }, //Dropdown: Play / Pause / Reset to beginning.
    { Commands::STATUS_VISUALIZE,       UITextID::STATUS_VISUALIZE, U'x', 1, 3, 1, 0, true, false, 9 , 23 },

    // ACTION GROUP 10: Cost
	// Subgroup : General
    { Commands::CREATE_BOM,             UITextID::CREATE_BOM, U'x', 1, 3, 0, 0, true, false, 10 , 23 },
    { Commands::REFRESH_BOM,            UITextID::REFRESH_BOM, U'x', 1, 3, 1, 0, true, false, 10 , 23 },
    { Commands::CREATE_REPORTS,         UITextID::CREATE_REPORTS, U'x', 1, 3, 2, 0, true, false, 10 , 23 },
    { Commands::BOM_RATES,              UITextID::BOM_RATES, U'x', 1, 3, 0, 0, true, false, 10 , 23 },

    // ACTION GROUP 11: Utility.
    // Subgroup : Import & Export
    { Commands::IMPORT_STD,             UITextID::IMPORT_STD, U'x', 1, 3, 0, 0, true, true, 11 , 20 },
    { Commands::IMPORT_CII,             UITextID::IMPORT_CII, U'x', 1, 3, 1, 0, true, false, 11 , 20 },
    { Commands::IMPORT_DXF,             UITextID::IMPORT_DXF, U'x', 1, 3, 2, 0, true, true, 11 , 20 },
    { Commands::IMPORT_DWG,             UITextID::IMPORT_DWG, U'x', 1, 3, 0, 0, true, false, 11 , 20 },
    { Commands::EXPORT_STD,             UITextID::EXPORT_STD, U'x', 1, 3, 1, 0, true, false, 11 , 20 },
    { Commands::EXPORT_DWG,             UITextID::EXPORT_DWG, U'x', 1, 3, 2, 0, true, false, 11 , 20 },

    // ACTION GROUP 12: Extensions
    // Subgroup : General
    // All Active Extensions (This will be dynamic in future, but we can hardcode few for now)
    { Commands::SCRIPT_PANNEL,          UITextID::SCRIPT_PANNEL, U'x', 1, 1, 0, 0, true, false, 12 , 23 },
    { Commands::SOFTWARE_UPDATE_CHECK,  UITextID::SOFTWARE_UPDATE_CHECK, UIIconForCommand(Commands::SOFTWARE_UPDATE_CHECK), 1, 1, 0, 0, true, true, 12 , 23 }
};

constexpr size_t TotalUIControls = std::size(AllUIControls);

struct UITopRibbonControlLayout {
    float x = 0.0f;
    float y = 0.0f;
    float width = 0.0f;
    float height = 0.0f;
};

struct UITopRibbonActionGroupLayout {
    float navX = 0.0f;
    float navWidth = 0.0f;
    float contentStartX = 0.0f;
    float contentEndX = 0.0f;
    float contentWidth = 0.0f;
};

struct UITopRibbonSubGroupLayout {
    float contentStartX = 0.0f;
    float contentEndX = 0.0f;
    bool hasControls = false;
};

struct UITopRibbonSubGroupRunLayout {
    uint8_t subGroupIndex = 0;
    float contentStartX = 0.0f;
    float contentEndX = 0.0f;
};

struct UITopRibbonLayout {
    std::array<UITopRibbonControlLayout, TotalUIControls> controls{};
    std::array<UITopRibbonActionGroupLayout, TotalTopUIActionGroups> actionGroups{};
    std::array<UITopRibbonSubGroupLayout, TotalTopUIActionSubGroups> actionSubGroups{};
    std::array<UITopRibbonSubGroupRunLayout, TotalUIControls> actionSubGroupRuns{};
    size_t actionSubGroupRunCount = 0;

    float buttonWidthPx = 0.0f;
    float buttonHeightPx = 0.0f;
    float iconSizePx = 0.0f;
    float textHeightPx = 0.0f;
    float iconReservedWidthPx = 0.0f;
    float textStartOffsetPx = 0.0f;
    float textEndInsetPx = 0.0f;
    float buttonGapPx = 0.0f;
    float tabBarHeightPx = 0.0f;
    float internalTabBarY = 0.0f;
    float internalTabBarHeightPx = 0.0f;
    float actionGroupLabelY = 0.0f;
    float actionGroupLabelHeightPx = 0.0f;
    float topActionGroupY = 0.0f;
    float actionSubGroupLabelY = 0.0f;
    float topUITotalHeightPx = 0.0f;
    float roundedCornerRadiusPx = 0.0f;
    float uiTextScale = 1.0f;
    float totalContentWidthPx = 0.0f;
    float actionGroupNavTotalWidthPx = 0.0f;
    float scrollOffsetPx = 0.0f;
    float dpiX = 0.0f;
    float dpiY = 0.0f;
    bool isValid = false;
};

// ---------- Platform-agnostic UI overlay interface (implemented in UserInterface.cpp) ----------
// Everything below only fills CPU-side arrays (AtlasBitmap pixels, UIDrawContext vertex/index
// streams) and emits UIActions. The platform half (UserInterface-<Platform>.cpp) uploads the
// atlases, owns the PSOs / dynamic buffers and issues the actual draw calls.

struct DX12ResourcesUI; // Platform GPU resources; full definition in UserInterface-<Platform>.h.
struct SingleUIWindow;  // विश्वकर्मा.h
struct IconAtlasCPU;    // Per-monitor icon glyph lookup + metadata; defined in UserInterface.cpp.

struct UIDrawContext { // Draw context
    UIVertex* vertexPtr;
    uint16_t* indexPtr;
    uint32_t vertexCount, indexCount;
    // Icon lookup/metadata for the monitor this frame is being recorded for. Set by BuildUIOverlay;
    // read by PushIcon / PushRoundedRectangle. Never dereferenced when null.
    const IconAtlasCPU* iconData = nullptr;
};

// CPU-side atlas bitmap builders (MSDF font + icons). Uploaded by the platform InitUIResources /
// BuildMonitorIconAtlas. The icon atlas cell size (px) is per monitor; BuildIconAtlas fills `out`.
AtlasBitmap BuildIconAtlas(int iconCellSizePx, IconAtlasCPU& out);
AtlasBitmap BuildMSDFFontAtlas();

// Storage accessor for a monitor's icon CPU bundle (lookup + metadata). The array lives in
// UserInterface.cpp; the platform half writes it via BuildIconAtlas and BuildUIOverlay reads it.
IconAtlasCPU& MonitorIconAtlasCPU(int monitorId);

void PrecomputeTopRibbonLayout(UITopRibbonLayout& layout, float monitorDPIX, float monitorDPIY);

// Quad / text tessellation: append vertices+indices into ctx (bounds-checked via uiRes limits).
void PushRect(UIDrawContext& ctx, float x, float y, float w, float h, uint32_t color, DX12ResourcesUI& uiRes);
void PushRoundedRectangle(UIDrawContext& ctx, float x, float y, float w, float h, float radiusPx,
    uint32_t color, DX12ResourcesUI& uiRes);
void PushTopRoundedRectangle(UIDrawContext& ctx, float x, float y, float w, float h, float radiusPx,
    uint32_t color, DX12ResourcesUI& uiRes);
void PushText(UIDrawContext& ctx, float x, float y, const char* text, uint32_t color, DX12ResourcesUI& uiRes);

// Widget primitives shared by BuildUIDropdown and the Application Tab's content panel
// (ApplicationTab.cpp). Unlike raw PushRect they advance the vertex/index counters themselves.
void PushWidgetRect(UIDrawContext& ctx, DX12ResourcesUI& uiRes, float x, float y, float w, float h,
    uint32_t color);
// ASCII text scaled by textScale, clipped to maxWidth, baseline at baselineY.
void PushWidgetText(UIDrawContext& ctx, DX12ResourcesUI& uiRes, float x, float baselineY,
    const char* text, float maxWidth, uint32_t color, float textScale);
float WidgetTextBaselineY(float y, float h, float textScale);

// Reusable dropdown: draws a closed field at (x, y, width, rowHeightPx) showing items[selectedIndex]
// and, while open, the item list below it. Handles its own hit-testing against input and returns
// the (possibly changed) selected index (-1 when itemCount == 0). ASCII item labels only.
int BuildUIDropdown(UIDrawContext& ctx, DX12ResourcesUI& uiRes, const UIInput& input,
    UIDropdownState& state, float x, float y, float width, float rowHeightPx, float textScale,
    const char* const* items, int itemCount, int selectedIndex);

// Launch splash trigger. wWinMain stores GetTickCount64() once, after the GPU engine and every
// monitor's icon atlas are up; BuildUIOverlay draws the credit card until 5 s later, then clears
// this back to 0. 0 = nothing to draw.
extern std::atomic<uint64_t> g_splashOverlayStartTick;

// Portable half of RenderUIOverlay: widget layout + hit-testing for the whole overlay. Fills ctx
// with the frame's UI geometry and emits UIActions; the platform wrapper draws ctx afterwards.
void BuildUIOverlay(SingleUIWindow& window, UIDrawContext& ctx, DX12ResourcesUI& uiRes,
    UITopRibbonLayout& topRibbonLayout, float monitorDPIX, float monitorDPIY, const UIInput& input,
    uint64_t activeInternalSubTabMemoryId, int monitorId);
