// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
//
// VishwakarmaExtension.exe - the out-of-process CPython worker that runs extensions
// (importers / exporters / plugins). Design: website/content/software/extensions.md
//
// A single self-contained executable: CPython 3.13 is statically linked (built by
// code-miscellaneous/BuildCPython.ps1 from the pinned code-external/cpython submodule)
// and the entire usable stdlib plus the google.protobuf pure-Python runtime is frozen
// into the binary. No python313.dll, no Lib\ folder, no dependence on any Python
// installed on the user's machine.
//
// The host (ExtensionCommunications.cpp) launches it as
//     VishwakarmaExtension.exe main.py
// with the extension's folder as the working directory and the IPC pipes on
// stdin/stdout. The worker is one-shot: it runs the extension entry script and exits.
//
// Defense-in-depth applied here, ahead of the planned AppContainer sandbox:
//   - Networking does not exist: _socket / select / _ssl were never compiled in and
//     socket.py / ssl.py are not frozen in, so "import socket" raises ImportError.
//   - The builtin module table below removes _winapi, winreg, mmap and msvcrt.
//   - Process-creation primitives (nt.system / spawn* / exec* / startfile / kill) are
//     deleted by an extra Py_mod_exec slot spliced into the nt module definition, so
//     every creation of the module - including a re-import after deleting
//     sys.modules['nt'] - comes up scrubbed. subprocess/multiprocessing are not frozen in.
//   - File I/O intentionally remains available (_io drives the IPC pipes and module
//     loading); confining WHAT is reachable on disk is the AppContainer's job.

#include <Python.h>

#include <cstdio>
#include <cstdlib>
#include <cwchar>

// ------------------------------------------------------------------ Builtin modules
// Curated copy of the pinned CPython's PC/config.c inittab. Removed relative to stock:
// _winapi, winreg, mmap, msvcrt, _lsprof, xxsubtype, _interpreters, _interpchannels,
// _interpqueues. "nt" must stay: the frozen importlib bootstrap requires it on Windows.
extern "C" {
PyObject* PyInit__abc(void);
PyObject* PyInit_array(void);
PyObject* PyInit__ast(void);
PyObject* PyInit_binascii(void);
PyObject* PyInit_cmath(void);
PyObject* PyInit_errno(void);
PyObject* PyInit_faulthandler(void);
PyObject* PyInit_gc(void);
PyObject* PyInit_math(void);
PyObject* PyInit_nt(void);
PyObject* PyInit__operator(void);
PyObject* PyInit__signal(void);
PyObject* PyInit__md5(void);
PyObject* PyInit__sha1(void);
PyObject* PyInit__sha2(void);
PyObject* PyInit__sha3(void);
PyObject* PyInit__blake2(void);
PyObject* PyInit__sysconfig(void);
PyObject* PyInit_time(void);
PyObject* PyInit__thread(void);
PyObject* PyInit__tokenize(void);
PyObject* PyInit__typing(void);
PyObject* PyInit__statistics(void);
PyObject* PyInit__locale(void);
PyObject* PyInit__tracemalloc(void);
PyObject* PyInit__codecs(void);
PyObject* PyInit__weakref(void);
PyObject* PyInit__random(void);
PyObject* PyInit__bisect(void);
PyObject* PyInit__heapq(void);
PyObject* PyInit_itertools(void);
PyObject* PyInit__collections(void);
PyObject* PyInit__symtable(void);
PyObject* PyInit__csv(void);
PyObject* PyInit__sre(void);
PyObject* PyInit__struct(void);
PyObject* PyInit__datetime(void);
PyObject* PyInit__functools(void);
PyObject* PyInit__json(void);
PyObject* PyInit__suggestions(void);
PyObject* PyInit_zlib(void);
PyObject* PyInit__multibytecodec(void);
PyObject* PyInit__codecs_cn(void);
PyObject* PyInit__codecs_hk(void);
PyObject* PyInit__codecs_iso2022(void);
PyObject* PyInit__codecs_jp(void);
PyObject* PyInit__codecs_kr(void);
PyObject* PyInit__codecs_tw(void);
PyObject* PyMarshal_Init(void);
PyObject* PyInit__imp(void);
PyObject* _PyWarnings_Init(void);
PyObject* PyInit__string(void);
PyObject* PyInit__io(void);
PyObject* PyInit__pickle(void);
PyObject* PyInit_atexit(void);
PyObject* PyInit__stat(void);
PyObject* PyInit__opcode(void);
PyObject* PyInit__contextvars(void);

// Generated by BuildCPython.ps1: the curated frozen stdlib + google.protobuf table.
extern const struct _frozen VkExtraFrozenModules[];
}

// ------------------------------------------------------------------ nt hardening
// posixmodule uses multi-phase init: PyInit_nt returns a PyModuleDef whose exec slots
// populate the module. We hand out a copy of that def with one extra exec slot appended
// that deletes the process-creation primitives. The interpreter copies the inittab at
// startup, so this wrapper - not a post-init fixup - is what makes the scrub stick
// across re-imports.
static const char* kVkNtRemovedFunctions[] = {
    "system", "spawnv", "spawnve", "execv", "execve", "startfile", "kill",
    "_add_dll_directory", "_remove_dll_directory", nullptr
};

static int VkNtScrubExec(PyObject* module) {
    PyObject* dict = PyModule_GetDict(module);  // Borrowed reference.
    for (const char** name = kVkNtRemovedFunctions; *name; ++name) {
        if (PyDict_DelItemString(dict, *name) < 0) PyErr_Clear();  // Absent is fine.
    }
    return 0;
}

static PyModuleDef vkNtDef;
static PyModuleDef_Slot vkNtSlots[16];

static PyObject* PyInit_vk_nt(void) {
    PyObject* original = PyInit_nt();
    if (!original) return nullptr;
    if (PyModule_Check(original)) {  // Single-phase fallback: scrub directly.
        VkNtScrubExec(original);
        return original;
    }
    static bool copied = false;
    if (!copied) {
        PyModuleDef* def = reinterpret_cast<PyModuleDef*>(original);
        vkNtDef = *def;
        int count = 0;
        if (def->m_slots) {
            for (; def->m_slots[count].slot; ++count) {
                if (count >= 14) { fwprintf(stderr, L"VishwakarmaExtension: nt slot table overflow\n"); return nullptr; }
                vkNtSlots[count] = def->m_slots[count];
            }
        }
        vkNtSlots[count].slot = Py_mod_exec;
        vkNtSlots[count].value = reinterpret_cast<void*>(&VkNtScrubExec);
        vkNtSlots[count + 1] = { 0, nullptr };
        vkNtDef.m_slots = vkNtSlots;
        copied = true;
    }
    return reinterpret_cast<PyObject*>(&vkNtDef);
}

static struct _inittab vkBuiltinModules[] = {
    {"_abc", PyInit__abc},
    {"array", PyInit_array},
    {"_ast", PyInit__ast},
    {"binascii", PyInit_binascii},
    {"cmath", PyInit_cmath},
    {"errno", PyInit_errno},
    {"faulthandler", PyInit_faulthandler},
    {"gc", PyInit_gc},
    {"math", PyInit_math},
    {"nt", PyInit_vk_nt},
    {"_operator", PyInit__operator},
    {"_signal", PyInit__signal},
    {"_md5", PyInit__md5},
    {"_sha1", PyInit__sha1},
    {"_sha2", PyInit__sha2},
    {"_sha3", PyInit__sha3},
    {"_blake2", PyInit__blake2},
    {"_sysconfig", PyInit__sysconfig},
    {"time", PyInit_time},
    {"_thread", PyInit__thread},
    {"_tokenize", PyInit__tokenize},
    {"_typing", PyInit__typing},
    {"_statistics", PyInit__statistics},
    {"_locale", PyInit__locale},
    {"_tracemalloc", PyInit__tracemalloc},
    {"_codecs", PyInit__codecs},
    {"_weakref", PyInit__weakref},
    {"_random", PyInit__random},
    {"_bisect", PyInit__bisect},
    {"_heapq", PyInit__heapq},
    {"itertools", PyInit_itertools},
    {"_collections", PyInit__collections},
    {"_symtable", PyInit__symtable},
    {"_csv", PyInit__csv},
    {"_sre", PyInit__sre},
    {"_struct", PyInit__struct},
    {"_datetime", PyInit__datetime},
    {"_functools", PyInit__functools},
    {"_json", PyInit__json},
    {"_suggestions", PyInit__suggestions},
    {"zlib", PyInit_zlib},
    {"_multibytecodec", PyInit__multibytecodec},
    {"_codecs_cn", PyInit__codecs_cn},
    {"_codecs_hk", PyInit__codecs_hk},
    {"_codecs_iso2022", PyInit__codecs_iso2022},
    {"_codecs_jp", PyInit__codecs_jp},
    {"_codecs_kr", PyInit__codecs_kr},
    {"_codecs_tw", PyInit__codecs_tw},
    {"marshal", PyMarshal_Init},
    {"_imp", PyInit__imp},
    {"builtins", nullptr},
    {"sys", nullptr},
    {"_warnings", _PyWarnings_Init},
    {"_string", PyInit__string},
    {"_io", PyInit__io},
    {"_pickle", PyInit__pickle},
    {"atexit", PyInit_atexit},
    {"_stat", PyInit__stat},
    {"_opcode", PyInit__opcode},
    {"_contextvars", PyInit__contextvars},
    {nullptr, nullptr}
};

int wmain(int argc, wchar_t** argv) {
    if (argc < 2) {
        fwprintf(stderr, L"usage: VishwakarmaExtension.exe <entry-script.py> [args...]\n");
        return 2;
    }

    // Both tables must be in place before the interpreter initializes.
    PyImport_Inittab = vkBuiltinModules;
    PyImport_FrozenModules = VkExtraFrozenModules;

    PyStatus status;
    PyPreConfig preConfig;
    PyPreConfig_InitIsolatedConfig(&preConfig);
    preConfig.utf8_mode = 1;
    status = Py_PreInitialize(&preConfig);
    if (PyStatus_Exception(status)) Py_ExitStatusException(status);

    // The entry script's directory is the only on-disk import location: an extension
    // package is exactly one folder (main.py plus sibling modules). The stdlib comes
    // from the frozen tables only.
    wchar_t scriptPath[4096];
    if (_wfullpath(scriptPath, argv[1], 4096) == nullptr) {
        fwprintf(stderr, L"VishwakarmaExtension: cannot resolve path '%s'\n", argv[1]);
        return 2;
    }
    wchar_t scriptDir[4096];
    wcscpy_s(scriptDir, scriptPath);
    wchar_t* lastSlash = wcsrchr(scriptDir, L'\\');
    if (!lastSlash) lastSlash = wcsrchr(scriptDir, L'/');
    if (lastSlash) *lastSlash = L'\0';

    PyConfig config;
    PyConfig_InitIsolatedConfig(&config);
    config.buffered_stdio = 0;  // stdin/stdout are the IPC pipes; never buffer them.
    config.write_bytecode = 0;  // No __pycache__ in the installation directory.
    config.parse_argv = 0;
    config.site_import = 0;     // No site-packages exist; everything usable is frozen in.

    status = PyConfig_SetString(&config, &config.program_name, L"VishwakarmaExtension");
    if (!PyStatus_Exception(status))
        status = PyConfig_SetString(&config, &config.run_filename, scriptPath);
    if (!PyStatus_Exception(status))
        status = PyConfig_SetArgv(&config, argc - 1, argv + 1);
    if (!PyStatus_Exception(status)) {
        config.module_search_paths_set = 1;
        status = PyWideStringList_Append(&config.module_search_paths, scriptDir);
    }
    if (!PyStatus_Exception(status))
        status = Py_InitializeFromConfig(&config);
    PyConfig_Clear(&config);
    if (PyStatus_Exception(status)) Py_ExitStatusException(status);

    return Py_RunMain();  // Runs the entry script, finalizes, returns the exit code.
}
