# Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
# Writes VersionGenerated.h (VS_VERSION_INFO macros) into -OutDir so that Vishwakarma.rc and
# VishwakarmaSetup.rc can embed the version number, git commit hash and build date into the exe's
# Windows version resource (Right-click -> Properties -> Details). Called from each project's
# pre-build event. The file is only rewritten when its contents change, so unchanged same-day
# builds don't force a needless resource recompile.

param(
    [Parameter(Mandatory = $true)][string]$OutDir
)

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path

# version = git commit count (same scheme as GenerateRelease.ps1); 0 marks a build with no git.
Push-Location $repoRoot
try {
    $version = 0
    $hash = "00000000"
    try {
        $version = [int](git rev-list --count HEAD 2>$null)
        $hash = (git rev-parse --short=8 HEAD 2>$null).Trim()
    } catch {}
}
finally { Pop-Location }

$buildDate = [DateTime]::UtcNow.ToString("yyyy-MM-dd")

$content = @"
// Generated by code-miscellaneous/GenerateVersionHeader.ps1 - do not edit.
#define VW_VERSION_NUM        $version
#define VW_FILEVERSION        0,0,0,$version
#define VW_FILEVERSION_STR    "$version"
#define VW_PRODUCTVERSION_STR "$version ($hash, $buildDate)"
#define VW_COMMENTS_STR       "Version $version, commit $hash, built $buildDate UTC"
"@

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$path = Join-Path $OutDir "VersionGenerated.h"
$utf8 = New-Object System.Text.UTF8Encoding $false
if (-not (Test-Path $path) -or ([System.IO.File]::ReadAllText($path) -ne $content)) {
    [System.IO.File]::WriteAllText($path, $content, $utf8)
    Write-Host "Wrote $path (version $version, $hash, $buildDate)"
}
