# Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
# This file was originally generated by AI (Codex, GPT5.5 Extra High Quality).
# The purpose of this file is to provide interoperability with .std files, 
# allowing for reading and parsing of .std input sections into structured data.
# Apparently this pure python file is parsing the .std file faster than the original software!
"""
Pure Python .std reader.

The reader is intentionally data-oriented: it parses the common input
sections into dictionaries and lists, while retaining source line numbers and
raw records so the same model can later be used as the basis for a writer.

Current coverage includes:
    - job information and units
    - joint coordinates
    - member incidences
    - element/plate incidences
    - group definitions
    - materials
    - member property/profile assignments
    - constants/material assignments
    - supports
    - member releases, offsets, fireproofing and truss/tension/compression lists
    - plane-stress element lists and inactive member commands
    - wind definition blocks (raw records retained)
    - load cases (incl. floor/oneway/reference load items), reference loads,
      load combinations and combination entries
    - steel/concrete design parameter blocks

Example:
    python code-miscellaneous/InteroperabilityWithSTDFile.py --file build/model.std
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple, Union


LoadId = Union[int, str]

_INT_RE = re.compile(r"^[+-]?\d+$")
_FLOAT_RE = re.compile(r"^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][+-]?\d+)?$")

# A malformed "1 TO 999999999" range would otherwise exhaust memory on expansion.
_MAX_RANGE_SPAN = 1_000_000

_FORCE_COMPONENTS = {"FX", "FY", "FZ", "MX", "MY", "MZ"}
_DIRECTIONS = {"X", "Y", "Z", "GX", "GY", "GZ"}
_MEMBER_LOAD_MODES = {
    "UNI",
    "UMOM",
    "CON",
    "CMOM",
    "TRAP",
    "LIN",
    "TEMP",
    "STRAIN",
    "PRESTRESS",
    "POSTSTRESS",
}
_PROPERTY_MARKERS = {"TABLE", "PRIS", "TAPERED", "UPTABLE", "GENERAL"}
_TARGET_SELECTORS = {
    "ALL",
    "MEMB",
    "MEMBER",
    "JOINT",
    "ELEMENT",
    "PLATE",
    "GROUP",
    "LIST",
}
_SUPPORT_TYPES = {
    "FIXED",
    "PINNED",
    "ENFORCED",
    "INCLINED",
    "ELASTIC",
    "MULTILINEAR",
    "SPRING",
    "FOUNDATION",
}
_ELEMENT_PROPERTY_MARKERS = {"THICKNESS", "MATERIAL", "PRIS", "ELEMENT", "PLATE"}

_LENGTH_TO_METER = {
    "M": 1.0,
    "METER": 1.0,
    "METERS": 1.0,
    "METRE": 1.0,
    "METRES": 1.0,
    "CM": 0.01,
    "CENTIMETER": 0.01,
    "CENTIMETERS": 0.01,
    "CENTIMETRE": 0.01,
    "CENTIMETRES": 0.01,
    "MM": 0.001,
    "MMS": 0.001,
    "MILLIMETER": 0.001,
    "MILLIMETERS": 0.001,
    "MILLIMETRE": 0.001,
    "MILLIMETRES": 0.001,
    "IN": 0.0254,
    "INCH": 0.0254,
    "INCHES": 0.0254,
    "FT": 0.3048,
    "FEET": 0.3048,
    "FOOT": 0.3048,
}

_FORCE_TO_NEWTON = {
    "N": 1.0,
    "NEWTON": 1.0,
    "NEWTONS": 1.0,
    "KN": 1000.0,
    "KNS": 1000.0,
    "KG": 9.80665,
    "KGS": 9.80665,
    "KGF": 9.80665,
    "MTON": 9806.65,
    "MTONS": 9806.65,
    "TON": 9806.65,
    "TONS": 9806.65,
    "TONNE": 9806.65,
    "TONNES": 9806.65,
    "LB": 4.4482216152605,
    "LBS": 4.4482216152605,
    "POUND": 4.4482216152605,
    "POUNDS": 4.4482216152605,
    "KIP": 4448.2216152605,
    "KIPS": 4448.2216152605,
}

_LENGTH_DESIGN_PARAMETERS = {
    "CLEAR",
    "DMAX",
    "DMIN",
    "ELB",
    "ELT",
    "ELY",
    "ELZ",
    "LX",
    "LY",
    "LZ",
    "SMAIN",
    "SSEC",
    "ULY",
    "ULZ",
    "UNB",
    "UNL",
    "UNT",
}

_PRESSURE_DESIGN_PARAMETERS = {
    "FC",
    "FPC",
    "FU",
    "FYLD",
    "FYMAIN",
    "FYSEC",
    "PC",
}


@dataclass
class LogicalRecord:
    text: str
    start_line: int
    end_line: int
    raw_lines: List[str] = field(default_factory=list)


@dataclass
class STDModel:
    path: Path
    data_type: str = ""
    title: str = ""
    job_information: Dict[str, str] = field(default_factory=dict)
    input_width: Optional[int] = None
    units: List[Dict[str, Any]] = field(default_factory=list)
    unit_context_by_line: Dict[int, Optional[Dict[str, Any]]] = field(
        default_factory=dict
    )
    nodes: Dict[int, Tuple[float, float, float]] = field(default_factory=dict)
    nodes_si: Dict[int, Tuple[float, float, float]] = field(default_factory=dict)
    node_source_lines: Dict[int, int] = field(default_factory=dict)
    members: Dict[int, Tuple[int, int]] = field(default_factory=dict)
    plates: Dict[int, Tuple[int, ...]] = field(default_factory=dict)
    groups: Dict[str, Dict[str, Dict[str, Any]]] = field(
        default_factory=lambda: {
            "MEMBER": {},
            "ELEMENT": {},
            "JOINT": {},
            "FLOOR": {},
        }
    )
    materials: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    user_tables: List[Dict[str, Any]] = field(default_factory=list)
    member_properties: List[Dict[str, Any]] = field(default_factory=list)
    member_profile_by_member: Dict[int, Dict[str, Any]] = field(default_factory=dict)
    element_properties: List[Dict[str, Any]] = field(default_factory=list)
    element_property_by_element: Dict[int, Dict[str, Any]] = field(default_factory=dict)
    pmembers: Dict[int, Dict[str, Any]] = field(default_factory=dict)
    pmember_by_member: Dict[int, int] = field(default_factory=dict)
    constants: List[Dict[str, Any]] = field(default_factory=list)
    supports: List[Dict[str, Any]] = field(default_factory=list)
    support_nodes: List[int] = field(default_factory=list)
    member_releases: List[Dict[str, Any]] = field(default_factory=list)
    member_offsets: List[Dict[str, Any]] = field(default_factory=list)
    member_fireproofing: List[Dict[str, Any]] = field(default_factory=list)
    member_truss: List[Dict[str, Any]] = field(default_factory=list)
    member_tension: List[Dict[str, Any]] = field(default_factory=list)
    member_compression: List[Dict[str, Any]] = field(default_factory=list)
    element_plane_stress: List[Dict[str, Any]] = field(default_factory=list)
    wind_definitions: List[Dict[str, Any]] = field(default_factory=list)
    loads: Dict[LoadId, Dict[str, Any]] = field(default_factory=dict)
    reference_loads: Dict[LoadId, Dict[str, Any]] = field(default_factory=dict)
    load_case_order: List[LoadId] = field(default_factory=list)
    reference_load_order: List[LoadId] = field(default_factory=list)
    load_combinations: Dict[int, Dict[str, Any]] = field(default_factory=dict)
    load_combination_order: List[int] = field(default_factory=list)
    load_envelopes: List[Dict[str, Any]] = field(default_factory=list)
    design_blocks: List[Dict[str, Any]] = field(default_factory=list)
    design_parameters: List[Dict[str, Any]] = field(default_factory=list)
    design_parameters_by_member: Dict[int, List[Dict[str, Any]]] = field(
        default_factory=dict
    )
    design_parameters_by_group: Dict[str, List[Dict[str, Any]]] = field(
        default_factory=dict
    )
    analysis_commands: List[Dict[str, Any]] = field(default_factory=list)
    comments: List[Dict[str, Any]] = field(default_factory=list)
    unparsed_records: List[Dict[str, Any]] = field(default_factory=list)
    records: List[LogicalRecord] = field(default_factory=list)

    def to_dict(self, include_records: bool = False) -> Dict[str, Any]:
        data = {
            "path": str(self.path),
            "data_type": self.data_type,
            "title": self.title,
            "job_information": self.job_information,
            "input_width": self.input_width,
            "units": self.units,
            "unit_context_by_line": self.unit_context_by_line,
            "nodes": self.nodes,
            "nodes_si": self.nodes_si,
            "node_source_lines": self.node_source_lines,
            "members": self.members,
            "plates": self.plates,
            "groups": self.groups,
            "materials": self.materials,
            "user_tables": self.user_tables,
            "member_properties": self.member_properties,
            "member_profile_by_member": self.member_profile_by_member,
            "element_properties": self.element_properties,
            "element_property_by_element": self.element_property_by_element,
            "pmembers": self.pmembers,
            "pmember_by_member": self.pmember_by_member,
            "constants": self.constants,
            "supports": self.supports,
            "support_nodes": self.support_nodes,
            "member_releases": self.member_releases,
            "member_offsets": self.member_offsets,
            "member_fireproofing": self.member_fireproofing,
            "member_truss": self.member_truss,
            "member_tension": self.member_tension,
            "member_compression": self.member_compression,
            "element_plane_stress": self.element_plane_stress,
            "wind_definitions": self.wind_definitions,
            "loads": self.loads,
            "reference_loads": self.reference_loads,
            "load_case_order": self.load_case_order,
            "reference_load_order": self.reference_load_order,
            "load_combinations": self.load_combinations,
            "load_combination_order": self.load_combination_order,
            "load_envelopes": self.load_envelopes,
            "design_blocks": self.design_blocks,
            "design_parameters": self.design_parameters,
            "design_parameters_by_member": self.design_parameters_by_member,
            "design_parameters_by_group": self.design_parameters_by_group,
            "analysis_commands": self.analysis_commands,
            "comments": self.comments,
            "unparsed_records": self.unparsed_records,
        }
        if include_records:
            data["records"] = [
                {
                    "text": record.text,
                    "start_line": record.start_line,
                    "end_line": record.end_line,
                    "raw_lines": record.raw_lines,
                }
                for record in self.records
            ]
        return data


def _clean_token(token: str) -> str:
    return token.strip().strip(",")


def _is_int_token(token: str) -> bool:
    return bool(_INT_RE.match(_clean_token(token)))


def _is_float_token(token: str) -> bool:
    return bool(_FLOAT_RE.match(_clean_token(token)))


def _to_number(token: str) -> Any:
    cleaned = _clean_token(token)
    if _is_int_token(cleaned):
        return int(cleaned)
    if _is_float_token(cleaned):
        return float(cleaned)
    return cleaned


def _parse_load_id(token: str) -> LoadId:
    cleaned = _clean_token(token)
    if _is_int_token(cleaned):
        return int(cleaned)
    return cleaned


def _expand_range(start: int, end: int) -> Iterable[int]:
    if end >= start:
        return range(start, end + 1)
    return range(start, end - 1, -1)


def parse_id_spec(tokens: Iterable[str]) -> Dict[str, Any]:
    cleaned_tokens = [_clean_token(token) for token in tokens if _clean_token(token)]
    ids: List[int] = []
    seen_ids: set = set()
    ranges: List[Tuple[int, int]] = []
    groups: List[str] = []
    unparsed: List[str] = []
    all_selected = False

    i = 0
    while i < len(cleaned_tokens):
        token = cleaned_tokens[i]
        upper = token.upper()

        if upper in {"MEMB", "MEMBER", "JOINT", "ELEMENT", "PLATE", "LIST"}:
            i += 1
            continue

        if upper == "ALL":
            all_selected = True
            i += 1
            continue

        if token.startswith("_"):
            groups.append(token)
            i += 1
            continue

        if _is_int_token(token):
            start = int(token)
            if (
                i + 2 < len(cleaned_tokens)
                and cleaned_tokens[i + 1].upper() == "TO"
                and _is_int_token(cleaned_tokens[i + 2])
            ):
                end = int(cleaned_tokens[i + 2])
                ranges.append((start, end))
                if abs(end - start) <= _MAX_RANGE_SPAN:
                    for value in _expand_range(start, end):
                        if value not in seen_ids:
                            seen_ids.add(value)
                            ids.append(value)
                i += 3
            else:
                if start not in seen_ids:
                    seen_ids.add(start)
                    ids.append(start)
                i += 1
            continue

        if upper == "TO":
            unparsed.append(token)
            i += 1
            continue

        unparsed.append(token)
        i += 1

    return {
        "raw": " ".join(cleaned_tokens),
        "ids": ids,
        "ranges": ranges,
        "groups": groups,
        "all": all_selected,
        "unparsed": unparsed,
    }


def _target_kind_from_selector(selector: str, default: Optional[str] = None) -> str:
    upper = selector.upper()
    if upper in {"MEMB", "MEMBER", "LIST"}:
        return default or "MEMBER"
    if upper == "JOINT":
        return "JOINT"
    if upper in {"ELEMENT", "PLATE"}:
        return "ELEMENT"
    if upper == "GROUP":
        return "GROUP"
    if upper == "ALL":
        return default or "ALL"
    return default or "UNKNOWN"


def _read_text(path: Path) -> str:
    encodings = ("utf-8-sig", "utf-8", "cp1252", "latin-1")
    last_error: Optional[Exception] = None
    for encoding in encodings:
        try:
            return path.read_text(encoding=encoding)
        except UnicodeDecodeError as exc:
            last_error = exc
    if last_error:
        raise last_error
    return path.read_text()


def _logical_records_from_text(text: str) -> Tuple[List[LogicalRecord], List[Dict[str, Any]]]:
    records: List[LogicalRecord] = []
    comments: List[Dict[str, Any]] = []
    current_parts: List[str] = []
    current_raw: List[str] = []
    current_start: Optional[int] = None

    for line_number, raw_line in enumerate(text.splitlines(), start=1):
        stripped = raw_line.strip()
        if not stripped:
            continue

        # "*" starts a comment; "<!" / "!>" bracket GUI-generated data blocks.
        if stripped.startswith(("*", "<!", "!>")):
            comments.append({"line": line_number, "text": stripped})
            continue

        if current_start is None:
            current_start = line_number

        continuation = stripped.endswith("-")
        if continuation:
            stripped = stripped[:-1].rstrip()

        current_parts.append(stripped)
        current_raw.append(raw_line)

        if continuation:
            continue

        combined = re.sub(r"\s+", " ", " ".join(current_parts)).strip()
        if combined:
            for part in combined.split(";"):
                record_text = re.sub(r"\s+", " ", part.strip())
                if record_text:
                    records.append(
                        LogicalRecord(
                            text=record_text,
                            start_line=current_start,
                            end_line=line_number,
                            raw_lines=list(current_raw),
                        )
                    )
        current_parts = []
        current_raw = []
        current_start = None

    if current_parts and current_start is not None:
        combined = re.sub(r"\s+", " ", " ".join(current_parts)).strip()
        for part in combined.split(";"):
            record_text = re.sub(r"\s+", " ", part.strip())
            if record_text:
                records.append(
                    LogicalRecord(
                        text=record_text,
                        start_line=current_start,
                        end_line=current_start + len(current_raw) - 1,
                        raw_lines=list(current_raw),
                    )
                )

    return records, comments


def _split_at_first_marker(
    tokens: List[str], markers: Iterable[str]
) -> Tuple[List[str], List[str]]:
    marker_set = {marker.upper() for marker in markers}
    for index, token in enumerate(tokens):
        if token.upper() in marker_set:
            return tokens[:index], tokens[index:]
    return tokens, []


def _parse_key_value_pairs(tokens: List[str]) -> Dict[str, Any]:
    values: Dict[str, Any] = {}
    index = 0
    while index < len(tokens):
        key = tokens[index].upper()
        if index + 1 < len(tokens):
            values[key] = _to_number(tokens[index + 1])
            index += 2
        else:
            values[key] = True
            index += 1
    return values


def _canonical_unit(token: Optional[str]) -> Optional[str]:
    if token is None:
        return None
    cleaned = _clean_token(token).upper().replace(".", "")
    return cleaned or None


def _parse_unit_record(text: str, line: int) -> Dict[str, Any]:
    tokens = text.split()
    length = tokens[1] if len(tokens) > 1 else None
    force = tokens[2] if len(tokens) > 2 else None
    length_key = _canonical_unit(length)
    force_key = _canonical_unit(force)
    length_factor = _LENGTH_TO_METER.get(length_key or "")
    force_factor = _FORCE_TO_NEWTON.get(force_key or "")

    unknown_units = []
    if length_key and length_factor is None:
        unknown_units.append(length)
    if force_key and force_factor is None:
        unknown_units.append(force)

    return {
        "line": line,
        "raw": text,
        "length": length,
        "force": force,
        "length_unit": length_key,
        "force_unit": force_key,
        "length_factor_to_meter": length_factor,
        "force_factor_to_newton": force_factor,
        "tokens": tokens[1:],
        "si_units": {
            "length": "m",
            "force": "N",
            "moment": "N*m",
            "pressure": "Pa",
            "force_per_length": "N/m",
            "force_per_volume": "N/m^3",
        },
        "unknown_units": unknown_units,
    }


def _copy_unit_context(
    context: Optional[Dict[str, Any]]
) -> Optional[Dict[str, Any]]:
    if context is None:
        return None
    return {
        "line": context.get("line"),
        "raw": context.get("raw"),
        "length": context.get("length"),
        "force": context.get("force"),
        "length_unit": context.get("length_unit"),
        "force_unit": context.get("force_unit"),
        "length_factor_to_meter": context.get("length_factor_to_meter"),
        "force_factor_to_newton": context.get("force_factor_to_newton"),
    }


def _quantity_factor(
    unit_context: Optional[Dict[str, Any]], quantity: str
) -> Optional[float]:
    if unit_context is None:
        return None

    length = unit_context.get("length_factor_to_meter")
    force = unit_context.get("force_factor_to_newton")
    if quantity == "length":
        return length
    if quantity == "area":
        return length * length if length is not None else None
    if quantity == "volume":
        return length * length * length if length is not None else None
    if quantity == "force":
        return force
    if quantity == "moment":
        if force is None or length is None:
            return None
        return force * length
    if quantity == "force_per_length":
        if force is None or length is None:
            return None
        return force / length
    if quantity == "moment_per_length":
        return force
    if quantity == "pressure":
        if force is None or length is None:
            return None
        return force / (length * length)
    if quantity == "force_per_volume":
        if force is None or length is None:
            return None
        return force / (length * length * length)
    if quantity == "dimensionless":
        return 1.0
    return None


def _numeric_to_si(value: Any, factor: Optional[float]) -> Any:
    if factor is None:
        return value
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return float(value) * factor
    if isinstance(value, list):
        return [_numeric_to_si(item, factor) for item in value]
    if isinstance(value, tuple):
        return tuple(_numeric_to_si(item, factor) for item in value)
    if isinstance(value, dict):
        return {key: _numeric_to_si(item, factor) for key, item in value.items()}
    return value


def _with_unit_context(data: Dict[str, Any], context: Optional[Dict[str, Any]]) -> None:
    copied = _copy_unit_context(context)
    if copied is not None:
        data["unit_context"] = copied


def _find_target_selector(tokens: List[str]) -> Optional[int]:
    for index, token in enumerate(tokens):
        upper = token.upper()
        if upper in _TARGET_SELECTORS or token.startswith("_"):
            return index
    return None


def _parse_parameter_record(
    text: str,
    line: int,
    block_id: Union[int, str],
    context: str,
    default_target_kind: Optional[str] = "MEMBER",
) -> Dict[str, Any]:
    tokens = text.split()
    upper_tokens = [token.upper() for token in tokens]

    if upper_tokens[:2] == ["CHECK", "CODE"]:
        name = "CHECK CODE"
        rest = tokens[2:]
    elif upper_tokens[:4] == ["STEEL", "MEMBER", "TAKE", "OFF"]:
        name = "STEEL MEMBER TAKE OFF"
        rest = tokens[4:]
    elif upper_tokens[:3] == ["STEEL", "TAKE", "OFF"]:
        name = "STEEL TAKE OFF"
        rest = tokens[3:]
    elif upper_tokens[:3] == ["CONCRETE", "TAKE", "OFF"]:
        name = "CONCRETE TAKE OFF"
        rest = tokens[3:]
    elif upper_tokens[:2] == ["LOAD", "LIST"]:
        name = "LOAD LIST"
        rest = tokens[2:]
        default_target_kind = "LOAD"
    elif upper_tokens and upper_tokens[0] == "CODE":
        return {
            "block": block_id,
            "context": context,
            "name": "CODE",
            "value": " ".join(tokens[1:]),
            "target_kind": None,
            "target": None,
            "line": line,
            "raw": text,
        }
    elif upper_tokens[:2] == ["DESIGN", "COLUMN"]:
        name = "DESIGN COLUMN"
        rest = tokens[2:]
        default_target_kind = "MEMBER"
    elif upper_tokens[:2] == ["DESIGN", "BEAM"]:
        name = "DESIGN BEAM"
        rest = tokens[2:]
        default_target_kind = "MEMBER"
    elif tokens:
        name = tokens[0].upper()
        rest = tokens[1:]
    else:
        name = ""
        rest = []

    selector_index = _find_target_selector(rest)

    if selector_index is None and name.startswith("DESIGN "):
        value_tokens: List[str] = []
        target_tokens = rest
        target_kind = default_target_kind or "MEMBER"
    elif selector_index is None:
        value_tokens = rest
        target_tokens = []
        target_kind = None
    else:
        value_tokens = rest[:selector_index]
        selector = rest[selector_index]
        if selector.upper() == "GROUP":
            target_tokens = rest[selector_index + 1 :]
            target_kind = "GROUP"
        elif selector.startswith("_"):
            target_tokens = rest[selector_index:]
            target_kind = "GROUP"
        elif selector.upper() == "ALL":
            target_tokens = ["ALL"]
            target_kind = default_target_kind or "ALL"
        else:
            target_tokens = rest[selector_index + 1 :]
            target_kind = _target_kind_from_selector(selector, default_target_kind)

    numeric_values = [_to_number(token) for token in value_tokens]
    if len(numeric_values) == 0:
        value: Any = None
    elif len(numeric_values) == 1:
        value = numeric_values[0]
    else:
        value = numeric_values

    target = parse_id_spec(target_tokens) if target_tokens else None
    return {
        "block": block_id,
        "context": context,
        "name": name,
        "value": value,
        "target_kind": target_kind,
        "target": target,
        "line": line,
        "raw": text,
    }


def _parse_support_record(text: str, line: int) -> Dict[str, Any]:
    tokens = text.split()
    support_index = None
    for index, token in enumerate(tokens):
        if token.upper() in _SUPPORT_TYPES:
            support_index = index
            break

    if support_index is None:
        return {"line": line, "raw": text, "target": parse_id_spec(tokens)}

    target_tokens = tokens[:support_index]
    support_tokens = tokens[support_index:]
    but_index = None
    for index, token in enumerate(support_tokens):
        if token.upper() == "BUT":
            but_index = index
            break

    support_type = support_tokens[0].upper()
    releases = support_tokens[but_index + 1 :] if but_index is not None else []
    details = support_tokens[1:but_index] if but_index is not None else support_tokens[1:]
    return {
        "line": line,
        "raw": text,
        "nodes": parse_id_spec(target_tokens),
        "support": support_type,
        "details": details,
        "releases": releases,
    }


def _parse_member_release_record(text: str, line: int) -> Dict[str, Any]:
    tokens = text.split()
    end_index = None
    for index, token in enumerate(tokens):
        if token.upper() in {"START", "END"}:
            end_index = index
            break

    if end_index is None:
        return {"line": line, "raw": text, "members": parse_id_spec(tokens)}

    return {
        "line": line,
        "raw": text,
        "members": parse_id_spec(tokens[:end_index]),
        "end": tokens[end_index].upper(),
        "releases": [token.upper() for token in tokens[end_index + 1 :]],
    }


def _parse_member_offset_record(text: str, line: int) -> Optional[Dict[str, Any]]:
    tokens = text.split()
    end_index = None
    for index, token in enumerate(tokens):
        if token.upper() in {"START", "END"}:
            end_index = index
            break

    if end_index is None:
        return None

    rest = tokens[end_index + 1 :]
    local = bool(rest) and rest[0].upper() == "LOCAL"
    offsets = [_to_number(token) for token in (rest[1:] if local else rest)]
    return {
        "line": line,
        "raw": text,
        "members": parse_id_spec(tokens[:end_index]),
        "end": tokens[end_index].upper(),
        "local": local,
        "offsets": offsets,
    }


def _parse_member_fireproofing_record(text: str, line: int) -> Optional[Dict[str, Any]]:
    tokens = text.split()
    fire_index = None
    for index, token in enumerate(tokens):
        if token.upper() == "FIRE":
            fire_index = index
            break

    if fire_index is None:
        return None

    rest = tokens[fire_index + 1 :]
    return {
        "line": line,
        "raw": text,
        "members": parse_id_spec(tokens[:fire_index]),
        "type": rest[0].upper() if rest else None,
        "parameters": _parse_key_value_pairs(rest[1:]),
    }


def _parse_member_property_record(
    text: str, line: int, source: str, sequence: int
) -> Optional[Dict[str, Any]]:
    tokens = text.split()
    target_tokens, property_tokens = _split_at_first_marker(tokens, _PROPERTY_MARKERS)
    if not property_tokens:
        return None

    target = parse_id_spec(target_tokens)
    profile_type = property_tokens[0].upper()
    profile = " ".join(property_tokens)
    values = [_to_number(token) for token in property_tokens[1:]]
    profile_name = ""
    if profile_type in {"TABLE", "UPTABLE"}:
        profile_name = " ".join(property_tokens[1:])
    elif profile_type == "PRIS":
        profile_name = "PRIS"
    elif profile_type == "TAPERED":
        profile_name = "TAPERED"

    return {
        "line": line,
        "sequence": sequence,
        "raw": text,
        "source": source,
        "members": target,
        "profile_type": profile_type,
        "profile": profile,
        "profile_name": profile_name,
        "values": values,
    }


def _parse_element_property_record(
    text: str, line: int, sequence: int
) -> Optional[Dict[str, Any]]:
    tokens = text.split()
    target_tokens, property_tokens = _split_at_first_marker(
        tokens, _ELEMENT_PROPERTY_MARKERS
    )
    if not property_tokens:
        return None

    property_type = property_tokens[0].upper()
    values = [_to_number(token) for token in property_tokens[1:]]
    return {
        "line": line,
        "sequence": sequence,
        "raw": text,
        "elements": parse_id_spec(target_tokens),
        "property_type": property_type,
        "property": " ".join(property_tokens),
        "values": values,
    }


def _parse_pmember_record(text: str, line: int) -> Optional[Dict[str, Any]]:
    tokens = text.split()
    upper_tokens = [token.upper() for token in tokens]
    if "PMEMBER" not in upper_tokens:
        return None

    index = upper_tokens.index("PMEMBER")
    if index + 1 >= len(tokens):
        return None

    pmember_value = _to_number(tokens[index + 1])
    return {
        "line": line,
        "raw": text,
        "members": parse_id_spec(tokens[:index]),
        "pmember": pmember_value,
    }


def _parse_material_property(text: str) -> Tuple[str, Any]:
    tokens = text.split()
    if not tokens:
        return "", None

    key = tokens[0].upper()
    rest = tokens[1:]
    if key == "STRENGTH":
        return key, _parse_key_value_pairs(rest)
    if len(rest) == 0:
        return key, True
    if len(rest) == 1:
        return key, _to_number(rest[0])
    return key, [_to_number(token) for token in rest]


def _parse_load_header(text: str, line: int) -> Dict[str, Any]:
    tokens = text.split()
    load_id = _parse_load_id(tokens[1])
    rest = tokens[2:]
    upper_rest = [token.upper() for token in rest]

    load_type = None
    title = ""
    reducible = "REDUCIBLE" in upper_rest
    attributes: List[str] = []

    if "LOADTYPE" in upper_rest:
        index = upper_rest.index("LOADTYPE")
        if index + 1 < len(rest):
            load_type = rest[index + 1]

    if "TITLE" in upper_rest:
        index = upper_rest.index("TITLE")
        title = " ".join(rest[index + 1 :]).strip()

    index = 0
    while index < len(rest):
        upper = rest[index].upper()
        if upper == "TITLE":
            break
        if upper == "LOADTYPE":
            index += 2
            continue
        attributes.append(rest[index])
        index += 1

    return {
        "id": load_id,
        "line": line,
        "raw": text,
        "load_type": load_type,
        "title": title,
        "reducible": reducible,
        "attributes": attributes,
        "items": [],
    }


def _parse_load_combination_header(text: str, line: int) -> Dict[str, Any]:
    tokens = text.split()
    combination_id: Optional[int] = None
    if len(tokens) > 2 and _is_int_token(tokens[2]):
        combination_id = int(tokens[2])
    title = " ".join(tokens[3:]).strip()
    return {
        "id": combination_id,
        "line": line,
        "raw": text,
        "title": title,
        "components": [],
        "raw_component_lines": [],
    }


def _parse_combination_components(text: str) -> Optional[List[Dict[str, Any]]]:
    tokens = text.split()
    if len(tokens) == 0 or len(tokens) % 2 != 0:
        return None

    components: List[Dict[str, Any]] = []
    for index in range(0, len(tokens), 2):
        load_token = tokens[index]
        factor_token = tokens[index + 1]
        if not (_is_int_token(load_token) or re.match(r"^[A-Za-z]\w*$", load_token)):
            return None
        if not _is_float_token(factor_token):
            return None
        components.append(
            {"load": _parse_load_id(load_token), "factor": float(factor_token)}
        )
    return components


def _parse_envelope_record(text: str, line: int) -> Dict[str, Any]:
    tokens = text.split()
    upper_tokens = [token.upper() for token in tokens]
    envelope_index = upper_tokens.index("ENVELOPE") if "ENVELOPE" in upper_tokens else -1
    type_index = upper_tokens.index("TYPE") if "TYPE" in upper_tokens else -1

    load_tokens = tokens[:envelope_index] if envelope_index >= 0 else tokens
    envelope_id = None
    if envelope_index >= 0 and envelope_index + 1 < len(tokens):
        envelope_id = _to_number(tokens[envelope_index + 1])
    envelope_type = " ".join(tokens[type_index + 1 :]) if type_index >= 0 else ""

    return {
        "line": line,
        "raw": text,
        "loads": parse_id_spec(load_tokens),
        "envelope": envelope_id,
        "type": envelope_type,
    }


def _parse_component_pairs(tokens: List[str]) -> Dict[str, Any]:
    components: Dict[str, Any] = {}
    index = 0
    while index < len(tokens):
        key = tokens[index].upper()
        if key in _FORCE_COMPONENTS and index + 1 < len(tokens):
            components[key] = _to_number(tokens[index + 1])
            index += 2
        else:
            index += 1
    return components


def _parse_floor_load_details(tokens: List[str]) -> Dict[str, Any]:
    """Parse FLOOR/ONEWAY load records: group form ("_GROUP FLOAD 3.75 GX")
    and range form ("YRANGE 128 128 FLOAD 1 XRANGE 0 8 ZRANGE -69.3 -47 GX")."""
    upper_tokens = [token.upper() for token in tokens]
    details: Dict[str, Any] = {"tokens": [_to_number(token) for token in tokens]}
    ranges: Dict[str, List[Any]] = {}
    index = 0
    while index < len(tokens):
        upper = upper_tokens[index]
        if (
            upper.endswith("RANGE")
            and index + 2 < len(tokens)
            and _is_float_token(tokens[index + 1])
            and _is_float_token(tokens[index + 2])
        ):
            ranges[upper[0]] = [_to_number(tokens[index + 1]), _to_number(tokens[index + 2])]
            index += 3
        elif upper in {"FLOAD", "ONE", "ONEWAY"} and index + 1 < len(tokens):
            details["load_type"] = upper
            details["magnitude"] = _to_number(tokens[index + 1])
            index += 2
        elif upper in _DIRECTIONS:
            details["direction"] = upper
            index += 1
        elif tokens[index].startswith("_"):
            details["group"] = tokens[index]
            index += 1
        else:
            index += 1
    if ranges:
        details["ranges"] = ranges
    return details


def _parse_load_item(kind: str, text: str, line: int) -> Dict[str, Any]:
    tokens = text.split()
    upper_tokens = [token.upper() for token in tokens]

    if kind == "SELFWEIGHT":
        target = None
        if "LIST" in upper_tokens:
            list_index = upper_tokens.index("LIST")
            target = parse_id_spec(tokens[list_index + 1 :])
        return {
            "kind": "SELFWEIGHT",
            "line": line,
            "raw": text,
            "direction": tokens[1].upper() if len(tokens) > 1 else None,
            "factor": _to_number(tokens[2]) if len(tokens) > 2 else None,
            "target": target,
        }

    if kind == "JOINT LOAD":
        component_index = None
        for index, token in enumerate(upper_tokens):
            if token in _FORCE_COMPONENTS:
                component_index = index
                break
        target_tokens = tokens[:component_index] if component_index is not None else tokens
        component_tokens = tokens[component_index:] if component_index is not None else []
        return {
            "kind": kind,
            "line": line,
            "raw": text,
            "target_kind": "JOINT",
            "target": parse_id_spec(target_tokens),
            "components": _parse_component_pairs(component_tokens),
        }

    if kind == "MEMBER LOAD":
        mode_index = None
        for index, token in enumerate(upper_tokens):
            if token in _MEMBER_LOAD_MODES:
                mode_index = index
                break
        target_tokens = tokens[:mode_index] if mode_index is not None else tokens
        load_tokens = tokens[mode_index:] if mode_index is not None else []
        mode = load_tokens[0].upper() if load_tokens else None
        direction = None
        values: List[Any] = []
        if len(load_tokens) > 1 and load_tokens[1].upper() in _DIRECTIONS:
            direction = load_tokens[1].upper()
            values = [_to_number(token) for token in load_tokens[2:]]
        else:
            values = [_to_number(token) for token in load_tokens[1:]]
        return {
            "kind": kind,
            "line": line,
            "raw": text,
            "target_kind": "MEMBER",
            "target": parse_id_spec(target_tokens),
            "mode": mode,
            "direction": direction,
            "values": values,
        }

    if kind in {"FLOOR LOAD", "ONEWAY LOAD"}:
        return {
            "kind": kind,
            "line": line,
            "raw": text,
            "details": _parse_floor_load_details(tokens),
        }

    if kind == "REFERENCE LOAD":
        if len(tokens) >= 2 and len(tokens) % 2 == 0 and all(
            _is_float_token(tokens[index]) for index in range(1, len(tokens), 2)
        ):
            references = [
                {"load": _parse_load_id(tokens[index]), "factor": float(tokens[index + 1])}
                for index in range(0, len(tokens), 2)
            ]
            return {"kind": kind, "line": line, "raw": text, "references": references}
        return {"kind": kind, "line": line, "raw": text, "tokens": tokens}

    if kind in {"ELEMENT LOAD", "PLATE LOAD", "AREA LOAD"}:
        marker_index = None
        load_markers = {"PR", "PRESSURE", "GX", "GY", "GZ", "X", "Y", "Z"}
        for index, token in enumerate(upper_tokens):
            if token in load_markers:
                marker_index = index
                break

        if marker_index is None:
            return {"kind": kind, "line": line, "raw": text, "tokens": tokens}

        value_tokens = tokens[marker_index + 1 :]
        direction = None
        load_type = upper_tokens[marker_index]
        if load_type in {"PR", "PRESSURE"} and value_tokens:
            next_upper = value_tokens[0].upper()
            if next_upper in _DIRECTIONS:
                direction = next_upper
                value_tokens = value_tokens[1:]

        return {
            "kind": kind,
            "line": line,
            "raw": text,
            "target_kind": "ELEMENT" if kind != "AREA LOAD" else "AREA",
            "target": parse_id_spec(tokens[:marker_index]),
            "load_type": load_type,
            "direction": direction,
            "values": [_to_number(token) for token in value_tokens],
        }

    if kind == "SPECTRUM":
        if len(tokens) == 2 and all(_is_float_token(token) for token in tokens):
            return {
                "kind": "SPECTRUM POINT",
                "line": line,
                "raw": text,
                "point": (_to_number(tokens[0]), _to_number(tokens[1])),
            }
        return {"kind": kind, "line": line, "raw": text, "tokens": tokens}

    return {"kind": kind, "line": line, "raw": text, "tokens": tokens}


def _normalize_keyed_number_tokens(
    values: List[Any], unit_context: Optional[Dict[str, Any]], quantity: str
) -> List[Any]:
    factor = _quantity_factor(unit_context, quantity)
    return [_numeric_to_si(value, factor) for value in values]


def _normalize_material_value(
    key: str, value: Any, unit_context: Optional[Dict[str, Any]]
) -> Tuple[Any, Optional[str]]:
    upper_key = key.upper()
    if upper_key in {"E", "G", "STRENGTH"}:
        return _numeric_to_si(value, _quantity_factor(unit_context, "pressure")), "Pa"
    if upper_key == "DENSITY":
        return (
            _numeric_to_si(value, _quantity_factor(unit_context, "force_per_volume")),
            "N/m^3",
        )
    return value, None


def _normalize_parameter_value(
    name: str, value: Any, unit_context: Optional[Dict[str, Any]]
) -> Tuple[Any, Optional[str]]:
    upper_name = name.upper()
    if upper_name in _LENGTH_DESIGN_PARAMETERS:
        return _numeric_to_si(value, _quantity_factor(unit_context, "length")), "m"
    if upper_name in _PRESSURE_DESIGN_PARAMETERS or upper_name in {"E", "G"}:
        return _numeric_to_si(value, _quantity_factor(unit_context, "pressure")), "Pa"
    if upper_name == "DENSITY":
        return (
            _numeric_to_si(value, _quantity_factor(unit_context, "force_per_volume")),
            "N/m^3",
        )
    return value, None


def _normalize_member_load_values(
    mode: Optional[str], values: List[Any], unit_context: Optional[Dict[str, Any]]
) -> Tuple[List[Any], List[str]]:
    if mode in {"UNI", "LIN"}:
        return (
            [
                _numeric_to_si(value, _quantity_factor(unit_context, "force_per_length"))
                if index == 0
                else _numeric_to_si(value, _quantity_factor(unit_context, "length"))
                for index, value in enumerate(values)
            ],
            ["N/m"] + ["m"] * max(0, len(values) - 1),
        )
    if mode == "TRAP":
        return (
            [
                _numeric_to_si(
                    value,
                    _quantity_factor(
                        unit_context,
                        "force_per_length" if index < 2 else "length",
                    ),
                )
                for index, value in enumerate(values)
            ],
            ["N/m"] * min(2, len(values)) + ["m"] * max(0, len(values) - 2),
        )
    if mode == "CON":
        return (
            [
                _numeric_to_si(
                    value,
                    _quantity_factor(unit_context, "force" if index == 0 else "length"),
                )
                for index, value in enumerate(values)
            ],
            ["N"] + ["m"] * max(0, len(values) - 1),
        )
    if mode == "CMOM":
        return (
            [
                _numeric_to_si(
                    value,
                    _quantity_factor(unit_context, "moment" if index == 0 else "length"),
                )
                for index, value in enumerate(values)
            ],
            ["N*m"] + ["m"] * max(0, len(values) - 1),
        )
    if mode == "UMOM":
        return (
            [
                _numeric_to_si(
                    value,
                    _quantity_factor(
                        unit_context,
                        "moment_per_length" if index == 0 else "length",
                    ),
                )
                for index, value in enumerate(values)
            ],
            ["N"] + ["m"] * max(0, len(values) - 1),
        )
    return values, []


def _normalize_load_item(item: Dict[str, Any], unit_context: Optional[Dict[str, Any]]) -> None:
    _with_unit_context(item, unit_context)
    kind = item.get("kind")

    if kind == "SELFWEIGHT":
        item["factor_si"] = item.get("factor")
        item["si_unit"] = "dimensionless"
        return

    if kind == "JOINT LOAD":
        components_si: Dict[str, Any] = {}
        component_units: Dict[str, str] = {}
        for component, value in item.get("components", {}).items():
            quantity = "moment" if component.upper().startswith("M") else "force"
            components_si[component] = _numeric_to_si(
                value, _quantity_factor(unit_context, quantity)
            )
            component_units[component] = "N*m" if quantity == "moment" else "N"
        item["components_si"] = components_si
        item["si_units"] = component_units
        return

    if kind == "MEMBER LOAD":
        values_si, value_units = _normalize_member_load_values(
            item.get("mode"), item.get("values", []), unit_context
        )
        item["values_si"] = values_si
        if value_units:
            item["si_units"] = value_units
        return

    if kind in {"FLOOR LOAD", "ONEWAY LOAD"}:
        details = item.get("details", {})
        details_si = dict(details)
        if "magnitude" in details_si:
            details_si["magnitude"] = _numeric_to_si(
                details_si["magnitude"], _quantity_factor(unit_context, "pressure")
            )
            item["si_unit"] = "Pa"
        if "ranges" in details_si:
            length_factor = _quantity_factor(unit_context, "length")
            details_si["ranges"] = {
                axis: _numeric_to_si(bounds, length_factor)
                for axis, bounds in details_si["ranges"].items()
            }
        item["details_si"] = details_si
        return

    if kind in {"ELEMENT LOAD", "PLATE LOAD", "AREA LOAD"} and "values" in item:
        item["values_si"] = _numeric_to_si(
            item["values"], _quantity_factor(unit_context, "pressure")
        )
        item["si_unit"] = "Pa"


def _bounding_box(nodes: Dict[int, Tuple[float, float, float]]) -> Optional[Dict[str, Any]]:
    if not nodes:
        return None
    xs = [coords[0] for coords in nodes.values()]
    ys = [coords[1] for coords in nodes.values()]
    zs = [coords[2] for coords in nodes.values()]
    return {
        "min": (min(xs), min(ys), min(zs)),
        "max": (max(xs), max(ys), max(zs)),
        "span": (max(xs) - min(xs), max(ys) - min(ys), max(zs) - min(zs)),
    }


class STDFileReader:
    def read(self, path: Union[str, Path]) -> STDModel:
        input_path = Path(path)
        text = _read_text(input_path)
        records, comments = _logical_records_from_text(text)

        model = STDModel(path=input_path)
        model.records = records
        model.comments = comments

        current_section: Optional[str] = None
        current_group_kind: Optional[str] = None
        current_material: Optional[str] = None
        current_property_source = ""
        current_load: Optional[Dict[str, Any]] = None
        current_load_collection: Optional[Dict[LoadId, Dict[str, Any]]] = None
        current_load_subtype: Optional[str] = None
        current_combination: Optional[Dict[str, Any]] = None
        in_job_information = False
        in_reference_loads = False
        current_design_block: Optional[Dict[str, Any]] = None
        active_unit_context: Optional[Dict[str, Any]] = None

        for record in records:
            text = record.text
            upper = text.upper()
            tokens = text.split()

            if not tokens:
                continue

            if upper.startswith("UNIT "):
                active_unit_context = _parse_unit_record(text, record.start_line)
                model.units.append(active_unit_context)
                self._remember_unit_context(model, record, active_unit_context)
                continue

            self._remember_unit_context(model, record, active_unit_context)

            if upper.startswith("STAAD"):
                model.title = text
                model.data_type = " ".join(tokens[:2]) if len(tokens) > 1 else tokens[0]
                current_section = None
                continue

            if upper == "START JOB INFORMATION":
                in_job_information = True
                current_section = "JOB INFORMATION"
                continue

            if upper == "END JOB INFORMATION":
                in_job_information = False
                current_section = None
                continue

            if in_job_information:
                key, value = self._parse_job_information_line(text)
                model.job_information[key] = value
                continue

            if upper.startswith("INPUT WIDTH"):
                if len(tokens) >= 3 and _is_int_token(tokens[2]):
                    model.input_width = int(tokens[2])
                model.analysis_commands.append(
                    {"line": record.start_line, "raw": text, "kind": "INPUT WIDTH"}
                )
                continue

            if upper == "DEFINE REFERENCE LOADS":
                in_reference_loads = True
                current_section = "REFERENCE LOADS"
                continue

            if upper == "END DEFINE REFERENCE LOADS":
                in_reference_loads = False
                current_section = None
                current_load = None
                current_load_collection = None
                current_load_subtype = None
                continue

            if upper == "DEFINE ENVELOPE":
                current_section = "DEFINE ENVELOPE"
                current_load = None
                current_load_collection = None
                current_load_subtype = None
                current_combination = None
                continue

            if upper == "END DEFINE ENVELOPE":
                current_section = None
                continue

            if upper.startswith("LOAD COMB "):
                current_combination = _parse_load_combination_header(text, record.start_line)
                combination_id = current_combination["id"]
                if combination_id is None:
                    model.unparsed_records.append(
                        {
                            "section": "LOAD COMBINATION",
                            "line": record.start_line,
                            "raw": text,
                        }
                    )
                    current_combination = None
                else:
                    model.load_combinations[combination_id] = current_combination
                    model.load_combination_order.append(combination_id)
                current_section = "LOAD COMBINATION"
                current_load = None
                current_load_collection = None
                current_load_subtype = None
                continue

            if upper.startswith("LOAD ") and not upper.startswith("LOAD LIST"):
                if len(tokens) > 1 and tokens[1].upper() not in {"COMB", "COMBINATION"}:
                    current_load = _parse_load_header(text, record.start_line)
                    current_load_subtype = None
                    if in_reference_loads:
                        current_load_collection = model.reference_loads
                        model.reference_load_order.append(current_load["id"])
                    else:
                        current_load_collection = model.loads
                        model.load_case_order.append(current_load["id"])
                    current_load_collection[current_load["id"]] = current_load
                    current_section = "LOAD"
                    current_combination = None
                    continue

            if upper == "JOINT COORDINATES":
                current_section = "JOINT COORDINATES"
                continue

            if upper == "MEMBER INCIDENCES":
                current_section = "MEMBER INCIDENCES"
                continue

            if upper.startswith("ELEMENT INCIDENCES") or upper.startswith("PLATE INCIDENCES"):
                current_section = "ELEMENT INCIDENCES"
                continue

            if upper == "DEFINE PMEMBER":
                current_section = "DEFINE PMEMBER"
                continue

            if upper == "START GROUP DEFINITION":
                current_section = "GROUP DEFINITION"
                current_group_kind = None
                continue

            if upper == "END GROUP DEFINITION":
                current_section = None
                current_group_kind = None
                continue

            if upper == "DEFINE MATERIAL START":
                current_section = "DEFINE MATERIAL"
                current_material = None
                continue

            if upper == "END DEFINE MATERIAL":
                current_section = None
                current_material = None
                continue

            if upper == "START USER TABLE":
                current_section = "USER TABLE"
                model.user_tables.append({"line": record.start_line, "records": []})
                continue

            if upper == "END" and current_section == "USER TABLE":
                current_section = None
                continue

            if upper.startswith("MEMBER PROPERTY"):
                current_section = "MEMBER PROPERTY"
                current_property_source = " ".join(tokens[2:]) if len(tokens) > 2 else ""
                continue

            if upper.startswith("ELEMENT PROPERTY") or upper.startswith("PLATE PROPERTY"):
                current_section = "ELEMENT PROPERTY"
                prefix = "ELEMENT PROPERTY" if upper.startswith("ELEMENT PROPERTY") else "PLATE PROPERTY"
                rest = text[len(prefix) :].strip()
                if rest:
                    self._add_element_property_record(model, rest, record.start_line)
                continue

            if upper == "CONSTANTS":
                current_section = "CONSTANTS"
                continue

            if upper == "SUPPORTS":
                current_section = "SUPPORTS"
                continue

            if upper.startswith("MEMBER RELEASE"):
                current_section = "MEMBER RELEASE"
                rest = text[len("MEMBER RELEASE") :].strip()
                if rest:
                    model.member_releases.append(
                        _parse_member_release_record(rest, record.start_line)
                    )
                continue

            if upper.startswith("MEMBER OFFSET"):
                current_section = "MEMBER OFFSET"
                rest = text[len("MEMBER OFFSET") :].strip()
                if rest:
                    self._add_member_offset_record(model, rest, record.start_line)
                continue

            if upper.startswith("MEMBER FIREPROOFING"):
                current_section = "MEMBER FIREPROOFING"
                rest = text[len("MEMBER FIREPROOFING") :].strip()
                if rest:
                    self._add_member_fireproofing_record(model, rest, record.start_line)
                continue

            if upper.startswith("ELEMENT PLANE"):
                current_section = "ELEMENT PLANE STRESS"
                continue

            if upper.startswith("INACTIVE "):
                model.analysis_commands.append(
                    {
                        "line": record.start_line,
                        "raw": text,
                        "kind": "INACTIVE",
                        "target": parse_id_spec(tokens[1:]),
                    }
                )
                continue

            if upper.startswith("DEFINE WIND"):
                model.wind_definitions.append(
                    {"line": record.start_line, "raw": text, "records": []}
                )
                current_section = "DEFINE WIND"
                continue

            if upper.startswith("MEMBER TRUSS"):
                current_section = "MEMBER TRUSS"
                rest = text[len("MEMBER TRUSS") :].strip()
                if rest:
                    model.member_truss.append(
                        {
                            "line": record.start_line,
                            "raw": rest,
                            "members": parse_id_spec(rest.split()),
                        }
                    )
                continue

            if upper.startswith("MEMBER TENSION"):
                current_section = "MEMBER TENSION"
                rest = text[len("MEMBER TENSION") :].strip()
                if rest:
                    model.member_tension.append(
                        {
                            "line": record.start_line,
                            "raw": rest,
                            "members": parse_id_spec(rest.split()),
                        }
                    )
                continue

            if upper.startswith("MEMBER COMPRESSION"):
                current_section = "MEMBER COMPRESSION"
                rest = text[len("MEMBER COMPRESSION") :].strip()
                if rest:
                    model.member_compression.append(
                        {
                            "line": record.start_line,
                            "raw": rest,
                            "members": parse_id_spec(rest.split()),
                        }
                    )
                continue

            if upper.startswith("PARAMETER"):
                block_number: Union[int, str] = (
                    int(tokens[1]) if len(tokens) > 1 and _is_int_token(tokens[1]) else len(model.design_blocks) + 1
                )
                current_design_block = {
                    "id": block_number,
                    "context": "PARAMETER",
                    "line": record.start_line,
                    "raw": text,
                    "parameters": [],
                }
                model.design_blocks.append(current_design_block)
                current_section = "DESIGN PARAMETERS"
                continue

            if upper == "START CONCRETE DESIGN":
                current_design_block = {
                    "id": "CONCRETE DESIGN",
                    "context": "CONCRETE DESIGN",
                    "line": record.start_line,
                    "raw": text,
                    "parameters": [],
                }
                model.design_blocks.append(current_design_block)
                current_section = "CONCRETE DESIGN"
                continue

            if upper == "END CONCRETE DESIGN":
                current_section = None
                current_design_block = None
                continue

            if upper == "FINISH":
                model.analysis_commands.append(
                    {"line": record.start_line, "raw": text, "kind": "FINISH"}
                )
                current_section = None
                continue

            if self._is_analysis_command(upper):
                model.analysis_commands.append(
                    {
                        "line": record.start_line,
                        "raw": text,
                        "kind": tokens[0].upper(),
                    }
                )
                if upper.startswith("LOAD LIST"):
                    if current_design_block is not None:
                        parameter = _parse_parameter_record(
                            text,
                            record.start_line,
                            current_design_block["id"],
                            current_design_block["context"],
                            default_target_kind="LOAD",
                        )
                        current_design_block["parameters"].append(parameter)
                        model.design_parameters.append(parameter)
                continue

            try:
                if current_section == "JOINT COORDINATES":
                    self._parse_joint_coordinate_record(model, record)
                elif current_section == "MEMBER INCIDENCES":
                    self._parse_member_incidence_record(model, record)
                elif current_section == "ELEMENT INCIDENCES":
                    self._parse_element_incidence_record(model, record)
                elif current_section == "DEFINE PMEMBER":
                    self._add_pmember_record(model, record)
                elif current_section == "GROUP DEFINITION":
                    current_group_kind = self._parse_group_record(
                        model, record, current_group_kind
                    )
                elif current_section == "DEFINE MATERIAL":
                    current_material = self._parse_material_record(
                        model, record, current_material
                    )
                elif current_section == "USER TABLE":
                    if model.user_tables:
                        model.user_tables[-1]["records"].append(
                            {"line": record.start_line, "raw": text}
                        )
                elif current_section == "MEMBER PROPERTY":
                    property_record = _parse_member_property_record(
                        text,
                        record.start_line,
                        current_property_source,
                        len(model.member_properties),
                    )
                    if property_record is None:
                        model.unparsed_records.append(
                            {
                                "section": current_section,
                                "line": record.start_line,
                                "raw": text,
                            }
                        )
                    else:
                        model.member_properties.append(property_record)
                        for member_id in property_record["members"]["ids"]:
                            model.member_profile_by_member[member_id] = {
                                "profile": property_record["profile"],
                                "profile_type": property_record["profile_type"],
                                "profile_name": property_record["profile_name"],
                                "property_index": property_record["sequence"],
                                "line": property_record["line"],
                                "source": property_record["source"],
                            }
                elif current_section == "ELEMENT PROPERTY":
                    self._add_element_property_record(model, text, record.start_line)
                elif current_section == "CONSTANTS":
                    parameter = _parse_parameter_record(
                        text,
                        record.start_line,
                        "CONSTANTS",
                        "CONSTANTS",
                        default_target_kind="MEMBER",
                    )
                    model.constants.append(parameter)
                elif current_section == "SUPPORTS":
                    support = _parse_support_record(text, record.start_line)
                    model.supports.append(support)
                    model.support_nodes.extend(
                        support.get("nodes", {}).get("ids", [])
                    )
                elif current_section == "MEMBER RELEASE":
                    model.member_releases.append(
                        _parse_member_release_record(text, record.start_line)
                    )
                elif current_section == "MEMBER OFFSET":
                    self._add_member_offset_record(model, text, record.start_line)
                elif current_section == "MEMBER FIREPROOFING":
                    self._add_member_fireproofing_record(model, text, record.start_line)
                elif current_section == "ELEMENT PLANE STRESS":
                    model.element_plane_stress.append(
                        {
                            "line": record.start_line,
                            "raw": text,
                            "elements": parse_id_spec(tokens),
                        }
                    )
                elif current_section == "DEFINE WIND":
                    model.wind_definitions[-1]["records"].append(
                        {"line": record.start_line, "raw": text}
                    )
                elif current_section == "MEMBER TRUSS":
                    model.member_truss.append(
                        {
                            "line": record.start_line,
                            "raw": text,
                            "members": parse_id_spec(tokens),
                        }
                    )
                elif current_section == "MEMBER TENSION":
                    model.member_tension.append(
                        {
                            "line": record.start_line,
                            "raw": text,
                            "members": parse_id_spec(tokens),
                        }
                    )
                elif current_section == "MEMBER COMPRESSION":
                    model.member_compression.append(
                        {
                            "line": record.start_line,
                            "raw": text,
                            "members": parse_id_spec(tokens),
                        }
                    )
                elif current_section == "LOAD" and current_load is not None:
                    current_load_subtype = self._parse_load_record(
                        current_load, record, current_load_subtype
                    )
                elif current_section == "LOAD COMBINATION" and current_combination is not None:
                    components = _parse_combination_components(text)
                    current_combination["raw_component_lines"].append(
                        {"line": record.start_line, "raw": text}
                    )
                    if components is not None:
                        current_combination["components"].extend(components)
                    else:
                        model.unparsed_records.append(
                            {
                                "section": current_section,
                                "line": record.start_line,
                                "raw": text,
                            }
                        )
                elif current_section == "DEFINE ENVELOPE":
                    model.load_envelopes.append(_parse_envelope_record(text, record.start_line))
                elif current_section in {"DESIGN PARAMETERS", "CONCRETE DESIGN"}:
                    if current_design_block is not None:
                        parameter = _parse_parameter_record(
                            text,
                            record.start_line,
                            current_design_block["id"],
                            current_design_block["context"],
                            default_target_kind="MEMBER",
                        )
                        current_design_block["parameters"].append(parameter)
                        model.design_parameters.append(parameter)
                else:
                    model.unparsed_records.append(
                        {"section": current_section, "line": record.start_line, "raw": text}
                    )
            except Exception as exc:
                # A malformed record must never crash the reader; retain it instead.
                model.unparsed_records.append(
                    {
                        "section": current_section,
                        "line": record.start_line,
                        "raw": text,
                        "error": f"{type(exc).__name__}: {exc}",
                    }
                )

        self._normalize_model_units(model)
        self._build_design_indexes(model)
        model.support_nodes = sorted(set(model.support_nodes))
        return model

    @staticmethod
    def _remember_unit_context(
        model: STDModel,
        record: LogicalRecord,
        unit_context: Optional[Dict[str, Any]],
    ) -> None:
        copied = _copy_unit_context(unit_context)
        for line in range(record.start_line, record.end_line + 1):
            model.unit_context_by_line[line] = copied

    @staticmethod
    def _parse_job_information_line(text: str) -> Tuple[str, str]:
        tokens = text.split(maxsplit=2)
        if len(tokens) >= 3 and tokens[0].upper() in {"JOB", "ENGINEER", "CHECKER", "APPROVED"}:
            return f"{tokens[0].upper()} {tokens[1].upper()}", tokens[2]
        if len(tokens) >= 2:
            return tokens[0].upper(), " ".join(tokens[1:])
        return text.upper(), ""

    @staticmethod
    def _is_analysis_command(upper: str) -> bool:
        prefixes = (
            "PERFORM ",
            "PRINT ",
            "LOAD LIST",
            "CUT OFF ",
            "DEFINE 1893",
            "PDELTA",
            "CHANGE",
            "SET ",
            "FINISH",
        )
        return any(upper.startswith(prefix) for prefix in prefixes)

    @staticmethod
    def _parse_joint_coordinate_record(model: STDModel, record: LogicalRecord) -> None:
        tokens = record.text.split()
        if len(tokens) % 4 != 0:
            model.unparsed_records.append(
                {
                    "section": "JOINT COORDINATES",
                    "line": record.start_line,
                    "raw": record.text,
                }
            )
            return

        for index in range(0, len(tokens), 4):
            if not _is_int_token(tokens[index]) or not all(
                _is_float_token(token) for token in tokens[index + 1 : index + 4]
            ):
                model.unparsed_records.append(
                    {
                        "section": "JOINT COORDINATES",
                        "line": record.start_line,
                        "raw": record.text,
                    }
                )
                return
            node_id = int(tokens[index])
            model.nodes[node_id] = (
                float(tokens[index + 1]),
                float(tokens[index + 2]),
                float(tokens[index + 3]),
            )
            model.node_source_lines[node_id] = record.start_line

    @staticmethod
    def _parse_member_incidence_record(model: STDModel, record: LogicalRecord) -> None:
        tokens = record.text.split()
        if len(tokens) % 3 != 0:
            model.unparsed_records.append(
                {
                    "section": "MEMBER INCIDENCES",
                    "line": record.start_line,
                    "raw": record.text,
                }
            )
            return

        for index in range(0, len(tokens), 3):
            if not all(_is_int_token(token) for token in tokens[index : index + 3]):
                model.unparsed_records.append(
                    {
                        "section": "MEMBER INCIDENCES",
                        "line": record.start_line,
                        "raw": record.text,
                    }
                )
                return
            member_id = int(tokens[index])
            model.members[member_id] = (int(tokens[index + 1]), int(tokens[index + 2]))

    @staticmethod
    def _parse_element_incidence_record(model: STDModel, record: LogicalRecord) -> None:
        tokens = record.text.split()
        if len(tokens) < 4 or not _is_int_token(tokens[0]) or not all(
            _is_int_token(token) for token in tokens
        ):
            model.unparsed_records.append(
                {
                    "section": "ELEMENT INCIDENCES",
                    "line": record.start_line,
                    "raw": record.text,
                }
            )
            return

        # Semicolon splitting normally leaves one element per record. If an
        # export omits semicolons, parse common 4-node and 3-node chunks.
        chunk_size = None
        if len(tokens) % 5 == 0:
            chunk_size = 5
        elif len(tokens) % 4 == 0:
            chunk_size = 4

        if chunk_size is None:
            element_id = int(tokens[0])
            model.plates[element_id] = tuple(int(token) for token in tokens[1:])
            return

        for index in range(0, len(tokens), chunk_size):
            element_id = int(tokens[index])
            model.plates[element_id] = tuple(
                int(token) for token in tokens[index + 1 : index + chunk_size]
            )

    @staticmethod
    def _parse_group_record(
        model: STDModel, record: LogicalRecord, current_group_kind: Optional[str]
    ) -> Optional[str]:
        upper = record.text.upper()
        if upper in {"MEMBER", "ELEMENT", "JOINT", "FLOOR"}:
            return upper

        tokens = record.text.split()
        if current_group_kind and tokens and tokens[0].startswith("_"):
            group_name = tokens[0]
            members = parse_id_spec(tokens[1:])
            model.groups.setdefault(current_group_kind, {})[group_name] = {
                "line": record.start_line,
                "raw": record.text,
                "items": members,
            }
            return current_group_kind

        model.unparsed_records.append(
            {"section": "GROUP DEFINITION", "line": record.start_line, "raw": record.text}
        )
        return current_group_kind

    @staticmethod
    def _add_element_property_record(model: STDModel, text: str, line: int) -> None:
        property_record = _parse_element_property_record(
            text, line, len(model.element_properties)
        )
        if property_record is None:
            model.unparsed_records.append(
                {"section": "ELEMENT PROPERTY", "line": line, "raw": text}
            )
            return

        model.element_properties.append(property_record)
        for element_id in property_record["elements"]["ids"]:
            model.element_property_by_element[element_id] = {
                "property": property_record["property"],
                "property_type": property_record["property_type"],
                "property_index": property_record["sequence"],
                "line": property_record["line"],
            }

    @staticmethod
    def _add_member_offset_record(model: STDModel, text: str, line: int) -> None:
        offset_record = _parse_member_offset_record(text, line)
        if offset_record is None:
            model.unparsed_records.append(
                {"section": "MEMBER OFFSET", "line": line, "raw": text}
            )
        else:
            model.member_offsets.append(offset_record)

    @staticmethod
    def _add_member_fireproofing_record(model: STDModel, text: str, line: int) -> None:
        fireproofing_record = _parse_member_fireproofing_record(text, line)
        if fireproofing_record is None:
            model.unparsed_records.append(
                {"section": "MEMBER FIREPROOFING", "line": line, "raw": text}
            )
        else:
            model.member_fireproofing.append(fireproofing_record)

    @staticmethod
    def _add_pmember_record(model: STDModel, record: LogicalRecord) -> None:
        pmember_record = _parse_pmember_record(record.text, record.start_line)
        if pmember_record is None:
            model.unparsed_records.append(
                {"section": "DEFINE PMEMBER", "line": record.start_line, "raw": record.text}
            )
            return

        pmember_id = pmember_record["pmember"]
        if isinstance(pmember_id, int):
            model.pmembers[pmember_id] = pmember_record
            for member_id in pmember_record["members"]["ids"]:
                model.pmember_by_member[member_id] = pmember_id
        else:
            model.unparsed_records.append(
                {"section": "DEFINE PMEMBER", "line": record.start_line, "raw": record.text}
            )

    @staticmethod
    def _parse_material_record(
        model: STDModel, record: LogicalRecord, current_material: Optional[str]
    ) -> Optional[str]:
        upper = record.text.upper()
        if upper.startswith("ISOTROPIC "):
            material_name = record.text.split(maxsplit=1)[1]
            model.materials[material_name] = {
                "line": record.start_line,
                "kind": "ISOTROPIC",
                "properties": {},
                "property_lines": {},
                "raw": [record.text],
            }
            return material_name

        if current_material is None:
            model.unparsed_records.append(
                {"section": "DEFINE MATERIAL", "line": record.start_line, "raw": record.text}
            )
            return current_material

        key, value = _parse_material_property(record.text)
        model.materials[current_material]["properties"][key] = value
        model.materials[current_material]["property_lines"][key] = record.start_line
        model.materials[current_material]["raw"].append(record.text)
        return current_material

    @staticmethod
    def _parse_load_record(
        current_load: Dict[str, Any],
        record: LogicalRecord,
        current_load_subtype: Optional[str],
    ) -> Optional[str]:
        text = record.text
        upper = text.upper()

        load_subtypes = {
            "JOINT LOAD",
            "MEMBER LOAD",
            "ELEMENT LOAD",
            "PLATE LOAD",
            "FLOOR LOAD",
            "ONEWAY LOAD",
            "AREA LOAD",
            "REFERENCE LOAD",
        }
        if upper in load_subtypes:
            return upper

        if upper.startswith("SELFWEIGHT"):
            current_load["items"].append(
                _parse_load_item("SELFWEIGHT", text, record.start_line)
            )
            return current_load_subtype

        if upper.startswith("SPECTRUM"):
            current_load["items"].append(
                {
                    "kind": "SPECTRUM",
                    "line": record.start_line,
                    "raw": text,
                    "tokens": text.split(),
                }
            )
            return "SPECTRUM"

        if upper.startswith("REPEAT LOAD"):
            current_load["items"].append(
                {"kind": "REPEAT LOAD", "line": record.start_line, "raw": text}
            )
            return "REPEAT LOAD"

        if upper.startswith("1893 LOAD") or upper.startswith("UBC LOAD"):
            current_load["items"].append(
                {"kind": text.split()[0].upper() + " LOAD", "line": record.start_line, "raw": text}
            )
            return current_load_subtype

        if current_load_subtype:
            current_load["items"].append(
                _parse_load_item(current_load_subtype, text, record.start_line)
            )
        else:
            current_load["items"].append(
                {"kind": "COMMAND", "line": record.start_line, "raw": text}
            )
        return current_load_subtype

    @staticmethod
    def _unit_for_line(model: STDModel, line: Optional[int]) -> Optional[Dict[str, Any]]:
        if line is None:
            return None
        return model.unit_context_by_line.get(line)

    @classmethod
    def _normalize_model_units(cls, model: STDModel) -> None:
        for node_id, coords in model.nodes.items():
            unit_context = cls._unit_for_line(model, model.node_source_lines.get(node_id))
            factor = _quantity_factor(unit_context, "length")
            model.nodes_si[node_id] = _numeric_to_si(coords, factor)

        for material in model.materials.values():
            _with_unit_context(material, cls._unit_for_line(model, material.get("line")))
            properties_si: Dict[str, Any] = {}
            property_units: Dict[str, str] = {}
            property_lines = material.get("property_lines", {})
            for key, value in material.get("properties", {}).items():
                unit_context = cls._unit_for_line(
                    model, property_lines.get(key, material.get("line"))
                )
                converted, si_unit = _normalize_material_value(key, value, unit_context)
                properties_si[key] = converted
                if si_unit:
                    property_units[key] = si_unit
            material["properties_si"] = properties_si
            if property_units:
                material["si_units"] = property_units

        for property_record in model.member_properties:
            unit_context = cls._unit_for_line(model, property_record.get("line"))
            _with_unit_context(property_record, unit_context)
            if property_record.get("profile_type") in {"PRIS", "TAPERED", "GENERAL"}:
                property_record["values_si"] = _normalize_keyed_number_tokens(
                    property_record.get("values", []), unit_context, "length"
                )
                property_record["si_unit"] = "m"

        for member_id, profile in model.member_profile_by_member.items():
            unit_context = cls._unit_for_line(model, profile.get("line"))
            _with_unit_context(profile, unit_context)
            property_index = profile.get("property_index")
            if isinstance(property_index, int) and property_index < len(model.member_properties):
                values_si = model.member_properties[property_index].get("values_si")
                if values_si is not None:
                    profile["values_si"] = values_si
                    profile["si_unit"] = model.member_properties[property_index].get(
                        "si_unit"
                    )

        for property_record in model.element_properties:
            unit_context = cls._unit_for_line(model, property_record.get("line"))
            _with_unit_context(property_record, unit_context)
            if property_record.get("property_type") == "THICKNESS":
                property_record["values_si"] = _normalize_keyed_number_tokens(
                    property_record.get("values", []), unit_context, "length"
                )
                property_record["si_unit"] = "m"

        for element_id, property_data in model.element_property_by_element.items():
            unit_context = cls._unit_for_line(model, property_data.get("line"))
            _with_unit_context(property_data, unit_context)
            property_index = property_data.get("property_index")
            if isinstance(property_index, int) and property_index < len(model.element_properties):
                values_si = model.element_properties[property_index].get("values_si")
                if values_si is not None:
                    property_data["values_si"] = values_si
                    property_data["si_unit"] = model.element_properties[property_index].get(
                        "si_unit"
                    )

        for pmember in model.pmembers.values():
            _with_unit_context(pmember, cls._unit_for_line(model, pmember.get("line")))

        for collection in (
            model.constants,
            model.design_parameters,
        ):
            for parameter in collection:
                unit_context = cls._unit_for_line(model, parameter.get("line"))
                _with_unit_context(parameter, unit_context)
                converted, si_unit = _normalize_parameter_value(
                    parameter.get("name", ""), parameter.get("value"), unit_context
                )
                if si_unit:
                    parameter["value_si"] = converted
                    parameter["si_unit"] = si_unit

        for support in model.supports:
            _with_unit_context(support, cls._unit_for_line(model, support.get("line")))

        for offset in model.member_offsets:
            unit_context = cls._unit_for_line(model, offset.get("line"))
            _with_unit_context(offset, unit_context)
            offset["offsets_si"] = _normalize_keyed_number_tokens(
                offset.get("offsets", []), unit_context, "length"
            )
            offset["si_unit"] = "m"

        for collection in (
            model.member_releases,
            model.member_fireproofing,
            model.member_truss,
            model.member_tension,
            model.member_compression,
            model.element_plane_stress,
            model.wind_definitions,
        ):
            for item in collection:
                _with_unit_context(item, cls._unit_for_line(model, item.get("line")))

        for load in list(model.loads.values()) + list(model.reference_loads.values()):
            _with_unit_context(load, cls._unit_for_line(model, load.get("line")))
            for item in load.get("items", []):
                _normalize_load_item(item, cls._unit_for_line(model, item.get("line")))

        for combination in model.load_combinations.values():
            _with_unit_context(combination, cls._unit_for_line(model, combination.get("line")))
            for raw_line in combination.get("raw_component_lines", []):
                _with_unit_context(raw_line, cls._unit_for_line(model, raw_line.get("line")))

        for envelope in model.load_envelopes:
            _with_unit_context(envelope, cls._unit_for_line(model, envelope.get("line")))

        for block in model.design_blocks:
            _with_unit_context(block, cls._unit_for_line(model, block.get("line")))

        for command in model.analysis_commands:
            _with_unit_context(command, cls._unit_for_line(model, command.get("line")))

    @staticmethod
    def _build_design_indexes(model: STDModel) -> None:
        by_member: Dict[int, List[Dict[str, Any]]] = defaultdict(list)
        by_group: Dict[str, List[Dict[str, Any]]] = defaultdict(list)

        for parameter in model.design_parameters:
            target = parameter.get("target")
            if not target:
                continue

            for group_name in target.get("groups", []):
                by_group[group_name].append(parameter)

            if parameter.get("target_kind") == "LOAD":
                continue

            member_ids = list(target.get("ids", []))
            if target.get("all"):
                member_ids = list(model.members.keys())

            for member_id in member_ids:
                by_member[member_id].append(parameter)

        model.design_parameters_by_member = dict(by_member)
        model.design_parameters_by_group = dict(by_group)


def read_std_file(path: Union[str, Path]) -> STDModel:
    return STDFileReader().read(path)


def _counter_text(counter: Counter, limit: int = 8) -> str:
    if not counter:
        return "none"
    items = counter.most_common(limit)
    text = ", ".join(f"{name}: {count}" for name, count in items)
    if len(counter) > limit:
        text += f", ... +{len(counter) - limit} more"
    return text


def print_statistics(
    model: STDModel,
    show_loads: bool = False,
    show_profiles: bool = False,
    show_unparsed: bool = False,
) -> None:
    print(f"File: {model.path}")
    print(f"Data title: {model.title or 'n/a'}")
    if model.units:
        unit = model.units[-1]
        print(f"Current unit: {unit.get('length') or 'n/a'} {unit.get('force') or 'n/a'}")
        print(
            "Unit commands: "
            f"{len(model.units)}"
            + (
                " at lines "
                + ", ".join(str(item.get("line")) for item in model.units)
                if len(model.units) > 1
                else ""
            )
        )
        print(
            "Current SI factors: "
            f"length={unit.get('length_factor_to_meter')} m, "
            f"force={unit.get('force_factor_to_newton')} N"
        )

    bounds = _bounding_box(model.nodes)
    si_bounds = _bounding_box(model.nodes_si)
    print("")
    print("Geometry")
    print(f"  Nodes: {len(model.nodes)}")
    if bounds:
        print(f"  Bounds min: {bounds['min']}")
        print(f"  Bounds max: {bounds['max']}")
        print(f"  Bounds span: {bounds['span']}")
    if si_bounds:
        print(f"  SI bounds min (m): {si_bounds['min']}")
        print(f"  SI bounds max (m): {si_bounds['max']}")
        print(f"  SI bounds span (m): {si_bounds['span']}")
    print(f"  Members: {len(model.members)}")
    print(f"  Plates/elements: {len(model.plates)}")

    member_groups = model.groups.get("MEMBER", {})
    element_groups = model.groups.get("ELEMENT", {})
    joint_groups = model.groups.get("JOINT", {})
    floor_groups = model.groups.get("FLOOR", {})
    print("")
    print("Groups")
    print(
        "  Member groups: "
        f"{len(member_groups)}"
        + (f" ({', '.join(list(member_groups)[:6])})" if member_groups else "")
    )
    print(f"  Element groups: {len(element_groups)}")
    print(f"  Joint groups: {len(joint_groups)}")
    print(f"  Floor groups: {len(floor_groups)}")

    profile_counter = Counter(
        data["profile"] for data in model.member_profile_by_member.values()
    )
    print("")
    print("Properties")
    print(f"  Member property assignments: {len(model.member_properties)}")
    print(f"  Members with profile/property: {len(model.member_profile_by_member)}")
    print(f"  Unique member profiles: {len(profile_counter)}")
    print(f"  Top profiles: {_counter_text(profile_counter)}")
    print(f"  Element property assignments: {len(model.element_properties)}")
    print(f"  Physical member definitions: {len(model.pmembers)}")
    print(f"  Member offset records: {len(model.member_offsets)}")
    print(f"  Member fireproofing records: {len(model.member_fireproofing)}")
    print(f"  Plane-stress element records: {len(model.element_plane_stress)}")

    support_counter = Counter(support.get("support", "UNKNOWN") for support in model.supports)
    print("")
    print("Supports")
    print(f"  Support records: {len(model.supports)}")
    print(f"  Support nodes: {len(model.support_nodes)}")
    print(f"  Support types: {_counter_text(support_counter)}")

    load_item_counter: Counter = Counter()
    for load in list(model.loads.values()) + list(model.reference_loads.values()):
        for item in load.get("items", []):
            load_item_counter[item.get("kind", "UNKNOWN")] += 1

    print("")
    print("Loads")
    print(f"  Load cases: {len(model.loads)}")
    print(f"  Reference loads: {len(model.reference_loads)}")
    print(f"  Load combinations: {len(model.load_combinations)}")
    print(f"  Load envelopes: {len(model.load_envelopes)}")
    print(f"  Wind definitions: {len(model.wind_definitions)}")
    print(f"  Load item types: {_counter_text(load_item_counter)}")

    if model.load_combinations:
        first_ids = model.load_combination_order[:5]
        examples = []
        for combination_id in first_ids:
            combo = model.load_combinations[combination_id]
            components = " ".join(
                f"{entry['load']}*{entry['factor']}" for entry in combo["components"][:6]
            )
            if len(combo["components"]) > 6:
                components += " ..."
            examples.append(f"{combination_id}: {combo['title']} [{components}]")
        print("  Combination examples:")
        for example in examples:
            print(f"    {example}")

    design_counter = Counter(parameter["name"] for parameter in model.design_parameters)
    print("")
    print("Design")
    print(f"  Design blocks: {len(model.design_blocks)}")
    print(f"  Design parameter records: {len(model.design_parameters)}")
    print(f"  Design parameter names: {_counter_text(design_counter, limit=12)}")
    print(f"  Members with indexed design parameters: {len(model.design_parameters_by_member)}")
    print(f"  Groups with indexed design parameters: {len(model.design_parameters_by_group)}")

    if show_loads:
        print("")
        print("Load Cases")
        for load_id in model.load_case_order:
            load = model.loads[load_id]
            print(
                f"  {load_id}: type={load.get('load_type')} title={load.get('title')} "
                f"items={len(load.get('items', []))}"
            )

    if show_profiles:
        print("")
        print("Profiles")
        for profile, count in profile_counter.most_common():
            print(f"  {profile}: {count}")

    if model.unparsed_records:
        print("")
        print(f"Unparsed/nonessential records retained: {len(model.unparsed_records)}")
        if show_unparsed:
            for item in model.unparsed_records:
                print(
                    f"  line {item.get('line')}: "
                    f"[{item.get('section')}] {item.get('raw')}"
                )


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Read a .std file and print statistics.")
    parser.add_argument("--file", required=True, help="Path to the .std file to read.")
    parser.add_argument(
        "--show-loads",
        action="store_true",
        help="Print the parsed load case list after the summary.",
    )
    parser.add_argument(
        "--show-profiles",
        action="store_true",
        help="Print all unique member profile assignments after the summary.",
    )
    parser.add_argument(
        "--show-unparsed",
        action="store_true",
        help="Print retained unparsed records after the summary.",
    )
    parser.add_argument(
        "--dump-json",
        action="store_true",
        help="Print the parsed model as JSON instead of the statistics summary.",
    )
    parser.add_argument(
        "--include-records",
        action="store_true",
        help="Include normalized source records when used with --dump-json.",
    )
    args = parser.parse_args(argv)

    try:
        model = read_std_file(args.file)
    except OSError as exc:
        print(f"Error: cannot read '{args.file}': {exc}", file=sys.stderr)
        return 1
    if args.dump_json:
        print(json.dumps(model.to_dict(include_records=args.include_records), indent=2, default=str))
    else:
        print_statistics(
            model,
            show_loads=args.show_loads,
            show_profiles=args.show_profiles,
            show_unparsed=args.show_unparsed,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
