# Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
"""Generate compressed C++ data for SVG icons listed in SVGIconManifest.h."""

import re
import sys
import zlib
from pathlib import Path


ENTRY_PATTERN = re.compile(
    r"VISHWAKARMA_SVG_ICON\(\s*([0-9]+)u?\s*,\s*\"([^\"]+)\"\s*\)"
)

def parse_manifest(path: Path) -> list[tuple[int, str]]:
    text = path.read_text(encoding="utf-8")
    entries = [(int(match.group(1)), match.group(2)) for match in ENTRY_PATTERN.finditer(text)]
    if not entries:
        raise RuntimeError(f"No SVG icon entries found in {path}")

    seen_ids: set[int] = set()
    seen_files: set[str] = set()
    for icon_id, filename in entries:
        if icon_id in seen_ids:
            raise RuntimeError(f"Duplicate SVG icon id {icon_id} in {path}")
        if filename in seen_files:
            raise RuntimeError(f"Duplicate SVG icon file {filename} in {path}")
        seen_ids.add(icon_id)
        seen_files.add(filename)

    return entries


def byte_array_literal(data: bytes) -> str:
    lines: list[str] = []
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{byte:02X}" for byte in chunk))
    return ",\n".join(lines)


def generate_header(entries: list[tuple[int, str]], svg_dir: Path) -> str:
    arrays: list[str] = []
    table_entries: list[str] = []

    for icon_id, filename in entries:
        svg_path = svg_dir / filename
        if not svg_path.is_file():
            raise RuntimeError(f"Missing SVG icon file: {svg_path}")

        source = svg_path.read_bytes()
        compressed = zlib.compress(source, level=9)
        symbol = f"kSVGIconData_{icon_id}"

        arrays.append(
            f"inline constexpr uint8_t {symbol}[] = {{\n"
            f"{byte_array_literal(compressed)}\n"
            f"}};\n"
        )
        table_entries.append(
            f"    {{ {icon_id}u, \"{filename}\", {len(source)}u, "
            f"{len(compressed)}u, {symbol} }}"
        )

    return (
        "// This file is generated by code-miscellaneous/svg_icon_embedder.py.\n"
        "// Edit code-core/SVGIconManifest.h, then rebuild.\n"
        "#pragma once\n\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n\n"
        "namespace SVGIconRenderer::Embedded {\n\n"
        "struct CompressedSVGIcon {\n"
        "    uint32_t id;\n"
        "    const char* fileName;\n"
        "    uint32_t uncompressedSize;\n"
        "    uint32_t compressedSize;\n"
        "    const uint8_t* compressedData;\n"
        "};\n\n"
        + "\n".join(arrays)
        + "\ninline constexpr CompressedSVGIcon kSVGIcons[] = {\n"
        + ",\n".join(table_entries)
        + "\n};\n\n"
        "inline constexpr std::size_t kSVGIconCount = "
        "sizeof(kSVGIcons) / sizeof(kSVGIcons[0]);\n\n"
        "} // namespace SVGIconRenderer::Embedded\n"
    )


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "Usage: svg_icon_embedder.py <SVGIconManifest.h> <SVGIconsDir> <OutputHeader>",
            file=sys.stderr,
        )
        return 2

    manifest_path = Path(sys.argv[1])
    svg_dir = Path(sys.argv[2])
    output_path = Path(sys.argv[3])

    try:
        entries = parse_manifest(manifest_path)
        header = generate_header(entries, svg_dir)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(header, encoding="utf-8", newline="\n")
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"[Pre-Build] Embedded {len(entries)} SVG icons into {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
