# Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
"""
This build-time script reads UserInterfaceTranslation.csv and generates:
    UserInterfaceTranslationCompiled.h
    UserInterfaceTranslationCompiled.cpp

The generated files contain a static compile-time translation table for all 46 languages.
- Multiple translator rows (Human, Comments, ChatGPT, Gemini, Grok, Claude) per WorldID are supported.
- The script prefers the "Grok" row when available (as per your request for Grok-centric workflow).
- If no Grok row exists for a WorldID, it falls back to the first row.
- Missing translations fall back to English at runtime.
- All strings are stored as UTF-32 (char32_t) for full Unicode support across all scripts.
"""

import csv
import sys
from pathlib import Path
from collections import defaultdict
from typing import Dict, List, Tuple

# Must match the exact order and count in UILanguage enum (UserInterface-TextTranslations.h)
LANGUAGE_COLUMN_PREFIXES = [f"{i:02d}." for i in range(46)]
LANGUAGE_NAMES = [
    "English", "Hindi", "Bengali", "Marathi", "Telugu", "Tamil", "Gujarati", "Urdu",
    "Kannada", "Odia", "Malayalam", "Punjabi", "Assamese", "Maithili", "Santali",
    "Kashmiri", "Nepali", "Sindhi", "Dogri", "Konkani", "Manipuri", "Bodo", "Sanskrit",
    "ChineseSimplified", "ChineseTraditional", "Spanish", "Portuguese", "Russian",
    "French", "Arabic", "Indonesian", "German", "Japanese", "Vietnamese", "Turkish",
    "Persian", "Korean", "Italian", "Thai", "Polish", "Ukrainian", "Dutch", "Filipino",
    "Swedish", "Czech", "Hungarian"
]

def to_cpp_u32_literal(text: str) -> str:
    """Escape a string for C++ U"" literal (UTF-8 source file)."""
    if not text:
        return 'U""'
    escaped = (text
               .replace('\\', '\\\\')
               .replace('"', '\\"')
               .replace('\n', '\\n')
               .replace('\r', '\\r'))
    return f'U"{escaped}"'


def main():
    csv_path = Path("UserInterfaceTranslation.csv")
    if not csv_path.exists():
        print("ERROR: UserInterfaceTranslation.csv not found in current directory.", file=sys.stderr)
        sys.exit(1)

    # Group rows by WorldID
    groups: Dict[int, List[dict]] = defaultdict(list)

    with csv_path.open(newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            print("ERROR: CSV has no header.", file=sys.stderr)
            sys.exit(1)

        # Find language column indices by parsing "00.English", "01.Hindi", etc.
        lang_col_indices: List[int] = []
        for i, field in enumerate(reader.fieldnames):
            for prefix in LANGUAGE_COLUMN_PREFIXES:
                if field.strip().startswith(prefix):
                    lang_col_indices.append(i)
                    break

        if len(lang_col_indices) != 46:
            print(f"ERROR: Expected 46 language columns, found {len(lang_col_indices)}", file=sys.stderr)
            sys.exit(1)

        for row in reader:
            try:
                world_id = int(row["WorldID"])
            except (KeyError, ValueError):
                continue  # skip malformed rows

            groups[world_id].append(row)

    # Generate data for each WorldID (prefer Grok row)
    translation_data: List[Tuple[int, List[str]]] = []

    for world_id in sorted(groups.keys()):
        rows = groups[world_id]
        # Prefer Grok row if available
        grok_row = next((r for r in rows if r.get("Translator", "").strip().lower() == "grok"), None)
        selected_row = grok_row if grok_row else rows[0]

        lang_texts: List[str] = []
        for col_idx in lang_col_indices:
            text = selected_row.get(reader.fieldnames[col_idx], "").strip()
            lang_texts.append(text)

        translation_data.append((world_id, lang_texts))

    # === Generate UserInterfaceTranslationCompiled.h ===
    h_content = """#pragma once
// Auto-generated by UserInterfaceTranslationCompiler.py - DO NOT EDIT MANUALLY
// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.

#include "UserInterface-TextTranslations.h"
#include <cstdint>

namespace UITranslations
{
    /**
     * Returns the localized UTF-32 string for the given stringID and language.
     * If the translation is missing/empty, English (index 0) is returned as fallback.
     * Returns empty string if the stringID is unknown.
     */
    const char32_t* GetUILocalizedString(uint32_t stringID, UILanguage language);
}
"""

    with open("UserInterfaceTranslationCompiled.h", "w", encoding="utf-8") as f:
        f.write(h_content)
    print("✓ Generated UserInterfaceTranslationCompiled.h")

    # === Generate UserInterfaceTranslationCompiled.cpp ===
    cpp_header = """// Auto-generated by UserInterfaceTranslationCompiler.py - DO NOT EDIT MANUALLY
// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.

#include "UserInterfaceTranslationCompiled.h"
#include <unordered_map>
#include <array>

namespace UITranslations
{
    // Static translation table: WorldID → array of 46 UTF-32 strings (one per language)
    static const std::unordered_map<uint32_t, std::array<const char32_t*, static_cast<size_t>(UILanguage::COUNT)>> g_TranslationMap =
    {
"""

    entries = []
    for world_id, lang_texts in translation_data:
        literals = [to_cpp_u32_literal(text) for text in lang_texts]
        entry = f"        {{ {world_id}, {{ {', '.join(literals)} }} }},"
        entries.append(entry)

    cpp_footer = """    };

    const char32_t* GetUILocalizedString(uint32_t stringID, UILanguage language)
    {
        auto it = g_TranslationMap.find(stringID);
        if (it == g_TranslationMap.end())
        {
            return U"";
        }

        size_t langIdx = static_cast<size_t>(language);
        const char32_t* str = it->second[langIdx];

        // Fallback to English if missing/empty (as per specification)
        if (str == nullptr || *str == U'\\0')
        {
            return it->second[0];
        }
        return str;
    }
}
"""

    with open("UserInterfaceTranslationCompiled.cpp", "w", encoding="utf-8") as f:
        f.write(cpp_header)
        f.write("\n".join(entries))
        f.write("\n")
        f.write(cpp_footer)

    print(f"✓ Generated UserInterfaceTranslationCompiled.cpp with {len(translation_data)} strings")
    print("   All 46 languages supported. Texture atlas preparation (Phase 4B) will use these strings.")


if __name__ == "__main__":
    main()
