# Copyright (c) 2026-Present : Ram Shanker: All rights reserved.
"""
Build-time compiler for UI translations.

Input files:
    code-miscellaneous/UserInterfaceTranslation.csv
    code-miscellaneous/UserInterfaceTranslation_01_Hindi.csv
    ...
    code-miscellaneous/UserInterfaceTranslation_45_Hungarian.csv

Generated files:
    code-core/UserInterfaceTranslationCompiled.h
    code-core/UserInterfaceTranslationCompiled.cpp

The English CSV is the canonical list of WorldID values. Per-language CSVs are
joined by WorldID and may be maintained independently by translators.
"""

import csv
import sys
from pathlib import Path
from typing import Dict, List, Tuple


# Must match the exact order in UILanguage (UserInterface-TextTranslations.h).
LANGUAGES = [
    "English", "Hindi", "Bengali", "Marathi", "Telugu", "Tamil", "Gujarati", "Urdu",
    "Kannada", "Odia", "Malayalam", "Punjabi", "Assamese", "Maithili", "Santali",
    "Kashmiri", "Nepali", "Sindhi", "Dogri", "Konkani", "Manipuri", "Bodo", "Sanskrit",
    "ChineseSimplified", "ChineseTraditional", "Spanish", "Portuguese", "Russian",
    "French", "Arabic", "Indonesian", "German", "Japanese", "Vietnamese", "Turkish",
    "Persian", "Korean", "Italian", "Thai", "Polish", "Ukrainian", "Dutch", "Filipino",
    "Swedish", "Czech", "Hungarian",
]
TRANSLATION_PRIORITY = ["Human", "Grok", "ChatGPT", "Gemini", "Claude"]

def to_cpp_u32_literal(text: str) -> str:
    """Escape text for a C++ UTF-32 string literal."""
    if not text:
        return 'U""'

    escaped = (
        text
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    return f'U"{escaped}"'


WORLD_ID_COLUMNS = ("WorldID", "WordID")

def read_csv_by_world_id(path: Path) -> Dict[int, dict]:
    if not path.exists():
        return {}

    rows: Dict[int, dict] = {}
    with path.open(newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        if not reader.fieldnames:
            return rows

        for row in reader:
            world_id_text = ""
            for column_name in WORLD_ID_COLUMNS:
                world_id_text = (row.get(column_name) or "").strip()
                if world_id_text:
                    break

            if not world_id_text:
                continue

            try:
                world_id = int(world_id_text, 0)
            except ValueError:
                print(f"WARNING: Skipping malformed WorldID {world_id_text!r} in {path.name}", file=sys.stderr)
                continue

            rows[world_id] = row

    return rows

def select_english_text(row: dict) -> str:
    return (row.get("English") or row.get("Human") or "").strip()

def select_translated_text(row: dict, english_fallback: str) -> str:
    for column_name in TRANSLATION_PRIORITY:
        text = (row.get(column_name) or "").strip()
        if text and text != english_fallback:
            return text

    for column_name in TRANSLATION_PRIORITY:
        text = (row.get(column_name) or "").strip()
        if text:
            return text

    return (row.get("English") or english_fallback or "").strip()

def language_csv_path(source_dir: Path, language_index: int, language_name: str) -> Path:
    return source_dir / f"UserInterfaceTranslation_{language_index:02d}_{language_name}.csv"

def build_translation_data(source_dir: Path) -> List[Tuple[int, List[str]]]:
    canonical_path = source_dir / "UserInterfaceTranslation.csv"
    canonical_rows = read_csv_by_world_id(canonical_path)
    if not canonical_rows:
        print(f"ERROR: No canonical translations found in {canonical_path}", file=sys.stderr)
        sys.exit(1)

    language_rows: List[Dict[int, dict]] = [canonical_rows]
    for language_index, language_name in enumerate(LANGUAGES[1:], start=1):
        path = language_csv_path(source_dir, language_index, language_name)
        rows = read_csv_by_world_id(path)
        if not rows:
            print(f"WARNING: {path.name} not found or empty; using English fallback.", file=sys.stderr)
        language_rows.append(rows)

    translation_data: List[Tuple[int, List[str]]] = []
    for world_id in sorted(canonical_rows.keys()):
        canonical_row = canonical_rows[world_id]
        english_text = select_english_text(canonical_row)
        texts = [english_text]
        for rows in language_rows[1:]:
            texts.append(select_translated_text(rows.get(world_id, {}), english_text))

        translation_data.append((world_id, texts))

    return translation_data

def write_compiled_header(output_dir: Path) -> None:
    h_content = """#pragma once
// Auto-generated by UserInterfaceTranslationCompiler.py - DO NOT EDIT MANUALLY
// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.

#include <cstdint>
#include "UserInterface-TextTranslations.h"

namespace UITranslations
{
    /**
     * Returns the localized UTF-32 string for the given stringID and language.
     * If the translation is missing/empty, English (index 0) is returned as fallback.
     * Returns empty string if the stringID is unknown.
     */
    const char32_t* GetUILocalizedString(uint32_t stringID, UILanguage language);
}
"""

    (output_dir / "UserInterfaceTranslationCompiled.h").write_text(h_content, encoding="utf-8")


def write_compiled_cpp(output_dir: Path, translation_data: List[Tuple[int, List[str]]]) -> None:
    cpp_header = """// Auto-generated by UserInterfaceTranslationCompiler.py - DO NOT EDIT MANUALLY
// Copyright (c) 2026-Present : Ram Shanker: All rights reserved.

#include "UserInterfaceTranslationCompiled.h"
#include <array>
#include <cstddef>
#include <unordered_map>

namespace UITranslations
{
    // Static translation table: WorldID -> array of UTF-32 strings, one per UILanguage value.
    static const std::unordered_map<uint32_t, std::array<const char32_t*, static_cast<size_t>(UILanguage::COUNT)>> g_TranslationMap =
    {
"""

    entries = []
    for world_id, lang_texts in translation_data:
        if len(lang_texts) != len(LANGUAGES):
            print(f"ERROR: WorldID {world_id} has {len(lang_texts)} translations, expected {len(LANGUAGES)}.", file=sys.stderr)
            sys.exit(1)

        literals = [to_cpp_u32_literal(text) for text in lang_texts]
        entries.append(f"        {{ {world_id}, {{ {', '.join(literals)} }} }},")

    cpp_footer = """    };

    const char32_t* GetUILocalizedString(uint32_t stringID, UILanguage language)
    {
        auto it = g_TranslationMap.find(stringID);
        if (it == g_TranslationMap.end())
        {
            return U"";
        }

        const size_t langIdx = static_cast<size_t>(language);
        if (langIdx >= static_cast<size_t>(UILanguage::COUNT))
        {
            return it->second[0];
        }

        const char32_t* str = it->second[langIdx];
        if (str == nullptr || *str == U'\\0')
        {
            return it->second[0];
        }

        return str;
    }
}
"""

    cpp_path = output_dir / "UserInterfaceTranslationCompiled.cpp"
    cpp_path.write_text(cpp_header + "\n".join(entries) + "\n" + cpp_footer, encoding="utf-8")


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    output_dir = repo_root / "code-core"

    translation_data = build_translation_data(script_dir)
    write_compiled_header(output_dir)
    write_compiled_cpp(output_dir, translation_data)

    print(f"Generated {output_dir / 'UserInterfaceTranslationCompiled.h'}")
    print(f"Generated {output_dir / 'UserInterfaceTranslationCompiled.cpp'}")
    print(f"Compiled {len(translation_data)} strings across {len(LANGUAGES)} languages.")


if __name__ == "__main__":
    main()
